### ISSUE TITLE
[Bug]: Little Box crashes on first tick

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#1]
### Discord Thread

https://discord.com/channels/828292123936948244/1264183063496359997

### What happened?

Even with a schematic only containing the default placed IO components, the game crashes upon pressing the NEXT button.

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1066 Beta on Windows
```

**Comment by Stuffe** [comment]
I can't reproduce, it was probably fixed. Let me know if now
