### ISSUE TITLE
[Bug]: bit switch level unbeatable

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#10]
### Discord Thread

https://discord.com/channels/828292123936948244/1264178076934213754

### What happened?

With the only possible solution for this level, it seems like the game doesn't reliably read the Z state as 0.

![image](https://github.com/user-attachments/assets/9aef8545-783e-4f05-b0ab-135a52462b67)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by MegaIng** [comment]
Not actually unbeatable, but the error message is confusing. The last ON signal should actually be a Z state symbol.

**Comment by Stuffe** [comment]
fixed
