### ISSUE TITLE
[Request]: Comment Hotkey

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#10]
### Request?

A Keybind to enter Comment Mode

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scottanderson** [comment]
The current button is not ideal because the player has to do a lap around the screen with their cursor to click the button between every wire label. Changing the tool to be modal (allow editing multiple wire comments at once), and adding more keyboard controls would be welcome changes.

**Comment by mtreis86** [comment]
When you use tools, for instance in photoshop, the typical way it works is once you click a tool you are using that mode until you click another or some hotkey to change modes.

**Comment by Stuffe** [comment]
Now the adding a comment doesn't deselect the comment tool, which I think addresses batch commenting being tedious
