### ISSUE TITLE
[Bug]: Save location not editable

### ISSUE THREAD

**Issue by x416C6578** [Turing-Complete-Game/Suggestions-and-Issues#100]
### What happened?

Since there's an editable value for the save location in the options, I trie editing that default value to place the saves in a different location (Tried both a inexistent and already created folder).
It's seems as soon as we close the options, the new value is not saved. When I reenter the options, the default value is till there.

My guess: no save/OK buttons to call sa save value and no autosave on modification on this textbox...or unsupported feature.

Anyway, it's a minor inconvenience

Cheers and thanks for the great game ;)

Alex

### Version

Latest (0.314 Beta)

### Operating System

Win10 21H1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Thanks Alex!
Actually that box is just for showing the location and it is editable only so that you copy paste and I know it will fit.

**Comment by cpkio** [comment]
This should not be view only. I got it installed on Windows 10 x64 and found out it saves games to `C:/NvimLua/Godot/app_userdata/Turing Complete`, and I dont want it to save game data to my Neovim installation. It seems it takes folder location from `XDG_CONFIG_HOME` or `XDG_DATA_HOME` which both point to `C:\NvimLua` in my system.

**Comment by cpkio** [comment]
@MegaIng Of course I did verify.
