### ISSUE TITLE
[Bug]: Lvl 3Bit Decoder output

### ISSUE THREAD

**Issue by x416C6578** [Turing-Complete-Game/Suggestions-and-Issues#101]
### What happened?

Seems to be a mismatch between the DESIRED and CURRENT bity output numbering (see image).
Seems like the desired starts at 1 (position) and current at 0 (value)
![image](https://user-images.githubusercontent.com/47071345/142888935-7385a234-3d32-4821-8ffd-0049d3fcbc9e.png)

### Version

Latest (Beta 0.315)

### Operating System

Win10 21H1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Not sure where the `?` comes from, but the general pattern of mismatching can be achieved by modifying the circuit while it's active and then continue stepping it:

https://user-images.githubusercontent.com/26136419/143070565-ceb3bf15-aad5-499f-9cf6-54794562e55f.mp4

**Comment by x416C6578** [comment]
if I recall correctly, I tested in a single pass with F6. Hope this helps for the debug (finding the ? and maybe the source of the mismatch while accepting the circuit as a valid answer)

**Comment by Stuffe** [comment]
I think this might have been fixed
