### ISSUE TITLE
[Bug]: ALPHA: Crash when including non-existing assembly file

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#101]
### Discord Thread

https://discord.com/channels/828292123936948244/1266323190272102443

### What happened?

I've typed `include "aaa"` at the beginning of my program to see the new keyword. (I've never created a file "aaa".)
The moment I typed the second `"`, the game crashed. Now it crashes every time I try to open the assembly editor.

(Reported by NO_NAME on Discord)

### Version

0.1083 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed
