### ISSUE TITLE
[Request]: Components and others

### ISSUE THREAD

**Issue by Bananenmilch** [Turing-Complete-Game/Suggestions-and-Issues#102]
### Request?

These are some components, that are very simple in their use, so I utilized them multiple times when building my architectures. I had to build all of them myself, which was fun, but it would be a lot mor comfortable if they are in the component menus.

64bit components:
- 64bit AND
- 64bit OR
- 64bit XOR
- 64bit NOT
- 64bit NEG
- 64bit MUL     |      this one is very important, as wanted to multiply numbers bigger than 255 multiple time before but had to 
use assembly code to cover for the missing component.
- 64bit Switch
- 64bit ADD

Other components:
- Byte to 64bit converter     |     this works at the moment already by just connecting the byte wire to the 64 Bit wire, but only for positive numbers. negative numbers have to be converted as the signed bit moved to the 64th bit instead of the 8th.
- Byte integer dividers/modulo  |   not as important but really difficult in the 8x8 component space if not impossible

Other:
- The 64bit counter: an option to change the increment value like in the byte counter
- The ability to save 64bit values in the stack      |      I got this problem when I wrote an assembly program that had more than 255 bytes and my function return stack saved the wrong number due to overflow
- more wire colors      |     I ran out multiple times when construcing compact components
- the ability to put watched states on 64 bit rams
- displaying the register/counter values on components with registers/counters in them as well as watched states on those components     |     doesn't work on any components with 64bit registers/counters in them. Haven't checked with byte registers/counters

Looking forward to future updates. I love this game

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
- For byte to 64 bit converters, it's not as simple as just moving the sign bit. It's called sign extension where you copy the bit to all higher bits. That being said, it's not any harder.
- For byte dividers and Modulo, you can definitely fit them in a custom component. I and others have done so.
- For the 64 bit stack, I think you'll need to use the 64 bit memory. Currently the normal memory does not store 64 bit values and so you'll need to deal with the 1 tick read delay when using 64 bit memory. If you don't need more than 256 storage cells, you can always chain the byte components together and remove the read delay.

**Comment by Stuffe** [comment]
In the future the custom component folder structure be reflected in the component menu
