### ISSUE TITLE
[Bug]: ALPHA: Number probes visual bugs

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#102]
### What happened?

Number probes have some visual bugs:
# Memory probe only shows content that fits within it's box
# Wire probe only shows least significant Byte of the number in hexadecimal(FF) number format

![image](https://github.com/user-attachments/assets/bf71ebf1-ff6f-4aef-b807-01428643b83c)
![image](https://github.com/user-attachments/assets/a35672ca-ab60-45a5-9551-a71aaef4c40f)

(Reported by Think on discord)

### Version

0.1083 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed next patch
