### ISSUE TITLE
[Bug]: ALPHA: crash due to being able to insert level components in sandbox -> component factory

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#103]
### Discord Thread

https://discord.com/channels/828292123936948244/1266386765825048627

### What happened?

How to reproduce: Go to sandbox, then in there go to the component factory. Then place a level input block.

This results in an immediate game crash, with the following printed to terminal:
```
No function matched [34march_get_input[0m([33mAnyInt[0m).
[31m(849)[0m
                let result = [31march_get_input(.trial)[0m
                .level_inputs[0] = result
```
I can't repro, but CensoredUsername reports Windows 10 & 0.1084.

(Reported by CensoredUsername on discord)

### Version

0.1084 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
