### ISSUE TITLE
[Bug]: ALPHA: Multiple pins/probes in one square doesn't display an error

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#104]
### Discord Thread

https://discord.com/channels/828292123936948244/1266436652096819353

### What happened?

* Placing 2 pins in the same square in the component factory doesn't display any error message like it use to.
* Placing 2 probes in the same square in a component factory doesn't display any error message (I can't recall whether the old version did or not).

### Version

0.1084 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed next patch
