### ISSUE TITLE
[Bug]: ascii screen has things displaying outside of "pixels"

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#104]
### What happened?

seem to be a single pixel higher than it should be at the very least
![image](https://user-images.githubusercontent.com/61679450/142972866-cfde1b40-15b6-48c8-a1f1-ba858e4b8917.png)

### Version

Latest

### Operating System

win 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can reproduce this. There seems to also not be enough distance between lines, they also seem to be one pixel to close together.

**Comment by Stuffe** [comment]
This screen will be replaced shortly
