### ISSUE TITLE
[Bug]: 2 programs with the same code not updating correctly 

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#105]
### What happened?

changing code in the assembly editor will only update the active "program" and not others running the same code
it can be fixed by changing the not updated one to something else and back again
![image](https://user-images.githubusercontent.com/61679450/142980510-f38b58a8-e362-4847-bd26-3cc55bf5abc1.png)

### Version

Latest

### Operating System

win 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I am pretty sure this was fixed
