### ISSUE TITLE
[Bug]: ALPHA: When opening an old schematic, all NOR gates are turned into OR gates

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#105]
### Discord Thread

https://discord.com/channels/828292123936948244/1266428785838784582

### What happened?

I've had a few levels where I opened the `old_Default` schematics to copy the solution, but the circuits would no longer be correct because all `NOR` gates had been swapped out by `OR` gates.

(Reported by Swan on Discord)

### Version

0.1084 and 0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This is fixed
