### ISSUE TITLE
[Bug]: ALPHA: manual page on component factory is out of date

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#106]
### Discord Thread

https://discord.com/channels/828292123936948244/1266446761644392551

### What happened?

Manual page on component factory is out of date, It still talks about unbuffered output pins among other things.

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
