### ISSUE TITLE
[Bug]: Bit size missing restrictions

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#107]
### Discord Thread

https://discord.com/channels/828292123936948244/1266442181183541309

### What happened?

Bit size button allows selecting values less than 2
Placing a component while a bit size of 0 and less is selected crashes the game with this error:
```
Was expecting a type here.
[31m(1409)[0m
            var v537 = (<[31mU-1[0m> 0)
```
Same happens for values more than 128

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This was fixed
