### ISSUE TITLE
Keyboard Component Crash[Bug]: 

### ISSUE THREAD

**Issue by nekokiwa** [Turing-Complete-Game/Suggestions-and-Issues#108]
### Discord Thread

https://discord.com/channels/828292123936948244/1266587058152144896

### What happened?

Passing a game tick while the keyboard component's read next pin is active causes the game to crash. The crash takes a second or to happen after pressing the next tick button.

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1087 Beta on Windows
```

**Comment by Stuffe** [comment]
cant reproduce, unclear if its still a thing
