### ISSUE TITLE
[Bug]: Alpha: Square pins are no longer square

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#109]
### Discord Thread

https://discord.com/channels/828292123936948244/1266584585878372453

### What happened?

Square [delay] pins are no longer squareJust cosmetic, but it makes them a bit harder to distinguish.

### Version

0.1079 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
There are technical reasons why they are round now
