### ISSUE TITLE
[Bug]: Level Level Soft Crash on Right Click

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#11]
### What happened?

While having components selected, right clicking in empty space will reload the component. In the event of being on a level in a folder, it will switch you to a different component. (Possibly related to #6 )

[Initial Report](https://discord.com/channels/828292123936948244/850737218759032892/907345349046317056)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is fixed
