### ISSUE TITLE
[Bug]: ALPHA: Gate score increases when deleting gates

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#110]
### Discord Thread

https://discord.com/channels/828292123936948244/1266688094359261255

### What happened?

1. Create a new empty schematic in sandbox gate score is 99999 (I assume this is to stop debug builds from ending up on the leaderboard by accident).
1. Place a NAND gate (gate score now 100000).
1. Delete NAND gate.
Gate score for the now empty schematic is now 199998 and neither of the expected 0 or 99999.

### Version

0.1079 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
