### ISSUE TITLE
[Bug]: MacOS crash on startup (M1 on 12.0.1

### ISSUE THREAD

**Issue by Liquidmantis** [Turing-Complete-Game/Suggestions-and-Issues#110]
### What happened?

Upon launching the game there is a brief flicker of a window, but a few seconds later Steam just goes from "Running" back to "Play".

No crash report, but I ran a trace log while launching.  Attached.
[turing-crash.txt](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/7590897/turing-crash.txt)

### Version

Latest

### Operating System

MacOS 12.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
M1 macs are not supported yet unfortunately :/

**Comment by Liquidmantis** [comment]
@Stuffe Thanks for the fast reply!  I figured as much.  To the PC it is then!
