### ISSUE TITLE
[Bug]: Alpha: Run fast button just... doesn't work for some reason

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#111]
### Discord Thread

https://discord.com/channels/828292123936948244/1266684680359645288

### What happened?

I'm not sure why, but on my MIPS architecture (and seemingly only that one, creating a new one doesn't cause the bug), the run fast button runs one tick, and then stops.

(Reported by Jace_M_09 on Discord)

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
this was fixed
