### ISSUE TITLE
[Request]: API with level meta

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#111]
### Request?

It would be nice to have an additional API to figure out which levels are which.

If possible, it would be nice if this info is accessible 

- Level Id (as the key)
- Level display name
- Position of level in profile page (if possible)
- Is the level scored?
- Is it an architecture level?

(we assume that we can decide if the tick value is useful based on `score & architecture`)

Very cool, but not sure if it actually exist: Permanent ID of the corresponding LevelGate inside of level_map. But if this last part would slow it down, do everything else first :-)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Now added: https://turingcomplete.game/api_level_meta - Meta data for levels (enum_number, enum_id, title, is_architecture, no_score. The order here is the same as on player profiles.
