### ISSUE TITLE
[Bug]: ALPHA: Going out of bounds of the map

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#112]
### Discord Thread

https://discord.com/channels/828292123936948244/1266633803624091709

### What happened?

Game has no invisible barrier that prevents you from moving outside the play area and you can go outside of the map and crash the game with this error: 
```
fatal.nim(54)            sysFatal
Error: unhandled exception: value out of range: 32867 notin -32768 .. 32767 [RangeDefect]
```

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
