### ISSUE TITLE
[Bug]: Alpha: Wires sometimes turn invisible when creating/moving other wire nodes

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#113]
### Discord Thread

https://discord.com/channels/828292123936948244/1266614611864588308

### What happened?

Seems to happen mostly when the wire node you're moving is connected to a long wire, I don't remember if it can occur on the wire attached to the node you're moving but I think it did once.

### Version

0.1087 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think this is fixed
