### ISSUE TITLE
[Bug]: Alpha: Cannot set static value of a custom component to 1

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#114]
### Discord Thread

https://discord.com/channels/828292123936948244/1266605616441462866

### What happened?

Since the bit width tool doesn't work, and for some reason trying to manually set the value of 1 by clicking on the static value display on the component instead sets it to 2, it's completely impossible to set the static value to 1.

### Version

0.1087 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
