### ISSUE TITLE
[Bug]: Tests are not exhaustive enough

### ISSUE THREAD

**Issue by DEPREZR** [Turing-Complete-Game/Suggestions-and-Issues#114]
### What happened?

In my playthrough sometimes I was able to validate some levels, and I figured out that in fact my hardware (or code) was broken some levels later.

2 examples :

1) When adding cond to leg architecture, I forgot to "disable" save on reg0 in case instruction is condition and not operation.
Tests still validated my stuff and I figured out the issue only while programming divide level.
2) During divide level, I used a really simple algorithm to add divider to a register starting from zero, until I exceed numerator... In my first attempt, I forgot to handle case when result of addition overflow 255. And half of the time, test suit validated my stuff with this mistake, not checking overflow case.

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
For 1), that has been discussed before over on discord: https://discord.com/channels/828292123936948244/850737218759032892/909195581782626336 , but it's good that this is now here as well.

For 2) Yes, that should probably be always checked for.

**Comment by sethtadd** [comment]
To add to point 2,

I was able to pass the divide level almost every time I checked my solution except for in cases where the denominator evenly divides the numerator. These specific cases are rarely randomly generated, so I think they should be explicitly included.

**Comment by Stuffe** [comment]
Divide has probably been fixed (and also has its own issue). There was a new test added for LEG as well
