### ISSUE TITLE
[Bug]: Alpha: Instruction bits can be modified even when the specification is locked

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#115]
### Discord Thread

https://discord.com/channels/828292123936948244/1266504541407543456

### What happened?

Clicking on an instruction bit in the specification editor will change it regardless of if the specification is locked or not.

### Version

0.1087 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
