### ISSUE TITLE
Search bar is active within levels

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#115]
### What happened?

Its not visible, but if you click in the upper right corner where the search bar is on the level map, you can start typing and it will look up the various level names.

What's really fun is that hovering over the names will highlight various components on your active schematic.

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
