### ISSUE TITLE
[Bug]: Incorrect screen ratio in Assembly Editor

### ISSUE THREAD

**Issue by MunchDev** [Turing-Complete-Game/Suggestions-and-Issues#116]
### What happened?

Problem as above. Not sure how to reproduce it, I just open any random programming level and boom, the assembly is distorted (the line number and the code, but not the index of the byte on the right hand side)

### Version

Latest

### Operating System

MacOS 12.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can you screenshot? Also, is it fixed by restarting? If not, upload your save to https://turingcomplete.game/report_bug

**Comment by MunchDev** [comment]
Not fixed by restarting, [screen shot here.](https://postimg.cc/Sn1CBHmd)

**Comment by MegaIng** [comment]
I think that is just the new font: #99

**Comment by MegaIng** [comment]
Although the byte index on the left is not correctly aligned with the rest.

**Comment by MunchDev** [comment]
> I think that is just the new font: #99

If I were to offer my suggestion, the new font looks _really, really bad_, especially for someone using 16:10 screen ratio😒

**Comment by bombitmanbomb** [comment]
![image](https://user-images.githubusercontent.com/11261721/143296955-32463e9d-d6c2-4764-accb-a5a0bff0d868.png)
Also getting this issue
line jumping is Unusable currently with the offsets

**Comment by tali713** [comment]
Can confirm, it appears that the central issue is using fonts with different heights for byte references vs code, here is a screenshot with code execution halted at breakpoint:
![ui_bug](https://user-images.githubusercontent.com/611289/143297421-7208eef3-839e-47cf-bb73-56adefe1ac27.png)

**Comment by zender42** [comment]
Same thing here. Line numbers on the left no longer match with line addresses on the right. Also, the line highlight gets progressively more inaccurate the further down in the code you go.
![img](https://user-images.githubusercontent.com/8879404/143300548-21519cef-4540-4248-80dc-54301ea235e3.PNG)

**Comment by MegaIng** [comment]
The font change has been reverted for the moment.

**Comment by Stuffe** [comment]
The font was reverted, only special characters use the new font
