### ISSUE TITLE
[Bug]: ALPHA: Latency RAM crash

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#116]
### Discord Thread

https://discord.com/channels/828292123936948244/1266691024139325450

### What happened?

Placing down a latency RAM crashes the game with this error:
```
The left hand side is of type [33mU64[0m, while the right hand side is of type [33mAnySint[0m.
[31m(967)[0m
            var v318 = (<U1> ([31m_load(64, VALUE_BUFFER, 256) >= .tick[0m))
```

Version and OS unconfirmed.

### Version

0.1087 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
