### ISSUE TITLE
[Bug]: Old name? Demux = decoder?

### ISSUE THREAD

**Issue by x416C6578** [Turing-Complete-Game/Suggestions-and-Issues#117]
### What happened?

Level: Calculations
In the instructions, the tip mentions a demux...I guess it's the old name for the 3 bit decoder?

![image](https://user-images.githubusercontent.com/47071345/143279315-7e12b789-eb9b-498a-8a43-5c70ac1eff54.png)

### Version

Latest (Beta 0.329)

### Operating System

Win10 21H1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Yes, that is the old name

**Comment by Stuffe** [comment]
Fixed next version
