### ISSUE TITLE
[Bug]: ALPHA: Assembler binary doesn't update when changing specification

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#117]
### Discord Thread

https://discord.com/channels/828292123936948244/1266785141209038849

### What happened?

In the assembler, changing the specifications (e.g. changing the bits of an existing instruction or field) doesn't automatically reassemble the file. It only updates after changing the asm file itself.

I'd expect the file to be reassembled.

### Version

0.1087

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
