### ISSUE TITLE
[Bug]: ALPHA: Crash when deleting field in specification

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#118]
### Discord Thread

https://discord.com/channels/828292123936948244/1266788703431430195

### What happened?

To reproduce from a new schematic:
- Place an assembler.
- Edit the specifications.
- Add a new, second field (after to registers).
- Delete the existing instructions (mov, mov, jmp).
- Create a new instruction which only takes the new, second field as argument.
- Click the lock twice to update the GUI.
- Delete the old 'register' field.
- Crash

When restarting the game, none of the changes are saved.

### Version

0.1087

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
On crash:
fatal.nim(54)            sysFatal
Error: unhandled exception: index 6 not in 0 .. 5 [IndexDefect]

On restart:
ASSEMBLY SPEC ERROR Field name 'field' not defined
ASSEMBLY SPEC ERROR Field name 'field' not defined
```

**Comment by Stuffe** [comment]
fixed next patch
