### ISSUE TITLE
[Bug]: The game does not open the correct schematic

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#118]
### What happened?

When a schematic is inside a folder and you try to "jump" to it (e.g. not via Switch Schematic menu), it fails to open and the first schematic in the root folder is opened instead.

This includes:

- Opening a level from the level map when the last opened schematic is inside a folder
- Using the "edit custom component" button on a specific component.
- Using the "open component factory" in the top bar.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
