### ISSUE TITLE
[Bug]: Freeze on startup on MacOS

### ISSUE THREAD

**Issue by feuerball11** [Turing-Complete-Game/Suggestions-and-Issues#119]
### Discord Thread

https://discord.com/channels/828292123936948244/1267398191285014570

### What happened?

On my Apple Macbook Max with an M3 (Sonoma 14.1), the game sadly freezes instantly when starting. I dont even get a window. 
I also cant upload any save, as there is no save generated. 

I tried starting it via console, and this is the output I get: 

```
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Apple M3 Max
OpenGL ES Batching: ON
 
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
[S_API] SteamAPI_Init(): Loaded '/Users/marius.janke/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
```

### Version

Unknown - Latest

### What OSes are you seeing the problem on?

MacOS

### Relevant `debug.log` output, search next to the exectuable

```shell
debug.log is 0 bytes big. So nothing to post here. Sorry
```

**Comment by Stuffe** [comment]
Apparently updating macos fixes this
