### ISSUE TITLE
[Bug] Default register will not spawn in all OVERTURE level.

### ISSUE THREAD

**Issue by aoisensi** [Turing-Complete-Game/Suggestions-and-Issues#119]
### What happened?

![image](https://user-images.githubusercontent.com/1350990/143443903-9d7c7417-8c37-4ac1-867f-cf14b842d8ca.png)

I bought this game at 2021/11/24 0:00 JST and continued to play for 8 hours.
I remember there was a game update after that.
Today, I play again earlier, this happened.
## Tried
- Reboot game
- Create new schematic
- Find it on the circuit

They didn't solve.

### Maybe...?
I bought and replaced new HDD yesterday.
(But it is `D:\` and I installed game on `C:\`)

sorry for bad english

### Version

Latest

### Operating System

Windows 10 Pro 64bit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aoisensi** [comment]
I uploaded save data

**Comment by MegaIng** [comment]
Can't you place new registers? You should have them under MEM.

Although you probably need RegisterPlus (those with an extra permanent output). That should be under CUST

**Comment by aoisensi** [comment]
Yes. It is placeable and working.

**Comment by Stuffe** [comment]
Those registers were supposed to be replaced by the "RegisterPlus" custom component. Did you maybe delete it? (it is still a bug)

After completing the level Turing Complete, new schematics no longer have registers

**Comment by aoisensi** [comment]
> new schematics no longer have registers
Oh I see.
But I didn't delete Register manually.
