### ISSUE TITLE
[Bug]: Crash when clicking "Load size from constant value"

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#12]
### Discord Thread

https://discord.com/channels/828292123936948244/1264176414731796582

### What happened?

Clicking the "Load size from constant value" will _eventually_ crash the game. 
I am not sure what directly causes this, but it is reliably reproducible for me.
![image](https://github.com/user-attachments/assets/d07592c9-d0e0-41df-97a4-d0bfed9e28a5)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
