### ISSUE TITLE
[Bug]: Green marbles should not roll up hill

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#12]
### What happened?

The game renders green marbles rolling through all energized paths regardless of whether the marbles have a place to exit at the end of that path.

![image](https://user-images.githubusercontent.com/662325/140815283-af958e15-b3dc-4c14-adca-4d277017fc89.png)

Marbles should only roll from energized output to other inputs on the circuit, but not along all energized paths. 

![image](https://user-images.githubusercontent.com/662325/140816119-f9220552-fbf5-4cad-b0c3-e5c07a230ef0.png)

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
No. I strongly disagree with this. Circuits are powered, not outputs. It doesn't matter if there is a target for the energy or not.
