### ISSUE TITLE
[Bug]: ALPHA: Components in CC only take up one square

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#120]
### Discord Thread

https://discord.com/channels/828292123936948244/1267441845634465792

### What happened?

Components placed inside a custom component will only ever take up one blue square in the custom components model, even if they span multiple cells. 
On the old patch, a component in multiple cells at once would create blue squares for all those cells.

Note: Fixing this would probably break existing schematics, so it should stay like this or be fixed soon-ish (or a workaround like allowing the fixed cc's to overlap with other stuff).

### Version

0.1087

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixing this is not worth the complexity
