### ISSUE TITLE
[Bug]: Memory leak in score sync view

### ISSUE THREAD

**Issue by Galaxyqasar** [Turing-Complete-Game/Suggestions-and-Issues#120]
### What happened?

When opening the score sync view from the main menu the game allocates all available memory (~12 GB) in about 20 seconds.

### Version

Development

### Operating System

Linux (Manjaro KDE)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed now
