### ISSUE TITLE
Selection desync when panning

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#121]
### What happened?

If you have components selected and pan the map (which I do frequently when trying to move small-hitbox items like NOT and BUFFER), components get deselected but wires do not.  If you don't notice and try your move again without reselecting the components, you can end up with a very messy situation.

(Possibly related to https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/85)

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I would suggest panning with middle mouse button. That doesn't have this effect.

**Comment by altrag** [comment]
I don't have a middle mouse button.  I have a scroll wheel that theoretically can be pressed to activate the middle click action, but most of the time the wheel just does what wheels do instead of clicking so not really a (useful) button in any meaningful context.

**Comment by SunCatMC** [comment]
Seems to be fixed as of 0.544
