### ISSUE TITLE
[Bug]: ALPHA: Short circuit location not shown

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#122]
### Discord Thread

https://discord.com/channels/828292123936948244/1267444999797080151

### What happened?

My circuit has a short circuit, presumably inside one of the components, but the error message is just "Short circuit!" with no indication where/which CC has the issue.

Short circuits in the top level are highlighted in red, but a clickable error message that takes you to it, would be also be great.

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
