### ISSUE TITLE
[Bug]: ALPHA: Missing NOT wrapper

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#123]
### Discord Thread

https://discord.com/channels/828292123936948244/1267447104142577674

### What happened?

The bit NOT gate has changed size, but there is no automatically created wrapper `old_components/1/OLDNot/` CC like for the other built-in size changes.

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
