### ISSUE TITLE
[Bug]: File component addresses wrong

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#124]
### Discord Thread

https://discord.com/channels/828292123936948244/1267461357146607818

### What happened?

Addresses in the file component start to become offset, and read results lower than they should do, when the address starts to become greater than ~1 million 

attached in the pic is my best attempt to recreate the problem. A file with 1 million 0x00 bytes, then a hundred 0xFF bytes.
reading address 0xF4240 (1,000,000 - where the FFs are) the file component reads in zeroes.
reading address 0xF4480 (1,000,576 - larger than the length of the file?) the file component reads in the correct data

This behaviour does not happen with 100,000 zeroes, and starts somewhere in between. 
The file component constant crashes make it difficult to pinpoint exactly when :(

test file made with simple python script:
```py
file = open("a.bin", "wb")
file.write((0).to_bytes() * 1000000)
file.write((1).to_bytes() * 100)
file.close()
```
![image](https://github.com/user-attachments/assets/fa4acbfe-2a8b-47d7-bc9a-bcebd6c151a9)

![image](https://github.com/user-attachments/assets/bfd320a0-dc7d-4944-a177-938425141bd3)

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I couldn't reproduce. Maybe a silly question, but did you "tick" after setting the address? Otherwise the output wont update
