### ISSUE TITLE
[Bug]: ALPHA: Hang after exiting factory and now on start up

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#125]
### Discord Thread

https://discord.com/channels/828292123936948244/1267495178223226933

### What happened?

The game hung after I exited the component factory (from 8008 Intel/top/ALU/) back to the sandbox and now hangs on start up.

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
This save hangs on start up:
[bug-125_Turing Complete.zip](https://github.com/user-attachments/files/16415138/bug-125_Turing.Complete.zip)

**Comment by Stuffe** [comment]
please check if this is fixed in 0.1091, which I am uploading now

**Comment by Gelthir** [comment]
Still hangs in 0.1091

**Comment by Gelthir** [comment]
Ccan confirm: fixed in 0.1092
