### ISSUE TITLE
[Bug]: ALPHA: Crash when adding label to jump command

### ISSUE THREAD

**Issue by danrog729** [Turing-Complete-Game/Suggestions-and-Issues#126]
### Discord Thread

https://discord.com/channels/828292123936948244/1267515139939369011

### What happened?

I have a "jmpi" (jump immediate) command that jumps to %a if %b != 0
jmpi %a(label) %b(register)
00000bbb aaaaaaaa 00100010
it seems reversed to make it big-endian, as the assembler is little-endian by default. **it is this reversal that is crashing the game**

When I type the command and the label it all works fine, it recognises the label, etc. When i type the first character of the %b argument, the game immediately crashes.

Tested this on Windows and Linux, happens on both

### Version

0.1087 Beta

### What OSes are you seeing the problem on?

Windows, Linux

### Relevant `debug.log` output, search next to the exectuable

```shell
debug.log:

Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1087 Beta on Windows



Console that opens on game startup:

PORT 5002
REQUEST: 1 sim_do
command: mode_reset -1
RESPONDING sim_do 1
REQUEST: 3 compile_and_run
RESPONDING compile_and_run 3
REQUEST: 4 sim_do
command: refresh -1
RESPONDING sim_do 4
REQUEST: 5 sim_do
command: mode_reset -1
RESPONDING sim_do 5
REQUEST: 7 compile_and_run
RESPONDING compile_and_run 7
REQUEST: 8 sim_do
command: refresh -1
RESPONDING sim_do 8
REQUEST: 9 compile_and_run
RESPONDING compile_and_run 9
REQUEST: 10 sim_do
command: refresh -1
RESPONDING sim_do 10
```

**Comment by Stuffe** [comment]
fixed next patch
