### ISSUE TITLE
[Bug]: Small Programs are not actually limited to 256 bytes

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#126]
### What happened?

![image](https://user-images.githubusercontent.com/26136419/143591690-7390e71f-dbcb-488f-bb45-b91ebcb3f9b7.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next update
