### ISSUE TITLE
[Bug]: ALPHA: CC not present after importing schematic from stable

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#127]
### Discord Thread

https://discord.com/channels/828292123936948244/1267534583080030275

### What happened?

Imported schematics from version 0.1059 do not have placed custom components.
Compare before and after upgrading to version 0.1088.
The schematics are still present on the file system and open fine in the factory.

### Version

0.1088 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
