### ISSUE TITLE
[Bug]: When you delete a custom component, that is used in components but not in architectures, it shows an empty list in confirmation box

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#127]
### What happened?

I wanted to delete a component that I used as part of another component (but not in any architecture). Amusingly, confirmation box said that "It is used in" and then didn't elaborate on where the component is actually used.
![bug-missing](https://user-images.githubusercontent.com/26610984/143607596-1e11b867-65e6-446e-95e2-88498446bd03.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next version
