### ISSUE TITLE
[Bug]: ALPHA : fix phantom point in component factory

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#128]
### Discord Thread

https://discord.com/channels/828292123936948244/1267622698855567453

### What happened?

phantom point in component factory, visible only on wires

![image](https://github.com/user-attachments/assets/0ef9ec17-12c0-4df9-8136-e21c288bebb0)

### Version

0.1090 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
