### ISSUE TITLE
[Bug]: Lists of components and architectures are not separated from each other in component deletion confirmation screen

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#128]
### What happened?

When you delete a component that is used both in architectures and other components, then there will be no space or comma between list of architectures and list of components
![bug-nospacing](https://user-images.githubusercontent.com/26610984/143609097-d50c43fa-caa5-44b7-b343-816ff5efefb1.png)

![bug-nospacing2](https://user-images.githubusercontent.com/26610984/143609118-6c5f3f43-f84f-4f9a-85f9-4df835458f5d.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SunCatMC** [comment]
relates to #127

**Comment by Stuffe** [comment]
fixed next version
