### ISSUE TITLE
[Bug]: ALPHA: ctrlV Crash with custom component

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#129]
### Discord Thread

https://discord.com/channels/828292123936948244/1267620756481900634

### What happened?

i have that in sandbox .
when i copy this and go to component factory , i crash on ctrl V every time . 
but with smaller assembly I did not have the problem. this one crashes every time . 
I will try to see if it is a particular component and I will update the post if I find it. => it's the custom component

![image](https://github.com/user-attachments/assets/822604ad-1772-41bb-afdc-5596357dc3f3)

### Version

0.1090 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
