### ISSUE TITLE
[Bug]: Modifying nested custom component doesn't update its representation in higher level component, which can lead to crash and unintended state

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#13]
### What happened?

If you modify a component that is nested inside another component, I expect that any changes I make to the form of the inner component will be visible from inside a higher level component without issues. Instead the component doesn't update, and when you try to click it it crashes the game. When you reopen the game, the lower level component is updated, but the higher level component gets a ghost filled tile, that is only visible from its own component menu and doesn't have any associated cache maps connected to its presence. It doesn't look like it's possible to remove it.
Here are screenshots of results after a couple of crashes:
<img src="https://user-images.githubusercontent.com/26610984/140816334-e2fe5ddb-3748-4c9c-a5f4-d3739f1b79db.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/26610984/140816341-7494f8e0-f469-4078-b77b-df04e49f07ab.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/26610984/140816316-1bfc3954-279c-4243-b48b-a5731c9b665a.png" width=50% height=50%>

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next upload
