### ISSUE TITLE
[Bug]: Removing a component with another component linked to it causes a crash

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#13]
### Discord Thread

https://discord.com/channels/828292123936948244/1264172277281456140

### What happened?

Linking a component to another, then removing the linked component will crash the game.
Tested with the console screen linked to ram. Deleting the ram component crashes the game.

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
