### ISSUE TITLE
[Bug]: 64bit inputs have delay written next to them

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#130]
### What happened?

Value is the 64bit input in the image.

![image](https://user-images.githubusercontent.com/26136419/143621669-2742e30f-a5a3-4fa6-8825-e3a710739ec6.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
this is not a bug. Input pins can have delay if they are connected up to a memory component

**Comment by MegaIng** [comment]
@Stuffe Then it's a bug that this only happens sometimes

**Comment by MegaIng** [comment]
For example in this slightly messy custom component I would think that the Value should also have a delay then. 
![image](https://user-images.githubusercontent.com/26136419/143624987-66e06a2e-86f5-4473-af9c-ce6527f5b2fa.png)
