### ISSUE TITLE
[Bug]: ALPHA: Imported IO pins offset

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#130]
### Discord Thread

https://discord.com/channels/828292123936948244/1267714151132958771

### What happened?

After importing a CC with smaller (bit, 8, 16, or 32-bit) IO pins the new larger IO pins are placed with their centres at the centre of the old ones. This causes the pin to overlap the connecting wire, and requires manual fixup for every pin.
If the import placed the pin so that its connection matches would reduce this manual work. Granted it is not guaranteed to work flawlessly every time, as the new pin position might be in a different square thus changing the foot print, but this is IME a less frequent problem.

64-bit are not affected.

### Version

0.1090 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
