### ISSUE TITLE
[Bug]: ALPHA: Crash at startup after opening a custom component

### ISSUE THREAD

**Issue by getItemFromBlock** [Turing-Complete-Game/Suggestions-and-Issues#131]
### Discord Thread

https://discord.com/channels/828292123936948244/1268161609705062554/1268161609705062554

### What happened?

I opened a custom component from my old (pre alpha) save file and the game crashed while opening it. Now the game crash at startup once it enters the main menu.
I have sent my savefile to Stuffe via discord DMs, let me know if there is anything more you want me to do

Note: the debug log does not contain anything more than what I have filled bellow

### Version

0.1093 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1093 Beta on Windows
```

**Comment by getItemFromBlock** [comment]
I think this might be related to https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/125, but this issue has been marked as fixed

**Comment by Stuffe** [comment]
fixed next patch
