### ISSUE TITLE
[Bug]: Game says "You should POP value 0 of the Stack", which conflicts with level log

### ISSUE THREAD

**Issue by jonah-andermin** [Turing-Complete-Game/Suggestions-and-Issues#131]
### What happened?

On the level "Push and Pop" I am instructed that I should have popped the value "0". However this should not be possible because we are only pushing a value when the value is non-zero.

I have attached an image of the state at input 2:

tick 0: input = "219"
tick 1: input = "0" 
on tick 1 the value 219 is output, but I am instructed that I should output 0 instead

![tc_Stack](https://user-images.githubusercontent.com/91590540/143623012-fe393df2-e4ef-4938-a5fa-fc3c4cb306ec.png)

### Version

Latest

### Operating System

Windows 7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Can you please upload your save files here: https://turingcomplete.game/report_bug

**Comment by SunCatMC** [comment]
> tick 1: input = "0"
that's not true, as you don't have the input enabled on this tick

so the issue here is that the game or the INPUTS menu don't diffirentiate between input being off or being on and giving 0

**Comment by Stuffe** [comment]
The error message is wrong. That is fixed in the next update
