### ISSUE TITLE
[Bug]: ALPHA: Glitched entry after renaming the currently edited component

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#132]
### Discord Thread

https://discord.com/channels/828292123936948244/1268273481834041375

### What happened?

Buttons "load" and "delete" are visible but they shouldn't. (They weren't before the rename.)
Clicking "load" (or double clicking) does nothing. I was too afraid to try "delete".

Loading a different component and loading this one again fixes the problem.
![Screenshot from 2024-07-31 20-19-19](https://github.com/user-attachments/assets/5b8ea38f-ef32-435c-af75-01a1146f4ff0)

### Version

0.1093 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch

**Comment by piotrsiupa** [comment]
This is still a bug in 0.1106.
