### ISSUE TITLE
[Bug]: Buffer is unavailable on the level "Conditions"

### ISSUE THREAD

**Issue by onoderis** [Turing-Complete-Game/Suggestions-and-Issues#135]
### What happened?

Buffer is unavailable on the level "Conditions". It doesn't show on the "gates" menu.
![image](https://user-images.githubusercontent.com/9282242/143688926-8bf72c4e-1338-4993-a8a9-16045318c4a8.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is correct: "One Way" the level that unlocks Buffer doesn't lead to Conditions, so Buffer is not usable.
