### ISSUE TITLE
[Bug]: Potential bug (too restrictive?) with Circular dependency

### ISSUE THREAD

**Issue by x416C6578** [Turing-Complete-Game/Suggestions-and-Issues#136]
### What happened?

I'm not quite sure if this should be considered a bug, but when using the component factory, I tried creating some sort of Register bank / memory routing circuit.

Anyway, fact is, when I tried connecting this component in the first LEG iteration (level: Wire Spaghetti), I had an circular dependency error.

I kindda get that I doubled linked the Input of the LEG architecture to my component (so it does have a link from Input to my component and another link (not connected internally) back to the LEG Input.

Since internally (in the component), those interfaces are not connected (I named thoses "Input" and "Input Select", it's not really a circular dependency...but fact is, it's a component , with a doubled link to another component (LEG Input).

Is that a bug? A limitation? Should it be that way? I'm I missing something?

(By the way, I guess I tried to go overboard / test the limits on that one... I did not need to create a component to do this level, but eh.. I'm exploring ^^)

Thanks again for your time and game ;)

Alex

![image](https://user-images.githubusercontent.com/47071345/143778197-72b2a139-45e7-4518-bb88-9a0d27759ca1.png)

![image](https://user-images.githubusercontent.com/47071345/143778208-8ad96491-104a-4e74-9fc1-dc41fce8f748.png)

### Version

Latest (Beta 0.342)

### Operating System

Win10 21H1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Not a bug, but an intentional limitation: https://turingcomplete.game/FAQ

**Comment by x416C6578** [comment]
Thanks Megalng (both for the Info and the quick response)
