### ISSUE TITLE
[Bug]: ALPHA: Circle / selection around NOT gate is not correctly centered

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#136]
### Discord Thread

https://discord.com/channels/828292123936948244/1268321939731255326

### What happened?

It looks right when the gate is in the default rotation but in 3 remaining cases it's off center.
![Peek 2024-07-31 23-37](https://github.com/user-attachments/assets/6abe9ddd-5e0f-4f2f-b8ae-878267c79300)

### Version

0.1094 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch
