### ISSUE TITLE
[Bug]: NAK 02 is sad when you lose

### ISSUE THREAD

**Issue by NariKiro** [Turing-Complete-Game/Suggestions-and-Issues#137]
### What happened?

On the level AI SHOWDOWN, when you manually play the game (using the arrow keys and enter), and leave NAK 02 with only one card (the joker), NAK 02 becomes sad. However, upon pressing next tick, the message "You lost" appears.
Here is a simple circuit which demonstrates this:
![image](https://steamuserimages-a.akamaihd.net/ugc/1866175185820705789/041FB2691CD508E17A89DF912EBB42FF746E4182/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
And upon pressing next tick:
![image](https://steamuserimages-a.akamaihd.net/ugc/1866175185820706178/C44D7BFBB6C45218C59F9C14B8412598274A98CB/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
