### ISSUE TITLE
[Bug]: ALPHA: Sometimes undo breaks the schematic

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#137]
### Discord Thread

https://discord.com/channels/828292123936948244/1268322991482081280

### What happened?

Sometimes when I undo a change the components don't return to the correct position (they are slightly off) or a wire gets deleted.
I didn't found a way to reliably reproduce it. It seems to happen randomly.

### Version

0.1094 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
I really need a way to reproduce to do anything here. It may also be a side effect of something else going wrong first

**Comment by piotrsiupa** [comment]
By accident I've found a way to reliable reproduce that!
0) Have a component with attached wire.
1) Double-click-drag the component. (Move it without detaching the wire.)
2) Remove the wire.
3) Undo 2 times.
![355246084-ea2e5e12-b106-43de-ae5e-156517a4d4e9](https://github.com/user-attachments/assets/cb9b619b-4a81-4a04-9f22-b4b75f807487)

**Comment by Stuffe** [comment]
fixed next patch
