### ISSUE TITLE
[Bug]: 64 Bit Program does not output values after pressing Stop

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#138]
### What happened?

Steps to Reproduce: 
- Press Step Next
- press Stop
- Output is now broken

![image](https://user-images.githubusercontent.com/11261721/143786957-13fbb2c5-195e-4817-b82e-e06b74fd7e27.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
Why should the program block output after you stopped the simulation? The simulation isn't running any more and would need to be restarted anyway. Or do you mean paused?

**Comment by bombitmanbomb** [comment]
Once you press stop it will NEVER output again. you have to completely reload the level @EnderShadow

**Comment by scottanderson** [comment]
https://user-images.githubusercontent.com/662325/144313148-a4902b0d-1cda-433a-859c-65b49a360b28.mp4

**Comment by bombitmanbomb** [comment]
I have found that (Sometimes) placing a wire and deleting it will fix for One run, as well as editing the code will let it run once

**Comment by bdemmy** [comment]
Same happens here. Also happens when completing a test case and it switches to another. No longer outputs until reloading the level.

**Comment by Stuffe** [comment]
this only happens for the 64 bit program? And does it still happen in the development version?

**Comment by MegaIng** [comment]
@Stuffe Yes, it did only happen for 64bit Programs, but it seems to have been fixed.
