### ISSUE TITLE
[Bug]: ALPHA: inconsistent look of unconnected wires

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#138]
### Discord Thread

https://discord.com/channels/828292123936948244/1268330245837164606

### What happened?

Wires look differently depending on what they were connected to before.
![Peek 2024-08-01 00-09](https://github.com/user-attachments/assets/df37c97b-8eca-4773-b758-62e2bf4091fe)

### Version

0.1094 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch
