### ISSUE TITLE
[Bug]: ALPHA: Probes broken

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#139]
### Discord Thread

https://discord.com/channels/828292123936948244/1268593576258830389

### What happened?

Linked probes show either 0 or 1 in the assembler (may change between ticks without a clear pattern). The probe component shows the correct value.

### Version

0.1095

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
