### ISSUE TITLE
[Bug]: Keyboard component causes a crash when used

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#14]
### Discord Thread

https://discord.com/channels/828292123936948244/1264168386003210323

### What happened?

As title :)
Component places fine,  but clicking on it to engage the keyboard events crashes the game. 

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```
Turing Complete 0.1080 Beta on Windows
HERE C:/Users/User/AppData/Roaming/Godot/app_userdata/Turing Complete/schematics/architecture/ETCa/conv.py
fatal.nim(54)            sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

**Comment by Stuffe** [comment]
fixed next patch
