### ISSUE TITLE
[Feature]: Display current tick output for 1-bit memory and registers

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#14]
### What happened?

The 1-bit memory and register components display the value that they will output next tick. This creates a confusing debugging experience.

The counter has special behavior so that it displays the value it is outputting, and IMO that should be the displayed behavior for all memory components.

https://user-images.githubusercontent.com/662325/140818622-d544308b-64b6-43fb-8c7a-6f0936968890.mp4

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I think that components should be able to display both the value current they currently have and what they will have next tick. Maybe always, maybe with a keybind I am not sure.

**Comment by scottanderson** [comment]
@MegaIng when would you ever want to see the value of the next tick? I have never worked with any hardware or software debugger which supported or enabled such a behavior.

**Comment by bombitmanbomb** [comment]
@scottanderson i beleive the issue is that Some memory components display what they Are displaying and others, like registers, show what they Will display on next tick

**Comment by MegaIng** [comment]
@scottanderson First of all, we don't care about reality.

The point is that when we stepping though the program, it will be interesting to know what the resulting action of this in addition to on what the action is based on.

**Comment by bombitmanbomb** [comment]
@MegaIng by that point it would be something you should test and find out since you can.

Reality is inportant as this is also an educational tool to learn the fundamentals of computing.

**Comment by MegaIng** [comment]
>Reality is important as this is also an educational tool to learn the fundamentals of computing and hardware design.

Sure, but we don't have to limit our design decisions based on what is realistic.

> by that point it would be something you should test and find out since you can.

Sure you can. But why does it hurt to be able to see what affect a tick does easily?

**Comment by bombitmanbomb** [comment]
> Sure you can. But why does it hurt to be able to see what affect a tick does easily?

You can currently run the tick and see what it does without consequence. The editor also provides Code Breakpoints and register value inspectors for debugging what happens which are really handy.

**Comment by MegaIng** [comment]
Did you read the sentence you quoted? Or did you just not understand what it meant?

**Comment by bombitmanbomb** [comment]
I suppose I don't understand what it means. 

From my understanding would be to see what affect the current operation will have. Which at that point one could run said operation and compare values. 

In that instance I would put breakpoints on the before and after with the inspectors set to said components

**Comment by MegaIng** [comment]
But then you can't see the previous state at the same state as the next state. Also, my only question in the quoted section is "But why does it hurt". Which you just straight up ignored.

**Comment by bombitmanbomb** [comment]
Actually, I believe there is a Backtick button for that exact purpose bound to one of the function keys, though I haven't needed to use it yet. I could be wrong on its functionality

`<`

**Comment by MegaIng** [comment]
You mean the mostly broken step back stuff? Sure, but once again "But why does it hurt".

**Comment by bombitmanbomb** [comment]
For complex machines it would double the memory overhead by needing to store every state twice potentially worsening already choppy performance.

For smaller machines it could be cool to see maybe as an opt in feature.

**Comment by MegaIng** [comment]
> For complex machines it would double the memory overhead by needing to store every state twice potentially worsening already choppy performance.

That is to 1000% not an issue ever. Currently the state is stored at least twice, since each wire segments knows which value it has.

**Comment by bombitmanbomb** [comment]
I don't know how it works internally so it could be as easy as adding a display mode.

**Comment by scottanderson** [comment]
Can you point to any example from any context where a debugger shows information from multiple ticks at the same time? If such a feature is useful, surely it must exist somewhere. Being able to see that example would help me understand the benefit of keeping any reference to the current behavior.

**Comment by MegaIng** [comment]
How about the behavior of the current in game debugger? Also, it doesn't show the information of multiple ticks. Showing both the loaded value and value to be saved accurately displays the state of the game, since one tick consists of two different steps.

**Comment by Stuffe** [comment]
Well actually I want it to show the memory state at the end of a tick, not the output. I also don't like inconsistencies so the counter has been fixed. 

Btw think of the first time you were building the OVERTURE computer how confusing it would be when you need to update a register if the number on it does not update. (The component not having the same number on it as the output is also a bit confusing though).

**Comment by scottanderson** [comment]
The current output could be displayed with an asterisk, indicating that the value will change on the next tick. That way the player can see that their action did have some effect.
