### ISSUE TITLE
[Bug]: ALPHA: Placing down a custom component that uses a RAM crashes the game

### ISSUE THREAD

**Issue by getItemFromBlock** [Turing-Complete-Game/Suggestions-and-Issues#140]
### Discord Thread

https://discord.com/channels/828292123936948244/1268673179526889542/1268673179526889542

### What happened?

After patching my stack component from my custom architecture, the game crashed. I quickly realized that this was caused by the presence of a fast RAM inside the custom component.

To reproduce, just make a new custom component with an input and a fast RAM, then try to place it on any architecture
I tested this with the fast RAM and delay RAM, but I could not find the regular RAM in the menu, was it removed ?

### Version

0.1095 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1095 Beta on Windows
```

**Comment by Stuffe** [comment]
fixed next patch
