### ISSUE TITLE
[Bug]: ALPHA: memory probe chain

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#141]
### Discord Thread

https://discord.com/channels/828292123936948244/1268892478904340562

### What happened?

I found that :
 if you put a memory probe in a custom component 1, then you place this custom component 1 in a custom component 2 and you put a memory probe on 1 in 2.
 place component 2 in your architecture the memory prob will not work.
if you check the input and output of the component 2, everything works well inside except its probe(2) which will always remain at 0.

I can create the situation in a save if necessary. 

### Version

0.1095 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
