### ISSUE TITLE
[Bug]: Lag with nested costume components

### ISSUE THREAD

**Issue by Tarimaru** [Turing-Complete-Game/Suggestions-and-Issues#141]
### What happened?

I had a fair amount of nested components in Overture and the game started to lag quite severely (my guess is under 1fps). After I looked at task manager, I did see, that the game used almost all of my RAM (16GB).

### Version

Latest

### Operating System

Windows 64bit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Currently you should regularly restart the game, that should at least temporarily reduce the problem

**Comment by Stuffe** [comment]
this should be fixed now after the refactor
