### ISSUE TITLE
[Bug]: File Loader, crash after file selected

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#142]
### Discord Thread

https://discord.com/channels/828292123936948244/1268929791717806142

### What happened?

With a fresh unstall of the game and no save (game reset and save folder wiped) on Windows 10. 

1: Place a file loader component. 
2: Hit LOAD
3: Select a file
Game crashes

Game copies the selected file to the save folder and will load that file upon reloading the game and schematic. If you repeat steps 2 and 3 game will again crash with same results.

### Version

0.1095 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next version
