### ISSUE TITLE
[Bug]: ALPHA: RAM size must be power of 2 >= 512, and incorrect GUI behaviour

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#143]
### Discord Thread

https://discord.com/channels/828292123936948244/1269379757707890741

### What happened?

If you set the size (amount of memory, not bit width) to a non-power of two, it rounds up to the next power of two that is at least 512 (maybe intended?). Clicking the save button doubles the size of the ram (probably not intended).

### Version

0.1096

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
