### ISSUE TITLE
[Bug]:  Hot GPU temperatures

### ISSUE THREAD

**Issue by vertexshader256** [Turing-Complete-Game/Suggestions-and-Issues#143]
### What happened?

I was playing TC, I believe my GPU fan died and it killed the video card.  This very likely has nothing to do with the game but lets make sure.  Lets verify that a frame-limiter is in place to reduce GPU temperatures.   Or perhaps an option to set the max fps?

### Version

Latest

### Operating System

Win 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The game should be limited to 60 FPS if you didn't disable that in your system wide GPU settings I think.

**Comment by vertexshader256** [comment]
I can't verify, because I had to install a new graphics card, erasing my old settings.  I have a 144hz monitor so I may have done that.

**Comment by vertexshader256** [comment]
If we have verify that the framerate of the game never exceeds that of the monitor, lets close this.  That's all I wanted to verify.

**Comment by EnderShadow** [comment]
I've never seen it exceed the refresh rate of my monitor

**Comment by Stuffe** [comment]
Depending on what exactly caused this, this is either improved in the new refactor, will be improved when we switch to Godot 4, or is something specific to your set up that probably wont be fixed anytime soon
