### ISSUE TITLE
[Bug]: ALPHA Multiplexer level wrong output

### ISSUE THREAD

**Issue by Dajlif** [Turing-Complete-Game/Suggestions-and-Issues#144]
### Discord Thread

https://discord.com/channels/828292123936948244/1269652227132489789

### What happened?

On the Multiplexer level, i made a solution (screenshot), that should produce the right output and also visually shows the right output, but the game says that its wrong anyway.
restarted both game as well as PC and rebuild like its shown in the screenshot.
![Screenshot 2024-08-04 144221](https://github.com/user-attachments/assets/656a1299-fe55-4cd7-89dd-55150871b6db)

### Version

0.1096

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon RX 6800
OpenGL ES Batching: ON
 
Turing Complete 0.1096 Beta on Windows
```

**Comment by Stuffe** [comment]
fixed
