### ISSUE TITLE
[Bug]: ALPHA crash in level "the bus"

### ISSUE THREAD

**Issue by Dajlif** [Turing-Complete-Game/Suggestions-and-Issues#145]
### Discord Thread

https://discord.com/channels/828292123936948244/1269662371782066226

### What happened?

build the Bus level as seen in the screenshot, but as soon as i start the test it Crashes when i change the layout it stops crashing.
![Screenshot 2024-08-04 161529](https://github.com/user-attachments/assets/3e4ad431-95e5-4a54-a2c9-21edc23aeea8)

### Version

0.1096

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon RX 6800
OpenGL ES Batching: ON
 
Turing Complete 0.1096 Beta on Windows
```

**Comment by Stuffe** [comment]
fixed
