### ISSUE TITLE
[Bug]: ALPHA: Crash when connecting wire in this schematic

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#146]
### Discord Thread

https://discord.com/channels/828292123936948244/1269753515387912255

### What happened?

Connecting the marked wire crashes with error 
`Variable [34mv647[0m not in scope.
[31m(9430)[0m
            var v967 = (<U8> (<U8> [31mv647[0m))`
(Schematic sent in)

### Version

0.1099

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
