### ISSUE TITLE
[Bug]: 64 bit IO components don't remember their label when exiting and re-entering the component factory

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#146]
### What happened?

1. Go to the component factory
2. Place a 64 bit IO component and name it
3. Exit the component factory
4. Re-enter the component factory
5. The 64 bit IO has reverted to it's default name

### Version

Development

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Interestingly, this affects the label on the input/output component itself and the left bar, but not the actual Custom Component. The CC has the correct name in the bottom panel both inside the component factory and in architectures.

**Comment by Stuffe** [comment]
fixed next update
