### ISSUE TITLE
[Bug]: Tests and Instructions lost upon completing "Component Factory"

### ISSUE THREAD

**Issue by jistjoalal** [Turing-Complete-Game/Suggestions-and-Issues#147]
### What happened?

Awesome game! One small detail, possibly a bug. When I finished the "Component Factory" level, I lost the ability to run tests, access the "instructions" menu, and the similarly informative text below the input signals in the left sidebar for that level. In the process of being reclassified as a "user component", it would be nice if it kept the same tests and associated signal information that it had before. I went back to optimize the layout of my ALU and knocked a single wire out of place that took me a while to track down because I had to manually decode and test everything.

![https://i.gyazo.com/e17c28382a53e0b547ea9adbfe9f9e03.png](https://i.gyazo.com/e17c28382a53e0b547ea9adbfe9f9e03.png)

You can see the Instruction field reads `0` instead of `OR`, the instructions gear icon is missing, and clicking tick/run does nothing since there are no longer tests. Aren't tests supposed to help with regressions too? 😄 Feels a bit gnarly/pointless to abandon them after the initial spec is met.

Thanks again for the fun and very impressive game. [N2T](https://www.nand2tetris.org/) 2.0 with a funny alien, doesn't get much better than that.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Glad you are enjoying the game!

This is not a bug, but a limitation of the component factory.

One solution that is currently possible is to just go back and recomplete the level "Arithmetic Engine". You can also copy over your modified solution from the component factory to help with this via CTRL+C/V.

With regard to test cases in the component factory, there is #86 . You can add your usecase there as a motivation, and as an example of what the game could prefill to test and show how it works.

With regard to "signal labeling", that would indeed be a nice feature to have in the component factory, and there isn't a currently open feature request for that.
