### ISSUE TITLE
[Bug]: ALPHA: Crash when renaming a new component

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#148]
### Discord Thread

https://discord.com/channels/828292123936948244/1269939240557613066

### What happened?

To reproduce:
1.  Create a new custom component (without opening it)
2. (Try to) Rename the component (Error: Could not rename, 
`SCRIPT ERROR: Invalid get index '6695270506342005287' (on base: 'Dictionary').`
`          at: rename_schematic_or_dir (res://misc/schematics.gdc:110)`). 
3. Loading / Cloning / Renaming / Deleting that component will crash the game with 
`oserr.nim(95) raiseOSError`
`Error: unhandled exception: The system cannot find the file specified.`

Note: 
- Restarting or loading any other component after step 2 will update the name of the broken component and prevent the crash.
- Still present after a factory reset.
(0.1100 Beta, Windows 10, SSD)

### Version

0.1100

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
