### ISSUE TITLE
[Bug]: ALPHA: Bugs / Crash when deleting a component factory folder

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#149]
### Discord Thread

https://discord.com/channels/828292123936948244/1269972805542350920

### What happened?

Setup from a fresh save:
1. Inside the component factory, click 'switch schematic' and create a new folder.
2. Create a component inside the new folder and place something inside so that it can be placed
3. While the component is still opened, delete the folder the component is in through the 'switch schematic' file explorer (probably should not be possible as you can't delete the currently opened component).

(These are probably only side effects, the issue appears to be step 3.)
4. Exit and reenter the component factory to open the default component
5. If you place and open the component inside the default component, the game crashes

### Version

0.1100

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
fatal.nim(54)            sysFatal
Error: unhandled exception: custom_prototype_list.nim(30, 12) `custom_id != 0`  [AssertionDefect]
```

**Comment by Stuffe** [comment]
fixed next patch
