### ISSUE TITLE
[Bug]: ALPHA: Crash when deleting nested components

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#150]
### Discord Thread

https://discord.com/channels/828292123936948244/1269974403047755827

### What happened?

To reproduce:
1. Create two custom components A and B
2. Place something in B so it can be placed
3. Place an instance of B in A
4. Open the instance of B by selecting it in A and clicking the wrench
5. Delete A
6. Click the 'back' arrow on the top to return from B to A
7. Crash

### Version

0.1100

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
fatal.nim(54)            sysFatal
Error: unhandled exception: custom_prototype_list.nim(30, 12) `custom_id != 0`  [AssertionDefect]
```

**Comment by Stuffe** [comment]
fixed next patch
