### ISSUE TITLE
[Bug]: Selected items move when moving non-selected items

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#150]
### What happened?

1. Select some items
2. Move an item that isn't selected

Expected:
Only the un-selected items should move.

Actual:
Selected and non-selected items all move together.

Is regression:
Yes, it regressed several weeks ago when the controls were changed. Prior to the new control scheme, this used to work correctly.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Did *you* already report this #85  ?

**Comment by scottanderson** [comment]
#85
