### ISSUE TITLE
[Bug]: 8bit programs appear to accept 16-bit address, but only use 8 bits

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#151]
### What happened?

My microcode at address 372 contains a jump instruction, and 116 represents no-op. The +256 bit represents the jump condition flag.

When the flag is set, the debugger shows offset 372 is active, but outputs the byte from position 116.

Expected:
Either output the value at address 372, or display offset 116 as active.

Actual:
Displayed offset and value output disagree.

https://user-images.githubusercontent.com/662325/144283978-5173e8e2-5112-457e-86cb-955f280e3ef4.mp4

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I am pretty sure this no longer applies after the new refactor, but if it does feel free to reopen
