### ISSUE TITLE
[Bug]: ALPHA: Probe and Static value visual bug

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#151]
### Discord Thread

https://discord.com/channels/828292123936948244/1270335249888579677

### What happened?

If you place a probe or a static value component in two cells in a custom component, the preview will show them in both cells. When placing the component, they only show in one of the cells (as expected).

### Version

0.1101

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
