### ISSUE TITLE
[Bug]: ALPHA: Space-rotating ignores selected wires

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#153]
### Discord Thread

https://discord.com/channels/828292123936948244/1270452340343832627

### What happened?

Place one component and a wire, select both using shift-drag, and use the space bar to (try and) rotate them. The component does rotate, but the wire stays in place.

To be consistent with how it behaves when you select multiple components, you shouldn't be allowed to rotate in this scenario (or allow rotating multiple components at once, but that isn't necessary imo).

### Version

0.1101

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
