### ISSUE TITLE
[Bug]: Broken helper bot achievement

### ISSUE THREAD

**Issue by DEPREZR** [Turing-Complete-Game/Suggestions-and-Issues#154]
### What happened?

I just finished the game. I so completed all levels.
And I never got helper bot achievement.
I passed again and again levels involving bot, but it never unlocked this one.
Version 0.342 beta

(And not really the place, but because I finished the game and so this is my last report here : GG. Even if there is still some little bugs here and here, the game was already really enjoyable. Keep going man !)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
The helper bot achievement is not for the for the normal levels. Here's a hint though, manually control the robot in the robot levels.

**Comment by DEPREZR** [comment]
Oh ok got it funny. So nevermind this one can be closed :)
