### ISSUE TITLE
[Discussion/Request]: More powerful 64 bit memory

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#155]
### Request?

With the 64 bit memory having a 1 tick read delay, I think it needs some capabilities added to it to make it easier to use. For instance, there's no real way to make a cache without running into a ton of issues related to using it. There's other possible ways to address the issues relating to it, so feel free to discuss them here as well.

Here's what I propose
- Multiple data inputs and outputs added to the 64 bit memory as well as potentially forcing read alignment by ignoring the lower bits of the address
  - This is so that it acts more like real memory in that you read cache lines instead of individual addresses
- A cache component. This should be the 256 byte component, but subdivided based on how many outputs are added to the 64 bit memory.
  - This component should have 32 64 bit values (256 bytes) of storage and and cost the same as RAM
  - It should only use the lower 5 bits of the address for choosing a 64 bit word
  - It should have as many data inputs and outputs as the 64 bit memory component

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I like adding more output pins to the 64 bit program, but why not implemented the cache with registers?

**Comment by EnderShadow** [comment]
It can be done, but ram is cheaper than registers which is why I suggested it. It's not the biggest issue in the world though.

**Comment by Stuffe** [comment]
Since this has changed so much I am closing it. Please reopen (or open a new one) if you think some of it is still relevant
