### ISSUE TITLE
[Bug]: ALPHA: Invisible pasted elements after hitting Escape

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#155]
### Discord Thread

https://discord.com/channels/828292123936948244/1270466381560676493

### What happened?

1) Go to the paste mode wither by Ctrl-C + Ctrl-V or by Ctrl-X.
2) Press Escape. (I often do it by accident when I'm trying to cancel.)
3) Go back to the schematic.
4) Clicking now pastes the components instead creating a wire, despite no visual indication of the paste mode.

### Version

0.1101 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed
