### ISSUE TITLE
[Request]: 64 Bit Switch

### ISSUE THREAD

**Issue by atsjewell** [Turing-Complete-Game/Suggestions-and-Issues#156]
### Request?

I built my own as a custom component.. but man, I sure wish one came built in to avoid the nesting. Plus the custom component shapes don't look as clean.
Actually, I'd like 64 bit versions of all the gates for the same reasons, but definitely the switch most of all.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
It appears there has been a somewhat firm no on this kind of requests: #102

**Comment by Stuffe** [comment]
I originally had this idea that it would be an exiting challenge to have the only 64bit component given be a NAND (well except for the program and other miscellaneous components).

But in the meantime I have been convinced by the argument that it will make the optimal scores for 64 bit challenges require players to micro optimize each level using bit and byte components. Also it hard coded components can make simulation faster

**Comment by MarximusMaximus** [comment]
This appears to have been completed? Close bug as completed?

**Comment by MegaIng** [comment]
Yes, this is done
