### ISSUE TITLE
[Bug]: Field references in static eval components crash the game

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#156]
### Discord Thread

https://discord.com/channels/828292123936948244/1271218079841648731

### What happened?

The sharing of the expression evaluator between leads to %a syntax being supported, but crashing the game upon being used since no "field values" are being passed.

IMO it would be a good idea to pass the width as the first field value %a, instead, or maybe in addition to, the current width fixed replacement. That pattern would easier to extend if in the future a second static parameter gets added.

### Version

0.1104

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
ERROR: Unhandled Nim exception: C:\Users\MegaIng\PycharmProjects\Turing-Complete_new\dyn_lib\backend\simulation\build_thread.nim(164) start_simulation_thread
C:\Users\MegaIng\PycharmProjects\Turing-Complete_new\dyn_lib\backend\simulation\preorder.nim(122) preorder
C:\Users\MegaIng\PycharmProjects\Turing-Complete_new\dyn_lib\backend\isa_spec\expressions.nim(140) eval
C:\Users\MegaIng\PycharmProjects\Turing-Complete_new\dyn_lib\backend\isa_spec\expressions.nim(135) eval
C:\Users\MegaIng\.choosenim\toolchains\nim-1.6.12\lib\system\fatal.nim(54) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

**Comment by Stuffe** [comment]
fixed
