### ISSUE TITLE
[Bug]:  Ability to move red components when not allowed to do

### ISSUE THREAD

**Issue by XXXDENDACION** [Turing-Complete-Game/Suggestions-and-Issues#157]
### Discord Thread

[https://discord.com/channels/828292123936948244/1271497876232605840/1271497876232605840](https://discord.com/channels/828292123936948244/1271497876232605840/1271497876232605840)

### What happened?

1. Go to the LOGIC ENGINE level
2. Place any logic component
3. Choose multi-select tool and select area with red component and logic component
4. Start dragging this logical component
5. Red component is changed initial place

### Version

0.1059 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
sorry this repo is for tracking bugs in the new 'save_breaker' version of the game only
