### ISSUE TITLE
[Bug]: ALPHA: Static shift crashes when you input too big input width

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#159]
### Discord Thread

https://discord.com/channels/828292123936948244/1272090863656374283

### What happened?

1) Connect static shift to input and output components.
2) Set the shift to -5. (this step may not be necessary)
3) Set the output width to 10. (nothing bad happens)
4) Change the output width to 100. (crash)

### Version

0.1114 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch
