### ISSUE TITLE
'Divide' level needs greater test coverage.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#159]
### What happened?

Currently these tests are mostly randomize (perhaps entirely, aside from the first?)  This allows the top to bits of the quotient to be effectively ignored.

Recommended solution:  Add a couple of fixed tests with a large numerator and small denominator to cover the relatively low chance of that combination showing up by chance.  Preferably at least three tests:  n>=128, d=1.  n>=128, d=2.  64<=n<=127, d=1.  If possible, it would be ideal for the numerator to remain random (but limited to the necessary ranges) to prevent people from special casing out those specific tests.

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by foovax** [comment]
I posted a code sample in the discussions that will pass 16/16 tests...sometimes.

**Comment by Stuffe** [comment]
from 0.366 the level test are more rigorous, let me know if its still not enough

**Comment by altrag** [comment]
I still think this will need some tests with hardcoded denominators to catch those edge cases consistently.  The high bit on the output can only be tested if the high bit is set on the numerator and the denominator = 1, or (assuming uniformly random inputs across the entire 8-bit range) a one-in-510 chance of being hit per test.  At 32 tests per run, that's about a 6% chance on any particular submission for a cheese solution to fail on the high bit.

The second-highest should be better - ~26% if my math is right (which is probably isn't, but its a lowish chance regardless).  This can be triggered by the denominator between 1..3 and the numerator in the ranges [64..127,192..255], [128..255] and [64..85] respectively.

**Comment by bmerry** [comment]
Semi-related: it would be better if the first test case was more interesting, rather than having a quotient of 0. That would
(a) make debugging easier, since you don't have to step through to more interesting test cases to see where things go wrong
(b) make scoring more interesting (with the current mechanism of the first test case determining the score).

I suggest something like 226/11, where the inputs and outputs are all non-trivial.

**Comment by Stuffe** [comment]
I belive this was fixed

**Comment by altrag** [comment]
This does not appear to be fixed (0.651), at least not in any way that's noticeable from the client side.

Currently I can disable the top bit on my solution and pass nearly 100% of the time.  Top two is very close (OK I did the math before, I imagine its still accurate :D).  Top three disabled is still running ~50% and top 4 disabled is passing ~1/3 of the time - which would require an average of 9 attempts to get the server to accept it.

(Unless the server is doing a more strict test regime, in which case I suggest those tests also be moved to the client - nothing worse than having the server reject your solution when the client accepts it and having no idea why.  I mean if you're intentionally trying to cheese you might be able to guess, but its possible someone just misses a bit by accident.)
