### ISSUE TITLE
[Bug]: Alpha: Console blank

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#160]
### Discord Thread

https://discord.com/channels/828292123936948244/1272090999522332725

### What happened?

Console connected to a RAM filled with [0,1,2,..., 255] is blank.
Maybe related to ⁠bug #21

![image](https://github.com/user-attachments/assets/23a415ba-2f2d-4a3a-8ba4-4788c79d0bce)

### Version

0.1114 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
