### ISSUE TITLE
[Bug]: Alpha: Static evaluator width variable clamps to minimum of 2

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#161]
### Discord Thread

https://discord.com/channels/828292123936948244/1271970143466950758

### What happened?

i would like to be able to use any value with the static evaluator, but i don't know how much jank may be going on in the backend

### Version

0.1113 Beta maybe?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
