### ISSUE TITLE
[Bug]: Alpha: Linking custom component to static evaluator crashes the game

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#162]
### Discord Thread

https://discord.com/channels/828292123936948244/1271973312255365220

### What happened?

using the static const link on a custom component to a static evaluator causes a crash. should be easy to reproduce i hope

### Version

0.1114 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
