### ISSUE TITLE
[Bug]: Custom Components that are offcenter can crash the game.

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#162]
### What happened?

If you have a CC like this: 
![image](https://user-images.githubusercontent.com/26136419/144618278-4c905323-f72f-4cad-bf7d-bf1b47bc6109.png)

I.e. where the center of the component does not actually have area and all other area is to one side of it, then trying to place the component close to an edge of a schematic in such a way that the center would be outside the schematic crashes the game.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I can no longer place this kind of custom component in a way so that its center is outside of the map. Can you still reproduce this? If so please reopen the issue
