### ISSUE TITLE
[Bug]: 64 bit register has the wrong delay

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#163]
### What happened?

The 64 bit register has 8 times the NAND and delay of the 8 bit register. The delay should be the same as the 8 bit register since registers scale horizontally

### Version

Development

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next version
