### ISSUE TITLE
[Bug]: ALPHA: It's not possible to set max value for 64-bit input

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#164]
### Discord Thread

https://discord.com/channels/828292123936948244/1272145024884146351

### What happened?

It looks like the highest accepted value is 2^63−1.
(My guess is that the game uses a function that parses 64-bit numbers with sign.)
![Peek 2024-08-11 12-45](https://github.com/user-attachments/assets/2f000138-81a8-466b-9e53-06ee2bf3c055)

### Version

0.1117 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch
