### ISSUE TITLE
[Bug]: Register and Counter outputing a tick late

### ISSUE THREAD

**Issue by ComputerErika** [Turing-Complete-Game/Suggestions-and-Issues#165]
### Discord Thread

https://discord.com/channels/828292123936948244/1272355713481572353

### What happened?

Version 0.1117 beta
OS: Linux
Distro: Manjaro

When writing a value to the register, the output updates 2 ticks after, not 1 like its supposed to
This happens where or not the first tick is `-` or `0` and on after a factory reset

I constructed this build in the component factory:
![build](https://github.com/user-attachments/assets/0f8fe952-db72-4466-b670-70ec984f8798)

I then clicked the tick button 6 times, to make sure it wasn't the `-` state messing it up, the tick counter now read 5

Tick 5:
![tick_5](https://github.com/user-attachments/assets/86eef1f1-c1f9-4ab4-83af-53cab21ec335)

Tick 6:
![tick_6](https://github.com/user-attachments/assets/ea7c3c93-f68f-4652-9f92-1c6f25288893)

Tick 7:
![tick_7](https://github.com/user-attachments/assets/ccb5e758-6020-4fd1-bc64-c673db883021)

As you can see, on tick 6 after writing 72 to the register the tick before, the register now holds 72, but the output is still zero
Only a tick later, on tick 7, does the output update, 2 ticks after I was writing the input

This holds for changing the write value every tick, the output value is always 2 ticks after its input, the register display showing the value in between

Ive noticed the counter also outputs its number a tick late, unless the display is supposed to show the *next* number its going to output

### Version

0.1117 beta

### What OSes are you seeing the problem on?

Linux

**Comment by ComputerErika** [comment]
Also heres my save:
[Turing Complete.zip](https://github.com/user-attachments/files/16576641/Turing.Complete.zip)

**Comment by MegaIng** [comment]
I see you did not read the pinned post... You should not share your save folder publicly without editing out the token.

**Comment by ComputerErika** [comment]
just deleted that comment, as someone explained to me on discord
I did read the pinned post on discord, I assumed "PM me your save" meant just share it in regards to the bug report, I didn't read anywhere it saying it includes private info
Rereading it seems theres a line I missed, my bad

**Comment by Stuffe** [comment]
If you edit the input on tick 5, you aren't actually changing tick 5, you are just setting up what will happen on tick 6. So on tick 6 the value is stored in the register and on tick 7 it is output. Granted you changed the inputs on tick 5, I don't see any issue here. I need to format my Linux machine but I confirmed it works as it should on macos. Closing for now
