### ISSUE TITLE
[Bug]: ALPHA: Visual bug on Fast Ram component

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#166]
### Discord Thread

https://discord.com/channels/828292123936948244/1272492331504898189

### What happened?

Notice the Load, Save labels at the bottom, they are off from the position where they're supposed to be at.
Only appears on Fast Ram, other rams are fine.
Appears both in sandbox and in component factory

In case it's related to resolution, here's my system's display config:
Resolution: 2560*1440
OS: Windows 11 Professional 23H2 22631.3958
Display Scale: 125%
Directly launched from steam without any command line args.

![image](https://github.com/user-attachments/assets/af83d3be-c581-4366-a8e9-d7e8da249cff)

### Version

0.1117 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
Mutex: I think it's because (for some reason) the fast ram is shown one unit higher in the preview than the other ram components (place a normal RAM, then switch between them to see the difference). 
It also still has the bit width selector, which I don't think is required anymore and doesn't seem to do anything.

**Comment by Stuffe** [comment]
fixed next patch
