### ISSUE TITLE
'Signed Negator' level needs greater test coverage.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#166]
### What happened?

Another in the series!  Currently this level can be completed with a logic solver at ~half nand of the best known-legitimate design.

Suggested solution:  As always, full test coverage of all possible values would be the ideal, but in the short term my suggestion is to add test cases for 0, -1 and -128.  If including negatives in the test input is undesirable (I notice none of the current ones are negative), adding just 0 and 127 I believe would still provide sufficient coverage to make "cheated" solutions not worthwhile from a scoring perspective.

PS:  1 is tested twice in the current list.  Doesn't hurt anything but doesn't really help either.

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0x473354** [comment]
I submitted my save with examples for this to https://turingcomplete.game/report_bug earlier. The addition of 0, -1, -128 or 0, 127 to the test cases would stop those examples from working.

**Comment by EnderShadow** [comment]
There's also the fact that no negative numbers are tested as well. So these will fix the issue where 12/4 is a valid solution because you ignore the msb

**Comment by tali713** [comment]
Alternatively, if it is intentional that negative numbers are not tested the level should announce an enhanced version of the component, as it does with registers, ram, etc.

**Comment by altrag** [comment]
FakeNeo just showed me a design that allows for ignoring the high bit on any non-negative input, including zero.  So the 0/127 set isn't sufficient coverage - would have to include at least one negative test value to prevent that.

**Comment by Stuffe** [comment]
The dev branch now has 128 tests up from 16 and includes tests for negative numbers
