### ISSUE TITLE
[Bug]:  Assembler doesn't parse hex numbers correctly

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#17]
### Discord Thread

https://discord.com/channels/828292123936948244/1264170243496869960

### What happened?

An assembler file with only this content:
```
<U32>0xFF

```
crashes the game with 

```
Error: unhanded exception: invalid hex integer: 0x [ValueError]
```

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
this was fixed
