### ISSUE TITLE
[Bug]: RAM components cursor visually overflows

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#17]
### What happened?

While the RAM component outputs the correct values, e.g. at address %256, the visual cursor is not restricted and goes out of bounds when connected to a 64bit wire. (similar to a previous bug with the Program component)

![image](https://user-images.githubusercontent.com/26136419/140820602-b791d62b-defd-425b-b1cf-f4217f54b3a2.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed  0.290
