### ISSUE TITLE
[Bug]: changing visibility of a custom component while changing its name crashes the game

### ISSUE THREAD

**Issue by danielrab** [Turing-Complete-Game/Suggestions-and-Issues#170]
### What happened?

click the name edit button in the custom component selection menu, make any change to the name, click the checkmark to toggle visibility.
the game immediately crashes.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next patch
