### ISSUE TITLE
[Bug]: ALPHA: Crash with large SSD

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#170]
### Discord Thread

https://discord.com/channels/828292123936948244/1272846328157835345

### What happened?

Pressing Save on the SSD size when it's `33554432` crashes. `16777216` is fine.

I have more than enough space on the drive for a 32 MiB file.

### Version

0.1119 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
Crash output: ```
(name: "C:/Users/gelthor/AppData/Roaming/Godot/app_userdata/Turing Complete/schematics/architecture/J1-simspeed/16777216_3916190619374538059.tc_rom", handle: 1976, pointer: 2293151825920, size: 16777216, is_file: true)
oserr.nim(95)            raiseOSError
Error: unhandled exception: Access is denied.
Additional info: C:/Users/gelthor/AppData/Roaming/Godot/app_userdata/Turing Complete/schematics/architecture/J1-simspeed/16777216_3916190619374538059.tc_rom [OSError]
```

**Comment by Stuffe** [comment]
fixed next patch
