### ISSUE TITLE
[Bug]: ALPHA: Using the new static shift/static evaluator components on a custom component cause strange behaviors

### ISSUE THREAD

**Issue by getItemFromBlock** [Turing-Complete-Game/Suggestions-and-Issues#171]
### Discord Thread

https://discord.com/channels/828292123936948244/1272901536015585393/1272901536015585393

### What happened?

I tried remaking the bit indexer using the new static shift and static evaluator
everything seemed to work as excepted, but I soon realized that the output were wrong.
It seems that adding more than one component make them partially share their output ? I am not 100% sure of what is happening, but it looks like the outputs of all indexers are mixed together
All of the static evaluators have the following expression: "-width"

The discord thread contains the relevant pictures

### Version

0.1119 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
