### ISSUE TITLE
[Bug]: Alpha: Run Fast hotkey missing in tooltip

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#172]
### Discord Thread

https://discord.com/channels/828292123936948244/1273606591018438677

### What happened?

The Tool tip for the `Run Fast` button doesn't show the hotkey `F6`.
`F6` does indeed "run fast", just the info is missing from the tooltip.

### Version

0.1119 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed next patch
