### ISSUE TITLE
[Request]: Make the server validated the legimatcy of a schematic

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#172]
### Request?

Currently it is somewhat by design possible to "hack" or generate save files that have invalid wiring, specifically that the start and the end are the only entries of the path that are actually in the save file.

The game engine accepts this willing and just treats it as if those two points are connected by magic. This is good IMO and should stay that way, but only client side: Solutions that use these kind of broken wires shouldn't verify server side, since they allow you to compact circuits a lot more than normally possible. Especially levels like Little Box might be cheatable with that (since cable management is irrelevant, and you can use all the space you want to unpack one or two registers), or levels like Product of Nibbles, where it might be possible to put in an impossible low score LUT.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Note: It also needs to be checked that wires don't overlap with component parts, otherwise you could route wires through components.

**Comment by Stuffe** [comment]
Interesting, I never considered this. Although I think the easier fix might be to make the board of product of nibbles larger (assuming that you can't do any better in "Little box", where of course the board can't get smaller)
