### ISSUE TITLE
[Bug]: rotation corrupts copied circuit.

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#173]
### Discord Thread

https://discord.com/channels/828292123936948244/1273378625047232664

### What happened?

Steps to reproduce:
* Select a piece of circuit containing both components and wires
* Copy the circuit (ctrl+c)
* Paste the circuit to get it at your cursor (ctrl+v)
* Press space to rotate the copied circuit
* press right click somewhere to cancel the pasting action.
* Paste the circuit again (ctrl+v)
Now the components in the pasted circuit still remember that they were rotated, but the wires don't, resulting in a broken circuit.

### Version

0.1119 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
