### ISSUE TITLE
[Bug]: ALPHA: Saving to latency RAM causes a crash

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#174]
### Discord Thread

https://discord.com/channels/828292123936948244/1273758034006507520

### What happened?

Saving anything to the latency RAM causes the game to crash
To reproduce, just place a Latency RAM, enable the save pin and step one tick.

The crash might be related to bug #116

### Version

0.1119 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
seems to be fixed
