### ISSUE TITLE
[Request]: Store multiple component scores and allow them to be used in levels

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#174]
### Request?

In many cases you can trade between NAND and delay to get a lower total score, but sometimes you want to use a version of a component which has a higher score but is better for NAND or delay. I suggest storing 3 different best scores for each component: lowest NAND, lowest delay, and lowest score. We should be able to choose which of these we use.

Normally this isn't too big of an issue since we can just use custom components, but sometimes you can't. A good example of this is the 1BM component. There's a 6 NAND 6 delay version which has the lowest score and delay, but there's also a 5 NAND 8 delay version which paradoxically gives you a better scored counter than the 6 NAND 6 delay 1BM does. (62/12 vs 70/10).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I have some changes in mind that would make this no longer an issue for the 1 bit memory component. If that was fixed, would manually building / custom components solve this issue?

**Comment by EnderShadow** [comment]
As long as there's no way for the optimal memory components to create non-optimal circuits, yes.

**Comment by Stuffe** [comment]
I am closing this now, it will be fixed soon
