### ISSUE TITLE
[Bug]: ALPHA: Inconsistent input counting

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#176]
### Discord Thread

https://discord.com/channels/828292123936948244/1274012094378934315

### What happened?

At the beginning levels there are different systems for counting inputs (input 0 is also marked as input 1 etc.). This is quite confusing.

e.g Second Tick

![image](https://github.com/user-attachments/assets/586c35c6-40ea-4c1e-9cdc-2abf6f1ed262)

### Version

0.1119 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
