### ISSUE TITLE
[Bug]: Test missing on Unsigned less

### ISSUE THREAD

**Issue by t0x1-jm** [Turing-Complete-Game/Suggestions-and-Issues#176]
### What happened?

I asked in Discord, and they told me to submit it, although I'm sure you can't do all test scenarios :

I forgot a component "floor" on my build and it passed the test. The following test is missing : 
Input 1 : 0 (anything <= 4 really)
Input 2 : 4
Output should be ON
(You can then OR the upper part with anything)

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I believe this was fixed. If not and you still have a "cheesy" solution, please upload it here: https://turingcomplete.game/report_bug

It is a lot faster for me to understand if I just have an example of a circuit that shouldn't work.
