### ISSUE TITLE
[Bug]: The "Working Computer" stage has poor counter-detection logic.

### ISSUE THREAD

**Issue by OrangeOliviero** [Turing-Complete-Game/Suggestions-and-Issues#177]
### What happened?

I'm working on the final stage for a working computer (integrating COND). I have done this by using a MUX to select between R0 and the existing counter byte. The game refuses to advance, saying that I do not have a counter - but I do!

Here, you can see the basic setup. The byte that comes in from the right is coming from R0.
![image](https://user-images.githubusercontent.com/42069201/145481028-e1493572-1805-41c6-a9a0-da754a345d4e.png)

Here's the very first step. Note that the counter is appropriately incremented to 1, but the game is complaining that I have no counter component!

![image](https://user-images.githubusercontent.com/42069201/145481227-312db8da-86f2-45d3-a19b-ea8e4ab2dd18.png)

Note that in the preceding iterations where the MUX component didn't appear in the counter loop, the game had no issues with this setup.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OrangeOliviero** [comment]
I've actually removed the MUX from the loop and restored the counter to its original state, but I still get this error!

**Comment by MegaIng** [comment]
Just for this level you have to add a Counter Component from the Bytes section.

**Comment by OrangeOliviero** [comment]
... but why, when we're building upon a previous implementation that had us build a counter?

That wasn't at all clear to me.

I don't seem to have a counter component?

![image](https://user-images.githubusercontent.com/42069201/145481848-0a7372c8-7c15-443c-bd4f-c82829e9d09c.png)

**Comment by MegaIng** [comment]
Yes you do, right most in the BYTES section.

**Comment by OrangeOliviero** [comment]
You beat me to my edit - I found it, thanks!

**Comment by OrangeOliviero** [comment]
Since this wasn't made clear at all anywhere in the instructions that I can find, I imagine the "bug" that is left is that lack of clarity.

Since this builds upon previous iterations, perhaps it'd be worthwhile to create the counter as a separate component (the same way we created all the other components, custom or otherwise), and then require that we use that counter from the get-go, rather than needing to replace it in the final step? That would eliminate the confusion around the counter in this level.

Either way, I'm unblocked now, so I'll leave this to you to close or use to make improvements in this area.

**Comment by MegaIng** [comment]
The actual bug is that the level `PROGRAM` doesn't require you to add a Counter.

**Comment by OrangeOliviero** [comment]
Oh, was the component there all along? Oops!

**Comment by MegaIng** [comment]
Yes, it was unlocked after the `Counter` level, like all other components.

**Comment by OrangeOliviero** [comment]
My bad, I must have unlocked it right before bed the first night and forgot about it.
