### ISSUE TITLE
[Bug]: ALPHA: Game crash loading Add 5 (then the game itself)

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#177]
### Discord Thread

https://discord.com/channels/828292123936948244/1274101862399873035

### What happened?

```
PORT 5002
REQUEST: 1 sim_do
command: mode_reset -1
RESPONDING sim_do 1
REQUEST: 3 compile_and_run
HERE C:/Users/altrag/AppData/Roaming/Godot/app_userdata/Turing Complete/schematics/architecture/OVERTURE/256_5823907971488135226.tc_rom

This statement should be indented with 4 spaces, not 2.
(771)
  return random(250)
}
```
I've tried deleting that file and it just recreates it while crashing again (tried turning off Steam cloud as well so it's not pulling it down from there behind my back).  Deleting the entire Overture architecture directory fixed it (though my further playing around managed to break it entirely... I think it was when I deleted the Sandbox level it had been trying to load into Add 5...)

I can fix it by hacking the test.si for the level and adjusting the spacing.

Unfortunately I now get a new error:
```
PORT 5002
REQUEST: 1 sim_do
command: mode_reset -1
RESPONDING sim_do 1
REQUEST: 3 compile_and_run
HERE C:/Users/altrag/AppData/Roaming/Godot/app_userdata/Turing Complete/schematics/architecture/asdf/256_3045714946806088093.tc_rom
RESPONDING compile_and_run 3
REQUEST: 4 sim_do
command: refresh -1
RESPONDING sim_do 4
REQUEST: 5 compile_and_run

Variable .inputs not in scope.
(5886)
                    let result = arch_check_output(.trial, .inputs[0], arch_output)
```

This one appears to be in the backend.dll so I probably won't be able to hack a fix on my own this time.  I believe this started when I tried manually copying Overture to Add 5 and then added the Output level IO component before the input component.  I've deleted that schematic so I'm not sure why it's still doing this but I'll keep digging.

### Version

0.1120 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
