### ISSUE TITLE
[Bug]: Storage Cracker level has inverted the syntax for 'const'

### ISSUE THREAD

**Issue by OrangeOliviero** [Turing-Complete-Game/Suggestions-and-Issues#178]
### What happened?

The "Storage Cracker" level pre-fills your IDE, but it has an error on line 4 - presumably at some point the order of name + value were inverted, and the pre-fill was never updated:

![image](https://user-images.githubusercontent.com/42069201/145489013-193fdccc-ad7d-4ac5-9133-aac8e75ec686.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed
