### ISSUE TITLE
[Bug]: ALPHA visual of the short circuit

### ISSUE THREAD

**Issue by jojo5144** [Turing-Complete-Game/Suggestions-and-Issues#178]
### Discord Thread

https://discord.com/channels/828292123936948244/1274311144676393022

### What happened?

it's only the color of the short circuit that remains even though the short circuit is gone.
![Animation](https://github.com/user-attachments/assets/c4a8d6e7-5dff-469d-b4d9-9e8b11b022a8)

### Version

0.1120

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I am almost sure this was fixed. Otherwise I am going to need a save
