### ISSUE TITLE
[Bug]: Components attached to the mouse are not scaled corretly accoding to the zoom level

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#18]
### What happened?

When selecting a component from the menu, or getting one to hover via CTRL+V, then zooming in out correctly scales the circuit itself, but not the attached component.

![image](https://user-images.githubusercontent.com/26136419/140820970-a073ff96-4937-48e3-9085-4c7041f9a306.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next version
