### ISSUE TITLE
[Bug]: "The Maze" level mis-marks a wall as "nothing"

### ISSUE THREAD

**Issue by OrangeOliviero** [Turing-Complete-Game/Suggestions-and-Issues#180]
### What happened?

When navigating the maze, the robot sees a particular wall (only this one, that I've seen) as not there:

![image](https://user-images.githubusercontent.com/42069201/145508455-0e3c59b8-9c94-4a36-b04b-e4752fbead2f.png)

And indeed, when told to go forward, it moves on top of the wall:

![image](https://user-images.githubusercontent.com/42069201/145508525-070d6705-7c06-43c3-ae86-7e0498f96b2b.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
