### ISSUE TITLE
[Bug]: ALPHA: You can't enter values -1 to -9 into the Static Shift component

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#180]
### Discord Thread

https://discord.com/channels/828292123936948244/1275201834839179416

### What happened?

When you try to enter a value in range of -1 to -9 into the Static Shift component it just resets to zero

### Version

0.1123 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
