### ISSUE TITLE
[Bug]: Deleting a component from the schematic factory doesn't remove it from the menu

### ISSUE THREAD

**Issue by OrangeOliviero** [Turing-Complete-Game/Suggestions-and-Issues#181]
### What happened?

I re-visited my solution for COND to get the achievement. I did this by creating a new schematic.

I completed this twice with the same schematic, and it added COND 2 and COND 3 to the list of custom components (this seems a bug - it shouldn't re-add the same schematic just because I ran it a second time).

I deleted COND and COND 3 and renamed COND 2 to COND:

![image](https://user-images.githubusercontent.com/42069201/145509898-92df9462-19fe-46d0-9318-82a1a90d446b.png)

however, I'm seeing a blank COND 2 show up in the menu:

![image](https://user-images.githubusercontent.com/42069201/145509959-f7bd3b19-191f-4245-b5d5-4001ca4e9683.png)

![image](https://user-images.githubusercontent.com/42069201/145509981-57ad79a5-c5ca-4e34-bf8d-7a4a7674ce93.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next update
