### ISSUE TITLE
[Bug]: ALPHA: Crash when pasting a component on a labeled wire

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#182]
### Discord Thread

https://discord.com/channels/828292123936948244/1275321323362451486

### What happened?

Ran into this relatively obscure bug.  Placing a new component (from the menu) doesn't seem to cause the crash, nor does dragging an existing component - it's only when pasting that it crashes.

### Version

0.1123 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
