### ISSUE TITLE
[Bug]: crash on changing the level of custom components

### ISSUE THREAD

**Issue by sunnyssk** [Turing-Complete-Game/Suggestions-and-Issues#182]
### What happened?

The game occasionally crashes upon selecting a new level of a custom component in the factory.

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Could this be related to https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/170 , E.g. does it crash while editing the name at the same time?

**Comment by sunnyssk** [comment]
Hadn't looked into the list of issues. It is a duplicate of #170 .

**Comment by Stuffe** [comment]
This is now fixed
