### ISSUE TITLE
[Bug]: Alpha: Failing to match later rule, reports syntax error

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#183]
### Discord Thread

https://discord.com/channels/828292123936948244/1275519178027303023

### What happened?

A later, longer isa.spec rule is not being matched, instead the assembler complains that it doesn't match a previous rule.
```
start:
mov 1,r0
mov start,r0
mov 1,2,ram ; This line generate the error: Line 4: Was expecting a label here
```
Relevant part of ISA.SPEC:
```
mov %a(immediate), %b(register)
bbbbbbbb 00000000 aaaaaaaa 11000000
Testing


mov %a(label), %b(register)
bbbbbbbb 00000000 aaaaaaaa 11000000
Testing


mov %a(immediate), %b(immediate), %c(memoryDevice)
cccccccc bbbbbbbb aaaaaaaa 11000000
Testing
```
I'd expect the 3 argument instruction to match line 4, instead the assembler seems to greedily match the second rule, and then reports that it expects a label. If it fails to parse this line like this then it should fall through to the next rule.

Reordering the rules in isa.spec is a workaround in this case.

### Version

0.1124 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think this was fixed?

**Comment by MegaIng** [comment]
I believe so as well
