### ISSUE TITLE
[Bug]: Description of 64-bit I/O connectors missing

### ISSUE THREAD

**Issue by sunnyssk** [Turing-Complete-Game/Suggestions-and-Issues#183]
### What happened?

The descriptions of 64-bit I/O connectors would disappear after leaving and entering the component factory again. This is not reflected immediately in the thumbnail of the custom component, but is reflected when these connectors are selected. Changing their positions could also reflect this loss of information in the thumbnail.

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Duplicate of #146
