### ISSUE TITLE
[Bug]: [ALPHA]Debug point in assembler editor

### ISSUE THREAD

**Issue by jojo5144** [Turing-Complete-Game/Suggestions-and-Issues#184]
### Discord Thread

https://discord.com/channels/828292123936948244/1275586684574236682

### What happened?

in assembler editor set a debug point , close the editor .
When you reopen the editor, the point is no longer visible, but if you run the code it will stop at this invisible point.

- there are also problems if a debug point is present and lines are added or removed. 
- I had some where the comment lines shifted the highlighter. => but I need to make this one more consistent. 
### Version

0.1124 ALPHA

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed next patch
