### ISSUE TITLE
[Bug]: Stack bug

### ISSUE THREAD

**Issue by ValiAkros** [Turing-Complete-Game/Suggestions-and-Issues#185]
### What happened?

Bug occurs on PUSH AND POP, where the stack seems to be loaded from previous level (STACK). First success at STACK was due to no multiple pops where when pop would occur byte would not erase from RAM. 

E.g. 
```
PUSH   PUSH   PUSH  POP   POP   PUSH


                         *3       3       3        3
              *2         2       *2       2        *4
  *1           1         1       1       *1         1
```

This then occurs as an error in the next level when multiple pops occur. I went back to STACK to fix the problem, however this does not update STACK besides the NAND and delay score.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can you be more specific what the problem is?

**Comment by ValiAkros** [comment]
Apologizes, the issue is along the line of how the STACK works. From what its seems, it seem that in the PUSH and POP level, whenever a value is popped from the STACK, the value remains in the STACK and persists until it is either overwritten (by PUSH) or one of the tests is completed. Overall the location of where the STACK PUSHes and POPs is correct, however these persistent POP values in the module cause the overall STACK to be incorrect.

I am not certain if this is due to a faulty STACK module I created in the previous level, "STACK," or the STACK module given for PUSH and POP is bugged. I need more information as to whether the STACK module is based on your first corrected STACK design or the STACK module is a default module where the user cannot alter it.

I've attached some images to help. First group is an example of PUSHing on 94 and POPing it off where the value persists:

![POP 94](https://user-images.githubusercontent.com/95949755/145690452-51951f58-0009-45d7-a770-d1580025b09a.png)
![PUSH 94](https://user-images.githubusercontent.com/95949755/145690453-87b69eb2-d5c2-42b1-894a-6034c84d920e.png)

In this group, this is the error generated from multiple pops (where first pop was 187) and then a push (38):

![Multi POPs then PUSH Error](https://user-images.githubusercontent.com/95949755/145690448-31965f1c-1fa0-4354-a745-5ffc96565a9a.png)
![Multi POPs](https://user-images.githubusercontent.com/95949755/145690451-6f341524-7423-43f4-8dfc-c23bed753a24.png)

**Comment by MegaIng** [comment]
Sure, those values stay. That is the normal behavior for a Stack, there is nothing really you can or should do about it. It's essentially just visual: Those values are never accessible.

**Comment by ValiAkros** [comment]
Ok that's good to know. Now the error I get doesn't make much sense then. 

Here it says that I should've popped 18 off but the instructions say to push 18 onto the STACK. The values through the circuit suggest it should be a push as well.

![POP rather than PUSH](https://user-images.githubusercontent.com/95949755/145691892-be1db984-0302-4b8a-9ce4-082259331f1d.png)

**Comment by MegaIng** [comment]
The error messages for the level Push And Pop are somewhat unclear: This probably means that in a previous Step you wrongly Pushed/Poped/Read form input/wrote to output. Currently the error messages displayed don't necessarily apply to the same tick.

**Comment by MegaIng** [comment]
It's related, or even a duplicate of #131. (there might not have been an update since then)

**Comment by Stuffe** [comment]
fixed
