### ISSUE TITLE
[Bug]: Connecting RAM-like to switch crashes the game

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#186]
### Discord Thread

https://discord.com/channels/828292123936948244/1276150532758568990

### What happened?

Drawing the connection between the RAM out and the switch out crashes the game

![grafik](https://github.com/user-attachments/assets/dc4d03aa-d841-4719-8891-793d0844f542)

### Version

0.1124

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Output of simulator.exe:

Variable or_field_259 not in scope.
(941)
                or_field_259 |= <U8>  (<U8> ((<U8> 0)))
```

**Comment by Stuffe** [comment]
Fixed
