### ISSUE TITLE
[Bug]: Deleting everything in a level while it completes produces a 0 NAND local score

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#186]
### What happened?

If you wait on a level till just after the last test ran through and the delete everything (or only some stuff), the game will give you the "Onwards" popup (or whatever popup is appropriate probably), but claim that you finished the level with a score of 0/0/1 (or similar). These scores don't verify on the server (I think, at least they aren't 0/0 there):

https://user-images.githubusercontent.com/26136419/145686901-f787761d-7912-4850-810a-74bdfb7431ed.mp4

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NariKiro** [comment]
In addition to the above, pressing level map just after the last test but before the level complete prompt appears causes the prompt to appear on the level map itself. In addition, none of the usual unlocks for that level appear in the prompt.
https://user-images.githubusercontent.com/5409394/145688700-1077dc6f-4615-4715-93f1-25cb9dd0d5c2.mp4

**Comment by Stuffe** [comment]
That whole system has been rewritten so this very likely doesn't happen any longer
