### ISSUE TITLE
[Request]: Ternary Logic

### ISSUE THREAD

**Issue by Quadruplay** [Turing-Complete-Game/Suggestions-and-Issues#187]
### Request?

After completing the game, it would be cool if you could replay through all the levels, but with ternary(0,1,2) logic instead of binary(0,1).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This would be essentially a completely different game requiring a completely different engine, components and partially interface. While you can ask, don't get your hopes up.
