### ISSUE TITLE
[Bug]: ALPHA short circuit on several components are not marked

### ISSUE THREAD

**Issue by jojo5144** [Turing-Complete-Game/Suggestions-and-Issues#188]
### Discord Thread

https://discord.com/channels/828292123936948244/1276330363899215903

### What happened?

i have short circuit on several components , and the behavior is not the same as a single short circuit

![Animation](https://github.com/user-attachments/assets/a4907d1e-accd-4526-90b4-29f890d2f492)

### Version

0.1124 ALPHA

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed!
