### ISSUE TITLE
[Bug]: my Registers Level looks weird 

### ISSUE THREAD

**Issue by snackycracky** [Turing-Complete-Game/Suggestions-and-Issues#189]
### What happened?

I can't compelte the registers level, since it looks really weired. There is some other input missing. The Black screen on top does not have any function, I can't click on it. I have version 0.342 Beta

![Screenshot 2021-12-12 at 23 22 43](https://user-images.githubusercontent.com/144498/145731914-67dfdc0d-dd35-4120-9bef-475b75eb6390.png)

### Version

Latest

### Operating System

mac

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can you try to create a new schematic via the menu in the top right? Otherwise need to upload your save folder to https://turingcomplete.game/report_bug , or start a completely new save. You can also try deleting just `progress.dat` and the files under `schematic/architecture`
