### ISSUE TITLE
[Bug]: ALPHA: Game hangs when entering sandbox

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#189]
### Discord Thread

https://discord.com/channels/828292123936948244/1276506477032374354

### What happened?

ASM said ''Multiple instruction matched with conflicting syntax" on a line with a label. Trying to delete the label hangs the game. Restarting and clicking "Sandbox" hangs the game again.

This wasn't present in 0.1124, it was introduced in 0.1125.

### Version

0.1125

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
