### ISSUE TITLE
[Bug]: Halt and Waveform don't work inside custom component

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#19]
### What happened?

As stated in the title, some IO components, specifically Halt and Waveform generator don't work when placed inside of Custom components.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Halt does and the waveform one was removed

**Comment by roflcopter4** [comment]
*Ahem*. No, halt does not work inside of a custom component. It _will_ halt the simulation, but it will not display the custom message.
