### ISSUE TITLE
[Bug]: ALPHA: Crash when referencing a non-existing label

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#190]
### Discord Thread

https://discord.com/channels/828292123936948244/1276566297869811815

### What happened?

If you create an instruction in the specs (e.g. `call %a(label)`), then use the instruction with a non-existing label (e.g. `call l`), the game crashes.

### Version

0.1126 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Turing Complete 0.1126 Beta on Windows
tables.nim(234)          raiseKeyError
Error: unhandled exception: key not found: l [KeyError]
```

**Comment by Stuffe** [comment]
I believe this was fixed
