### ISSUE TITLE
[Request]: Keyboard UI module indicate key release

### ISSUE THREAD

**Issue by JayFromProgramming** [Turing-Complete-Game/Suggestions-and-Issues#191]
### Request?

As of the current version the UI element that allows you to use the keyboard does not indicate if a key is released (Unless I am doing something wrong). A better implementation would be to have the keyboard value return to ascii null(0) after the enable pin is cycled (Low-High-Low) so that keystrokes can be read without holding the key down for relatively slow machines 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
You can now check if the key is still held down using an extra pin. Once the value has been read the keyboard component is reset to 0
