### ISSUE TITLE
[Request]: When in 100hz mode allow the Character LCD to update display

### ISSUE THREAD

**Issue by JayFromProgramming** [Turing-Complete-Game/Suggestions-and-Issues#192]
### Request?

One of the things 100hz mode does is the game stops updating the numbers over elements which allows for faster simulation, which is very convenient but when writing programs for the LCD screen when in 100hz mode the display does not update until the simulation is paused or slowed down. It would be a great QOL upgrade to allow the LCD screen to update in 100hz mode so that interfacing with the machine isn't painfully slow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
coming up shortly with the new screens being added
