### ISSUE TITLE
[Bug]: ALPHA: Crash when entering sandbox. (Windows)

### ISSUE THREAD

**Issue by hnagd1** [Turing-Complete-Game/Suggestions-and-Issues#192]
### Discord Thread

https://discord.com/channels/828292123936948244/1276672256835059712

### What happened?

I was just in the TC sandbox testing out instructions when it randomly crashed. Now whenever I enter the sandbox it crashes. I don't know what I did to cause this at all.

### Version

0.1125 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Could you PM your save for this? It is impossible to fix without. It is probably already fixed though

**Comment by hnagd1** [comment]
Sorry. Forgot to close it after it was fixed.
