### ISSUE TITLE
[Bug]: Reliable Crash while UNDO

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#193]
### What happened?

When you draw a wire that gets cut off because of a component, undoing this wire create crashes the game reliably

https://user-images.githubusercontent.com/26136419/146168131-820cdeca-c915-4959-bb37-f72aadca0a90.mp4

At the end of the video I just pressed CTRL+Z

(this might be the reason for the still remaining reports of crashes during UNDO)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Good catch. Fixed next patch
