### ISSUE TITLE
[Bug]: Crash running Instruction Decoder level circuit

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#193]
### Discord Thread

https://discord.com/channels/828292123936948244/1276673158627201138

### What happened?

This circuit crashes consistently when I try to run the test. I've uploaded a mac crash report to the "report_bug" page as well.

![image](https://github.com/user-attachments/assets/e6dce954-dc3e-4a58-83ce-dfc6b0195a1a)

### Version

0.1125 Beta ??

### What OSes are you seeing the problem on?

MacOS

**Comment by Stuffe** [comment]
fixed next patch
