### ISSUE TITLE
[Bug]: OldNot and NOT can be placed in NOT Gate level

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#194]
### Discord Thread

https://discord.com/channels/828292123936948244/1276848469914685451

### What happened?

Both the imported `OldNot` and the new `NOT` gate can be placed in the the `NOT Gate` level.
Using either one passes the level.
I placed the NOT gate by copy pasting.
You should not be able to place either in the level where you build it.

![image](https://github.com/user-attachments/assets/daedebbf-5bfe-4f10-a663-2c5711626ca6)

### Version

0.1127 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
