### ISSUE TITLE
[Bug]: problem with level wire spaghetti

### ISSUE THREAD

**Issue by brent1776** [Turing-Complete-Game/Suggestions-and-Issues#195]
### What happened?

A bug happened!

In the documentation it says that this level only has zero for opcode and the code should 'ADD' argument 1 and 2.  The first 4 bytes of the program are 0 7 7 0, which seems to be me should add the input to the input and store result in reg 0.

My design does this but it is not accepted by the program.  It says that the opcode should be 'if_greater_or_equal'  and arg1 is reg 0, and arg 2 is 4, and result is reg 4.    I don't know where any of that comes from.

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Try restarting the game. This level sadly has a tendency to have these kinds of bugs.

**Comment by brent1776** [comment]
this issue can be closed.. it was my issue with not setting the increment correctly.
