### ISSUE TITLE
[Bug]: Tables in various level logs (e.g. Conditions) are misaligned

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#195]
### Discord Thread

https://discord.com/channels/828292123936948244/1277235271519178863

### What happened?

The table with condition codes for the level `Conditions` is misaligned. I'd expect the top twos rows of :OFF: and :ON: s to be directly above the other rows.

![image](https://github.com/user-attachments/assets/c341e34d-42d3-4694-9c06-17ba2c80a9fd)

### Version

0.1128 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
