### ISSUE TITLE
[Bug]: 'Equality' level needs greater test coverage.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#196]
### What happened?

It appears the 1 and 4 bits are still not being adequately tested with the extended test coverage, allowing a 13/6 solution (legit should be 17/6 with the currently-best design).

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next patch
