### ISSUE TITLE
[Bug]: Conditions expectation unclear

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#196]
### Discord Thread

https://discord.com/channels/828292123936948244/1277246789124362251

### What happened?

The sidebar on `Conditions` suggests that the expected output is four 8-bit numbers.
This has already caused some confusion, see the circuit from https://discord.com/channels/828292123936948244/1276673158627201138 and https://discord.com/channels/828292123936948244/897062022099918871/1276894587998441564

Instead the sidebar should show single bit values and be labelled `IMMED`, `CALC`, `COPY`, `COND`  rather than `N Output`

![image](https://github.com/user-attachments/assets/a8ac1c0a-888b-441e-a949-ad6ae1ee1ba9)
![image](https://github.com/user-attachments/assets/b17b6b9b-60d3-468e-9609-1fde7a1dd962)

### Version

0.1128 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed next patch
