### ISSUE TITLE
[Bug]: ALPHA: Old image of delay line in level log

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#197]
### Discord Thread

https://discord.com/channels/828292123936948244/1277250064334721025

### What happened?

The level 'Delay lines' uses an image of the old delay line.

### Version

0.1128

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
