### ISSUE TITLE
[Bug]: ALPHA: Conditions in 'Instructions' tab in 'Turing complete' incorrect

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#198]
### Discord Thread

https://discord.com/channels/828292123936948244/1277254374808223816

### What happened?

See https://discord.com/channels/828292123936948244/899582781271736361/1277159923293098057.
The shown conditional encoding in 'Turing complete' does not match the implemented operations in 'Conditionals'.

### Version

0.1128

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This was fixed
