### ISSUE TITLE
[Bug]: Counter level needs greater test coverage

### ISSUE THREAD

**Issue by bmerry** [Turing-Complete-Game/Suggestions-and-Issues#198]
### What happened?

I managed to submit a 60/12 solution for Counter by just deleting circuits for dealing with carries that affect the top 3 bits, saving 3 nand gates.

Per bit, there are 4 inputs of interest:
- the previous value of the bit
- whether there will be a carry from the lower bits when incrementing them
- the action
- the reset value

Ideally the test cases would cover all 16 combinations.

### Version

Latest

### Operating System

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Can you please upload you save with this schematic here:
https://turingcomplete.game/report_bug

That will make it very easy for me to fix

**Comment by bmerry** [comment]
@Stuffe I sent you my save games a little while ago but since then the memory has all changed. Let me know if you need new save games.

One particular case where it's debatable whether it should be tested is rollover from 255 back to 0. My 32/6 on the leaderboard will not work for that case (33/6 is doable while handling that rollover).

**Comment by Stuffe** [comment]
@bmerry I think this was fixed? If not please reopen this and submit an example.
