### ISSUE TITLE
[Bug]: Crashes while running ticks in 'CALIBRATING LASER CANNONS'

### ISSUE THREAD

**Issue by k3itak** [Turing-Complete-Game/Suggestions-and-Issues#199]
### What happened?

Cannot get past the level 'CALIBRATING LASER CANNONS'.
The game crashes every time on Test 4/4. It doesn't matter when I click 'Run ticks' or 'Next tick'.
It always happens on the last tick.
I love this game so much, and it's very unfortunate that I'm stuck here.

### Version

Latest

### Operating System

Windows 10 Education

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Upload your save to https://turingcomplete.game/report_bug

**Comment by MegaIng** [comment]
Actually, no need to upload. Seems to be a general problem.

**Comment by Stuffe** [comment]
I think this was fixed

**Comment by k3itak** [comment]
It works! Thank you so much!
