### ISSUE TITLE
[Feedback]: Default tick rate is unreasonable

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#20]
### Discord Thread

https://discord.com/channels/828292123936948244/1264157844190662657

### What happened?

For levels like `Adding Bytes` and `Byte OR`, the default tick rate of 100Hz is unreasoanbly slow, it would take more than 10mins to complete the tests.

A few things should be changed here:
- Somehow the default tick rate should be synced across component levels, but not into architecture levels
- The player should be told about and shown the ability to change the rate, in either of these two levels

Also see https://discord.com/channels/828292123936948244/1264163170285785098

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
