### ISSUE TITLE
[Bug]: In the preview, pin labels disappear

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#20]
### What happened?

After moving an IO pin to a new box in the component factory, the label in the preview doesn't appear at the new location. Reloading the schematic or editing the facing direction of the label fixes that.

It appears as if the cache for which box has which label inside of it doesn't get updated when moving an IO pin.

![image](https://user-images.githubusercontent.com/26136419/140821992-daf8f662-d2d6-405a-9ddd-592d3b08b265.png)

![image](https://user-images.githubusercontent.com/26136419/140822024-00ad29d9-395f-4fed-a583-af8bd1ce501f.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think this has been fixed
