### ISSUE TITLE
[Request]: A button to reset level score within the UI

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#201]
### Request?

Right now if your score gets out of sync (for example if you previously had a cheated solution and you want to create a 'correct' one), the only way to update your score is to go into the file system and mess around with @Best or progress.dat.

I think it would be useful to be able to do this from within the UI.  Suggested location would be in the "score sync" screen - have a little button for each level that lets you reset its score (locally at least.. probably doesn't need to be pushed to the server since that always updates when a new working solution is pushed, regardless of whether it scores better or worse so it should be able to just retain the existing solution until the user finishes their new one).

An alternative location would be in the upper right on the level's schematic to the right of the scoring data, though that's a little less obvious since it could be interpreted to mean resetting the score for just that one schematic rather than the level as a whole.

Or a final alternative would be on the level map.  An explicit button there might not be great there but perhaps a magic key combination list ctrl+shift+R you could push/click when hovering over a level blob?  Would add another thing for the "this should be documented somewhere" pile, but it probably isn't a feature that should be used for the most part (especially once all the test coverage has been settled and we have a well-defined line between 'cheated' and 'legit' solutions).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Actually I just changed it in 0.365 so after you open the sync page it will notice which levels the server disagrees with. Then when you complete that level again it will use the new score no matter what. Right now the scores are in flux, but later the levels will be more stable and we wont have to worry about this
