### ISSUE TITLE
[Bug]: Not repsonding when opening sandbox

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#202]
### Discord Thread

https://discord.com/channels/828292123936948244/1278351306091659397

### What happened?

With todays version, the game crashes (not a "clean" crash where it closes immediately, a "process is not responding" crash) as soon as I open the sandbox, no clues in the console output.

### Version

0.1131 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I believe this was fixed
