### ISSUE TITLE
[Bug]: Current iteration of Tangled Gates doesn't work properly

### ISSUE THREAD

**Issue by ShadF0x** [Turing-Complete-Game/Suggestions-and-Issues#203]
### What happened?

Current iteration of Tangled Gates (using NOR gates) doesn't work properly. The state of the circuit during the tests seems to be dependent on the state of the circuit before the testing. So far I was able to complete up to three test cases without changing the circuit, most of the time failing the first case and never completing the whole suite.

The issue seems to be in how the states of the components are updated, with the simulation essentially running one tick behind the test cases.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SIGSTACKFAULT** [comment]
also experiencing.

**Comment by MarximusMaximus** [comment]
same on Mac M1 macOS 12.1 (21C52), beta 0.367

**Comment by MegaIng** [comment]
This has been fixed by replacing the level
