### ISSUE TITLE
[Bug]: Recursive definition of %c in isa.spec crashes

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#203]
### Discord Thread

https://discord.com/channels/828292123936948244/1278695078994378793

### What happened?

Error: ```
Hint: used config file 'C:\bin\nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\bin\nim\config\config.nims' [Conf]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
10123 lines; 0.046s; 10.477MiB peakmem; proj: C:\bin\msys64\home\mark\src\isa_spec\main.nim; out: C:
\bin\msys64\home\mark\src\isa_spec\main.exe [SuccessX]
Hint: C:\bin\msys64\home\mark\src\isa_spec\main.exe check_add.spec check_add.asm [Exec]
C:\bin\msys64\home\mark\src\isa_spec\main.nim(64) main
C:\bin\msys64\home\mark\src\isa_spec\isa_spec.nim(558) assemble
C:\bin\msys64\home\mark\src\isa_spec\isa_spec.nim(1017) pre_assemble
C:\bin\msys64\home\mark\src\isa_spec\isa_spec.nim(657) assemble_instruction
C:\bin\msys64\home\mark\src\isa_spec\expressions.nim(140) eval
C:\bin\msys64\home\mark\src\isa_spec\expressions.nim(135) eval
C:\bin\nim\lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: index 2 not in 0 .. 1 [IndexDefect]```

### Version

0.1131 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
