### ISSUE TITLE
[Bug]: Registers in custom components fail to update

### ISSUE THREAD

**Issue by sunnyssk** [Turing-Complete-Game/Suggestions-and-Issues#204]
### What happened?

With the Dec 23th refractoring patch, the registers placed in custom components fail to update in architectures. They still work as expected in the component factory when constructing the components.

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by teliot** [comment]
Counters as well.
