### ISSUE TITLE
[Bug]: Inconsistent size and position of values

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#205]
### Discord Thread

https://discord.com/channels/828292123936948244/1278674053053288498

### What happened?

The value displayed on the components does not have a consistent size or position.
The value for Delay is larger than the others.
The position for Register is approx. 1 pixel down and to the left, compared to Count and Constant.

![image](https://github.com/user-attachments/assets/2d4e9e51-3933-4291-a7d1-c7f9357dc224)
![image](https://github.com/user-attachments/assets/7e763b8b-e229-4151-b141-f3e4f9a618cf)

### Version

0.1132 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
