### ISSUE TITLE
[Request]: [UI] Wire color changing tool

### ISSUE THREAD

**Issue by TempNameSuperstar** [Turing-Complete-Game/Suggestions-and-Issues#205]
### Request?

I think it would be nice to have a tool to change wire colors without having to rewire large sections of the computer. It would help a lot when experimenting on or "refactoring" larger systems.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
We do have such a tool: `CTRL+R`, `CTRL+F` and `CTRL+E` (maybe it's something different for you. Look into the settings)

**Comment by TempNameSuperstar** [comment]
Oh, thanks! I guess I need to look more thoroughly before submitting next time! Sorry for cluttering up the feature requests!
