### ISSUE TITLE
[Bug]: Label under wire

### ISSUE THREAD

**Issue by TempNameSuperstar** [Turing-Complete-Game/Suggestions-and-Issues#206]
### What happened?

When connecting a wire to a wire that already has a label, the label will appear underneath the wire.
![image](https://user-images.githubusercontent.com/34651716/147409259-366208d0-186c-405a-afb9-a1c82ad800bd.png)
 

### Version

Latest

### Operating System

Windows 10 (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SunCatMC** [comment]
fixed as of 0.544
