### ISSUE TITLE
[Bug]: Alpha: Counting Signals - not connecting to output pins results in negative values

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#206]
### Discord Thread

https://discord.com/channels/828292123936948244/1266938257816551485

### What happened?

The unconnected pins are counted as negative values in binary, -1, -2, -4 respectively. Connecting constant zero makes the pin value 0. Connecting constant one makes the pin value positive 1,2,4.

No output pins connected - Current output -7
All output pins connected to constant false - Current output 0
All output pins connected to constant true - Current output 7

### Version

0.1132 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
