### ISSUE TITLE
[Bug]: "Conditions" level does not save schematic to Component Factory

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#207]
### Discord Thread

https://discord.com/channels/828292123936948244/1280274446250410195

### What happened?

On Turing Complete 0.1137 Beta on Windows

I noticed this when moving onto "Turing Complete" where the COND custom component is required and it does not appear in the list of custom components

### Version

0.1137 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think it is fixed now
