### ISSUE TITLE
[Bug]: If you change the circuit to the correct circuit mid validation, the output is garbage but you get a pass

### ISSUE THREAD

**Issue by RolfHuisman** [Turing-Complete-Game/Suggestions-and-Issues#207]
### What happened?

On 0.373 Beta
If you make a correct circuit in counting signals and remove the last connection and then perform a few F5's:
![Step 1](https://user-images.githubusercontent.com/39134931/147412613-576e270e-5b04-4d97-b145-8fb1e96d8e85.png)
Then in this state, correct the circuit by connecting the last wire:
![Step 2](https://user-images.githubusercontent.com/39134931/147412618-cdb74c0a-1d99-4bb9-859a-40bb60457e08.png)
Press F5 for the ticks, and the wrong results will be in the bottom, but still pass the level:
![Step 3 Wrong](https://user-images.githubusercontent.com/39134931/147412621-9d964c2a-2bcc-4f02-a0c2-11fc0096bfcd.png)

### Version

Latest

### Operating System

Windows 11 Dev (22523.1000)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RolfHuisman** [comment]
Rerunning the validation results in the correct values, so its probably a missing reset of the validation.

**Comment by SunCatMC** [comment]
fixed as of 0.544 due to validation starting from beginning after edit
