### ISSUE TITLE
[Bug]: Crash loading level not_gate was: When editing assembler, game crashes, and other crashes (possibly related)

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#208]
### Discord Thread

https://discord.com/channels/828292123936948244/1280587729041887283

### What happened?

I downloaded the save breaker beta for the first time, and immediatly starting going to the sandbox to experiment with it, i edited the assembler and the game crashed, so i tried a few things to see where the crash was coming from (including editing the levels text file in the save file) and when i had set nand_gate to true, i opened the game again and tried to open the level following that (which the game then crashed), so i opened the game again and now it just crashes immediately

### Version

0.1137 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
One crash was related to loading the level `not_gate`, OP not sure how to repro other assembler bug.

**Comment by Gelthir** [comment]
Crash log on entering `not_gate`: ```
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Radeon RX 580 Series
OpenGL ES Batching: ON

unknown level property max_trial_scoring in campaign\_binary_programming
unknown level property trials in campaign\_binary_programming
unknown level property max_trial_scoring in campaign\_water_world
unknown level property trials in campaign\_water_world
unknown level property current_version in campaign\_water_world
unknown level property highscore_version in campaign\_water_world

E:\games\steam\steamapps\common\Turing Complete>start cmd /k simulator.exe 5002
Turing Complete 0.1137 Beta on Windows
``` and ```

Couldn't read the expression inside the parenthesis.
[31m(713)[0m
def set_[31m("", my_text)[0m_pos(x: Int, y: Int) {
```

**Comment by Stuffe** [comment]
fixed next patch
