### ISSUE TITLE
[Bug]: ALPHA: Assembler tries to write to non existing file and crashes

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#209]
### Discord Thread

https://discord.com/channels/828292123936948244/1280593952562614383

### What happened?

Occurs on clicking 'Edit' on the assembler. The architecture is called 'Test' and not 'sandbox'. The file mentioned in the error message does not exist.

### Version

0.1137 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Turing Complete 0.1137 Beta on Windows
io.nim(884)              writeFile
Error: unhandled exception: cannot open: C:/Users/<redacted>/AppData/Roaming/Godot/app_userdata/Turing Complete/schematics/architecture/sandbox/new_program.asm [IOError]
```

**Comment by Stuffe** [comment]
fixed
