### ISSUE TITLE
'Unsigned Less' needs more test coverage.

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#209]
### What happened?

This solution apparently passes even though it wouldn't pass if (A,B) were (0,0), (1,1) nor (1,0)

![image](https://user-images.githubusercontent.com/3260768/147445399-72481854-dbc7-4240-8ddb-ff7f04d06c19.png)

### Version

Latest

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by paulstelian97** [comment]
Proper coverage is doing comparisons that would give all 3 possible results for all combos of sign bits of the inputs.

**Comment by Stuffe** [comment]
I think this was fixed
