### ISSUE TITLE
[Bug]: Console component does not work correctly

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#21]
### Discord Thread

https://discord.com/channels/828292123936948244/1264169365767589938

### What happened?

Not really sure what step is going wrong, but it doesn't display the stuff that is put it. And no, color mode doesn't change anything.

![image](https://github.com/user-attachments/assets/b7fe643f-be8f-493d-ae59-0ae9abe1bae8)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Not only does it work now, it also feels super responsive
