### ISSUE TITLE
[Bug]: ALPHA: Opening a custom component does not correctly save register state.

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#210]
### Discord Thread

https://discord.com/channels/828292123936948244/1280599367497027644

### What happened?

Save file will be sent in. Seems to happen when you have a custom component A containing a register, and then place multiple of those inside another custom component B. When opening B, all registers seem to get the same value from one register instead of their actual value.

### Version

0.1137 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
