### ISSUE TITLE
[Bug]: Cheat discovered in "Saving Gracefully"

### ISSUE THREAD

**Issue by iamstillalexh** [Turing-Complete-Game/Suggestions-and-Issues#210]
### What happened?

![image](https://user-images.githubusercontent.com/44297537/147509208-df732c26-840b-458c-9864-79fdde787dac.png)
While messing around trying to figure out the "Saving Gracefully" level, I figured out a way to get the correct output without using the "value" input at all. Maybe it's worth testing for more "edge cases" like this by forcing a situation where the "value" input MUST be used into the test I/O?

### Version

Latest

### Operating System

macOS Monterey 12.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Next patch the pattern is less predictable and also tests the case where the same value is stored twice
