### ISSUE TITLE
Shown maze does not update on faster speeds / Robot can move through walls in The Maze

### ISSUE THREAD

**Issue by fuchslucian** [Turing-Complete-Game/Suggestions-and-Issues#211]
### What happened?

https://user-images.githubusercontent.com/80114645/147554630-11a1ea8d-871a-4446-93c5-079bc73fa845.mov

My robot can run through walls. I think the Robot works but the Assembly Editor shows the wrong maze

### Version

Latest

### Operating System

macOS BigSur Version 11.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by x416C6578** [comment]
I Might have a similar problem (program freeze at higher speed: freeze somewhere in the 1rst maze when tested at 1KHz and 500MHz / works at 100MHz and 200 MHz).
After freezing the in game program, the game itself becomes unresponsive.
I can produce a video / save file if requested

**Comment by x416C6578** [comment]
Also, on some levels, at 100MHz, I confirm Robots seems to navigate a different maze than displayed (goes through walls)

Same code / architecture  from early December (before the memory update)

**Comment by SunCatMC** [comment]
fixed as of 0.544
