### ISSUE TITLE
[Bug]: ALPHA: RAM output behaves strange when load is disabled.

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#212]
### Discord Thread

https://discord.com/channels/828292123936948244/1280608692127137802

### What happened?

(See image in the discord post). The output pin does not cause a short circuit with the constant, but it does seem to interfere as the value from the constant does not get saved. 
If the top wire from the output to the input is disconnected, the circuit works as expected. 
If load is enabled, this (sometimes) causes a short circuit.

### Version

0.1137

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
It has nothing to do with Z state. You can't see it in the screen shot, but those two pins are orange
As a reminder, orange pins never cause circular dependencies

**Comment by Gelthir** [comment]
The original post states this does not cause the expected short cirtcuit between the 20 form the constant and 0 from the RAM. Circular dependancy was not the issue reported.

A suggested fix was disabled RAM could output Z.

If I build the circuit described in the OP in version 0.1140 it crashes with:
```
Variable [34mor_field_259[0m not in scope.
[31m(980)[0m
                [31mor_field_259[0m |= <U8>  (<U8> (20))
```

Do you want a test case for this, or has this been fixed already?

**Comment by Stuffe** [comment]
Sorry, you are right

**Comment by Stuffe** [comment]
Fixed next patch
