### ISSUE TITLE
[Bug]: ALPHA: Unexpected 0 output value from division

### ISSUE THREAD

**Issue by mbraunecker** [Turing-Complete-Game/Suggestions-and-Issues#214]
### Discord Thread

https://discord.com/channels/828292123936948244/1266150238888919282

### What happened?

The division seems to output the correct value on the data line (33/11=3) and for comparison the output of the multiplication (33*11=363). But the delay line (or registers) update to value 0 in case of the division.

### Version

0.1137 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This was fixed
