### ISSUE TITLE
[Bug]: ALPHA: RAM output visually appears one tick early

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#215]
### Discord Thread

https://discord.com/channels/828292123936948244/1280861427493634099

### What happened?

Saving and loading from RAM in the same tick causes the value to appear on the output wire in that same tick. Observing the output through a delay gate shows the expected results (the old value in this tick and the new value next tick).

### Version

0.1137 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
