### ISSUE TITLE
[Bug]: Undo crashes after moving a ghost component of another component

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#216]
### Discord Thread

https://discord.com/channels/828292123936948244/1281868548788191252

### What happened?

After moving the ghost component away fromt he overlap, pressing CTRL+Z crashes the game. Doesn't happen when the ghost only overlaps wires.
![image](https://github.com/user-attachments/assets/2dc7f5e8-8061-4b06-ad85-a069f6703c5d)

### Version

0.1140 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Turing Complete 0.1140 Beta on Windows
fatal.nim(54)            sysFatal
Error: unhandled exception: cache_opps.nim(67, 12) `h notin component_area_obstructions` AREA POS: (x: 25, y: -158) 27 12 [AssertionDefect]
```

**Comment by Stuffe** [comment]
fixed next patch
