### ISSUE TITLE
[Bug]: Confusing (misplaced) error in level Registers

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#216]
### What happened?

When in level Registers you have a working arch, but you disconnect the byte wire from output and try to test that, the error you get is "Output enable bit not connected", even tho it is actually still connected

![image](https://user-images.githubusercontent.com/26610984/147611529-57056b9d-213e-4517-9870-5186f44477f3.png)

Related to #215, as that's where this error would've been handy

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Was fixed
