### ISSUE TITLE
[Bug]: delay not updated

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#217]
### Discord Thread

https://discord.com/channels/828292123936948244/1279593058916237362

### What happened?

If the input delay of a gate is changed to be smaller, the gate's delay will not update.
for example:
(4, 6) -> 8
(4, 8) -> 10
(4, 6) -> 10 [!]

![image](https://github.com/user-attachments/assets/b5394b8c-7863-47c0-8a01-4b070de03868)

### Version

0.1141 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
