### ISSUE TITLE
[Bug]: Area of Product of Nibbles did not grow graphically

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#217]
### What happened?

![image](https://user-images.githubusercontent.com/26136419/147617545-b2a387d2-d440-4944-bd6a-e536df576851.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
