### ISSUE TITLE
[Bug]: Level Screen replaced with Red immovable Output pin

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#218]
### Discord Thread

https://discord.com/channels/828292123936948244/1281989233803919467

### What happened?

I opened a build that previously worked in save_breaker (but not sure exactly which version) but it now has no `Level Screen` instead it's been replaced with a Red `Output`.
The `Level Screen` is not placeable in Sandbox (like it used to be) as it's missing from the build menu.
Also I can't delete the Red Output pin.

![image](https://github.com/user-attachments/assets/0eeabe2e-cd6b-4066-860e-84a9ded45cb9)

### Version

0.1141 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
The level screen is deleted and the enum value has been claimed by a new output component. Use type `dev_mode on` in the console to delete it. This is not a bug in the traditional sense
