### ISSUE TITLE
[Bug]: Assembler is accessible in levels Registers and Calculations

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#218]
### What happened?

After you build a turing complete machine, you get levels where you are allowed to edit program memory. Most levels that are not supposed to allow you to edit your prog. mem. are protected from access to assembler (see #72). But in Registers and Calculations there isn't any program component initially (just an input for instructions), and when that gets replaced with finished component, you can see the edit button on it and can access Assembly editor. It doesn't seem to affect what values are actually used for tests tho

![image](https://user-images.githubusercontent.com/26610984/147687714-3423d29a-17f1-4d88-9209-01af3e6c0e19.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next patch
