### ISSUE TITLE
[Bug]: "Front panel" does not have EDIT button

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#22]
### Discord Thread

https://discord.com/channels/828292123936948244/1264166973647093854

### What happened?

The new "Front Panel" component which seems to be similar to the Program components apparently should contain an edit button, but doesn't.
![image](https://github.com/user-attachments/assets/b0971c92-9118-431b-95c0-7f40b6fe363d)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
