### ISSUE TITLE
[Bug]: [ALPHA] Circular Dependency level broken

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#220]
### Discord Thread

https://discord.com/channels/828292123936948244/1282093889964081252

### What happened?

Something broke along the way (I obviously completed it before) but now causes the game to pause for several seconds before crashing.
Console shows:
```
PORT 5002
REQUEST: 1 sim_do
command: mode_reset -1 0
RESPONDING sim_do 1
REQUEST: 3 compile_and_run
Sim never syncs!
```

I was using NOT gates but the same happens with NOR.  This occurs as soon as the wires are connected (or on level load), though the UI doesn't seem to pause (I can still move the component around for a second or two before the crash).

This previously worked (I've gone through the alpha campaign under some earlier build, though I couldn't tell you which exactly - would have been fairly soon after save_breaker was released but possibly not right at the first version).

### Version

0.1142 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
PORT 5002
REQUEST: 1 sim_do
command: mode_reset -1 0
RESPONDING sim_do 1
REQUEST: 3 compile_and_run
Sim never syncs!
```

**Comment by Stuffe** [comment]
fixed
