### ISSUE TITLE
[Bug]: ALPHA: 'Sim never syncs!' crash in sandbox

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#221]
### Discord Thread

https://discord.com/channels/828292123936948244/1282338072226299954

### What happened?

The hangs for a few seconds, then crashed with `Sim never syncs!`. I was able to reopen the schematic the first time, but now it hangs when clicking 'Sandbox' and crashes with the same message.

### Version

0.1143

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
