### ISSUE TITLE
[Bug]: Register linking not working properly

### ISSUE THREAD

**Issue by nekokiwa** [Turing-Complete-Game/Suggestions-and-Issues#222]
### Discord Thread

https://discord.com/channels/828292123936948244/1282545193392013455

### What happened?

When linking a register, the game creates a new register in the assembler screen to link to instead, leaving the desired register unlinked.
This causes a crash when cancelling the linking of a register.
![image](https://github.com/user-attachments/assets/00376614-0845-4904-963b-249c8110ecdf)
![image](https://github.com/user-attachments/assets/1bd8b175-b967-441f-9c7f-ff94c88cb7ef)
![image](https://github.com/user-attachments/assets/59f5650d-db75-4e85-a1e3-578da52f3a3a)

### Version

0.1145 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Turing Complete 0.1145 Beta on Windows
fatal.nim(54)            sysFatal
Error: unhandled exception: index 2 not in 0 .. 1 [IndexDefect]
```

**Comment by Stuffe** [comment]
fixed next patch
