### ISSUE TITLE
My profile shows the wrong number of NAND gates

### ISSUE THREAD

**Issue by fuchslucian** [Turing-Complete-Game/Suggestions-and-Issues#223]
### What happened?

<img width="570" alt="Bildschirmfoto 2021-12-31 um 11 32 58" src="https://user-images.githubusercontent.com/80114645/147818552-a0fbaf10-771e-4d62-a602-1a34fbe15b04.png">
<img width="455" alt="Bildschirmfoto 2021-12-31 um 11 33 30" src="https://user-images.githubusercontent.com/80114645/147818561-fe83a1b0-2d33-459c-876f-1444ba9a80a2.png">

### Version

Latest

### Operating System

Mac OS BigSur

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This means that the server doesn't have one of your earlier solutions uploaded. Try rerunning all of them

**Comment by MegaIng** [comment]
I would guess that it's specifically your XOR gate that isn't on the server
