### ISSUE TITLE
[Bug]: output delay of components with memory is calculated incorrectly.

### ISSUE THREAD

**Issue by danielrab** [Turing-Complete-Game/Suggestions-and-Issues#224]
### What happened?

custom components with interconnected memory (which is common for counters for example) give wrong output delay. Here are some examples
![image](https://user-images.githubusercontent.com/6858789/147830900-cc8f4ebe-f6df-4845-be6f-d859a18a9830.png)

### Version

Development

### Operating System

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed
