### ISSUE TITLE
[Request/Bug]: Combinatorial Circuit based levels should be reset for each input

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#225]
### Request?

This is to prevent cheese using the delay buffer for optimal solutions that pass the tests but don't actually work. An example of this is the instruction decoder and the 3 bit decoder where you can use a nor gate and multiple delay buffers to complete the level.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scottanderson** [comment]
![image](https://user-images.githubusercontent.com/662325/147838342-5d8af3f9-98e3-43cf-9edc-29520bac8da0.png)

**Comment by Rartrin** [comment]
After finding I found this, I checked to see what other levels are affected by this.

Affected levels that I've found:
- Instruction Decoder
- Bit Inverter
- 3 Bit Decoder

While the first two only really after score for that level, the 3 bit decoder affects the component in other levels.

**Comment by Stuffe** [comment]
fixed
