### ISSUE TITLE
[Bug]: ALPHA: 'Add 5' Front Panel has the values from 'Turing Complete'

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#225]
### Discord Thread

https://discord.com/channels/828292123936948244/1283398606593855569

### What happened?

The front panel does not contain all 0, but instead the values from the previous level.

### Version

0.1147

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
