### ISSUE TITLE
[Bug]: ALPHA: Crash when entering sandbox

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#226]
### Discord Thread

https://discord.com/channels/828292123936948244/1283399759398309920

### What happened?

The game crashes when entering the sandbox.

### Version

0.1147

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
No function matched [34march_get_input[0m([33mInt[0m, [33m[[0m[33mInt[0m[33m][0m).
Perhaps you meant:

[31mdef[0m [34march_get_input[0m([34mtest[0m: [33mInt[0m) [33mInt[0m { ...



[31m(2097)[0m
                result_15 = <U8> [31march_get_input(.test, $.scratch_space)[0m
                _store(result_15, VALUE_BUFFER, 280)
```

**Comment by Stuffe** [comment]
fixed next patch
