### ISSUE TITLE
[Bug]: The Waveform Generator isn't able to modulate note length.

### ISSUE THREAD

**Issue by GreenGem-ButOnGitHub** [Turing-Complete-Game/Suggestions-and-Issues#227]
### What happened?

I'm not sure that the waveform generator is working as advertised. 
1. Flip the middle 2 bits and it plays a C4 (that makes sense). 
2. Also flip the 2nd bit from the right and it plays a D4. 
3. Instead flip the 2nd bit from the left and it plays a C5. 

At no points are any bits being used to determine note length, as I've just used every contiguous segment of 2 bits to modulate the pitch.

This behavior can be easily verified using this simple program (increment the counter by 1):
![image](https://user-images.githubusercontent.com/11450137/147856362-3fd6f309-5b20-4990-bcc4-e94d13a8beef.png)

### Version

Latest

### Operating System

WIndows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This component was replaced
