### ISSUE TITLE
[Bug]: Crash when renaming deleted wire

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#228]
### What happened?

When using the edit label tool, clicking on a wire opens up a popup. When deleting the wire before closing the popup, the pressing "Save" on the popup crashes the game.

### Version

Development

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
