### ISSUE TITLE
[Bug]: A few levels complain about "old save" in fresh run of the game

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#23]
### Discord Thread

https://discord.com/channels/828292123936948244/1264151902279569460

### What happened?

Specifically these three levels at least:

- ODD TICKS
- COUNTING SIGNALS
- HALF ADDER

Because this error prevents simulation, these levels are unbeatable.

![image](https://github.com/user-attachments/assets/908a4a80-e159-4f29-92e1-678f5b716794)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
