### ISSUE TITLE
[Bug]: Delay overlay prevents WASD movement.

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#23]
### What happened?

When activating the Delay overlay, it is no longer possible to pan with WASD.

Also, there is weird interaction with other shortcuts like `CTRL+E` allowing you do color the middle of a wire without it's connected pins. (#24 )

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
Could you edit the issue to have more information about "Delay overlay prevents wasd movement" as the nature of the issue is not clear.

Info such as Steps to Reproduce, Conditions where the bug happens, etc

----

For CTRL-E That paints a segment, I beleive CTRL-F paints the whole wire.

**Comment by MegaIng** [comment]
When activating the Delay overlay, it is no longer possible to pan with WASD.

> For CTRL-E That paints a segment, I beleive CTRL-F paints the whole wire.

I know, that is not what I am talking about. Try it out.

![image](https://user-images.githubusercontent.com/26136419/140828155-396c652f-5648-4f4e-abc7-509edb80c22d.png)

**Comment by Stuffe** [comment]
fixed in  0.290
