### ISSUE TITLE
[Bug]: [ALPHA] New Objective Beauty level breaks with CCs.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#230]
### Discord Thread

https://discord.com/channels/828292123936948244/1284221113668337685

### What happened?

See screenshot.  Total score is 7/3, which is well less than 10 gates.  If I pull the half adders out and build the circuit directly, it works fine.
The score shown in the top right is correct - its just the error check that fails.
![image](https://github.com/user-attachments/assets/ea2e49ab-3f55-4e47-ac5d-3ac4d3d40b08)

### Version

0.1154

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I believe this was fixed
