### ISSUE TITLE
[Request]: Allow input and output overlapping

### ISSUE THREAD

**Issue by kerams** [Turing-Complete-Game/Suggestions-and-Issues#230]
### Request?

For example, given this byte maker

![Namnlös](https://user-images.githubusercontent.com/5063478/147875037-bfc0f281-9ecc-421b-81c3-852a1bad47a4.png)

I'd like to move the component one unit to the left, so that the outputs of the ON components overlap the inputs of the byte maker, and signals pass implicitly without having to create any wires.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This would require a huge refactoring for many different reasons, so this wont be done
