### ISSUE TITLE
[Bug]: Custom components show buffered square inputs only when placed

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#232]
### What happened?

When you look in the menu at custom components that have buffered pins, they show up as regular circular pins. Same happens when you take them out to place them. Square pins only show when you have that component on the map

![image](https://user-images.githubusercontent.com/26610984/147878003-76367ba5-5153-4b75-b34f-8521a6bdaa53.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
