### ISSUE TITLE
[Bug]: Quotation marks in Little Box IO pin panel

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#233]
### Discord Thread

https://discord.com/channels/828292123936948244/1284473729337786430

### What happened?

There are extra quotation marks display on the IO pin names on the left hand panel.
I haven't noticed it on any other level, but haven't properly looked.

![image](https://github.com/user-attachments/assets/79a4b1c3-ec51-421f-95ae-9439475595ec)

### Version

0.1154 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
