### ISSUE TITLE
[Bug]: Manual entry on Self dependency does not match with current behavior

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#233]
### What happened?

Self dependency describes pins having an asterisk to show that a pin may depend on an output of the component, while now the pins are shown as orange squares, instead of having asterisks

![image](https://user-images.githubusercontent.com/26610984/147878318-9a9d2ab8-1d3f-43e6-9b50-bafa8465907a.png)

also, you currently have to search for said manual page, instead of how it used to be - the asterisk was linking to the relevant manual page.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
