### ISSUE TITLE
[Bug]: Level "Shift" allows left and right shift of the same input

### ISSUE THREAD

**Issue by Pr0metheus42** [Turing-Complete-Game/Suggestions-and-Issues#234]
### What happened?

Currently the optimal solution to the level is to read input on tick 0, shift it and shift a delayed input the other direction
![image](https://user-images.githubusercontent.com/21281226/147880835-4efd2b82-b2a8-49b3-b2bf-9e9972fd5350.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This level was removed
