### ISSUE TITLE
[Bug]: Calculations scenario instruction and check mismatch

### ISSUE THREAD

**Issue by FortySixnTwo** [Turing-Complete-Game/Suggestions-and-Issues#235]
### What happened?

In the scenario calculations, my ALU which passed the ALU scenario, and seems to be correctly handling the 2nd tick test of 0111 1011 (123) NAND 0000 0000 is being failed. The game states REG2 should be 0 where as it is 255. 

Unless I'm being daft, which is quite likely, is the check asking for AND instead of NAND which is provided by the input?

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I would guess you are miscounting the registers. It's zero based, so it's REG0, REG1, REG2, REG3, ... , not REG1, REG2, REG3, REG4, ...

**Comment by FortySixnTwo** [comment]
![image](https://user-images.githubusercontent.com/37109710/147914982-160a8140-7d32-4bb9-9962-c3f69cf90bbb.png)
