### ISSUE TITLE
[Bug]: Crash on Undo with Circular Dependency

### ISSUE THREAD

**Issue by Starficz** [Turing-Complete-Game/Suggestions-and-Issues#236]
### What happened?

Reproduction:
1: Go to component factory
2: Connect input of NOT gate to bit output
3: Create circular dependency by connecting output of NOT to input wire
4: Ctrl-Z

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next patch
