### ISSUE TITLE
[Bug]: Crash on holding F5 on unfinished level solved wrong

### ISSUE THREAD

**Issue by Brambor** [Turing-Complete-Game/Suggestions-and-Issues#237]
### What happened?

A crash occurs when holding F5 (next tick), or spamming the [next tick] button.
You have to be playing unfinished level.
You have to have wrong solution.

Reproduction Example:
1) Start level you haven't finished that is empty.
2) Hold F5.
3) Observe crash.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
this is solved
