### ISSUE TITLE
[Request]: New components

### ISSUE THREAD

**Issue by mpklink** [Turing-Complete-Game/Suggestions-and-Issues#238]
### Request?

Would it be possible to have some new components added or a way to import or create components?  Some of the things I'm thinking of would be custom buttons and LED 7 segment displays or even LCD displays, etc., so that we could design things like calculators or handheld games.  I could see this being a great tool for hobbyist electronics developers to try out their projects in a game space before creating the real thing using electronic components. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
There is a keyboard component and a console component currently.

**Comment by Stuffe** [comment]
I don't see any good way to allow fully custom screens. But the goal is to cover the typical display paradigms with different screens and have them be powerful and flexible enough to support the majority of use cases.
