### ISSUE TITLE
[Bug]: Copy paste doesn't work on linux

### ISSUE THREAD

**Issue by Stuffe** [Turing-Complete-Game/Suggestions-and-Issues#239]
### What happened?

Copy paste doesn't work on linux.

Reported on steam and by user on discord:
https://discord.com/channels/828292123936948244/850737218759032892/928024173035532388

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmerry** [comment]
For what it's worth, copy-paste works fine for me on Ubuntu 20.04.

**Comment by Stuffe** [comment]
This was probably the bug where you couldn't copy while having the selection button active
