### ISSUE TITLE
[Bug]: In signed mode, the input panel in the top left is a bit confused.

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#24]
### Discord Thread

https://discord.com/channels/828292123936948244/1264160725513797674

### What happened?

Not really sure how to describe it. It feels like the top bit is ignored and assumed to be 1?

![image](https://github.com/user-attachments/assets/c696231a-99fa-4f90-9039-55ac4fa019cf)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
this was fixed
