### ISSUE TITLE
[Bug]: Wire Pins do not do not inherit wire color while Delay Overlay is active

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#24]
### What happened?

Source: https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/23#issuecomment-963632979

When applying a color to a wire via CTRL-E the pins do not always reflect the new color.

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
There is a recent I didn't open a separate issue for this: This only happens then the delay overlay is active. Otherwise it works correctly.

**Comment by bombitmanbomb** [comment]
@MegaIng is still a bug albeit a very minor one.
