### ISSUE TITLE
[Bug]: 3 Adder Multiply Achievement Falsely Triggers

### ISSUE THREAD

**Issue by zamadatix** [Turing-Complete-Game/Suggestions-and-Issues#240]
### What happened?

> 3 Adder Multiply
> 
> Complete "The Product of Nibbles" using no more than 3 adders

This achievement triggered even though I used more than 3 adders from the bytes menu in this level.

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can you show your solution/upload to the website?

**Comment by zamadatix** [comment]
I think this is the version that triggered the achievement:

![image](https://user-images.githubusercontent.com/343550/148653666-9950d023-8611-45a0-959e-b41b4e8cdd41.png)

Looking at it and reading the achievement again is it possible the actual actual goal is "use no more than 3 adders in series" or similar? While this version used 11 adders it was never more than 3 adders deep (cyan lines on the far left).

**Comment by Stuffe** [comment]
Fixed
