### ISSUE TITLE
[Bug]: Continuous crashing after experiencing Issue #228

### ISSUE THREAD

**Issue by Dr-Game** [Turing-Complete-Game/Suggestions-and-Issues#241]
### What happened?

Extension to issue #228. The game will crash upon clicking "Save" on the renaming popup after first deleting the wire to be renamed. However, the game now continues to crash after completing almost any level in the game, or clicking the "Level Map" button to exit a level. This issue persists even after uninstalling and reinstalling the game.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
