### ISSUE TITLE
[Bug]: 0x0 is not considered valid in assembly editor

### ISSUE THREAD

**Issue by roblabla** [Turing-Complete-Game/Suggestions-and-Issues#242]
### What happened?

The following code in the assembly editor will trigger an error:

```
const A 0x0
```

The error is: Need a name and a value after "const" (e.g. const up 3)

The code `const A 0x00` works without issue. It looks like the assembly parser expects at least two digits after the `0x` prefix.

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next patch
