### ISSUE TITLE
[Bug]: Four bit XOR level

### ISSUE THREAD

**Issue by JakeGR0** [Turing-Complete-Game/Suggestions-and-Issues#244]
### What happened?

Level does not complete if solved with NAND gates. 

### Version

Latest

### Operating System

windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Did you solve it with less than 3 components?

**Comment by JakeGR0** [comment]
no

**Comment by MegaIng** [comment]
Then you didn't complete the challenge of the level.

**Comment by JakeGR0** [comment]
Ah my bad, just trying to help, perhaps i'm to drunk to take everything in properly.
