### ISSUE TITLE
[Bug]: Undo breaks delay buffer

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#245]
### What happened?

Reported by VL4DL3N on Discord
https://discord.com/channels/828292123936948244/850737218759032892/929771770016329778

> On "Saving Gracefully" delayed buffer won't work after reversing it and Ctrl+Z him back in place

![image](https://user-images.githubusercontent.com/662325/148694334-0837a0bf-bea7-4a70-b8bc-6ec8ac18f44e.png)

### Version

Latest

### Operating System

Unknown

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
