### ISSUE TITLE
[Bug]: 2nd Level can not be validated (faulty components availability check)

### ISSUE THREAD

**Issue by kevin-frugier** [Turing-Complete-Game/Suggestions-and-Issues#246]
### What happened?

Just purchased the game.
Version 0.419 Beta

First level OK, 2nd Level with NAND gate can not be completed "Some of the components used are not supposed to be available in this level. Therefore the solution is not scored."
I did nothing but try, as requested, the input values and see the impact on the output (which I then entered before checking my answer)

![Screenshot 2022-01-09 224743](https://user-images.githubusercontent.com/9249864/148702430-cb579e17-5ff1-4ded-abe0-f74f106691af.png)
.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Till this is fixed the only real workaround is to by pass the level with save editing, editing progress.data with an sql editor like https://sqlitebrowser.org/

**Comment by MegaIng** [comment]
This has been fixed now.
