### ISSUE TITLE
[Bug]: Better feedback on 3 Bit Decoder

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#246]
### What happened?

If I have of the 2 (or more) output bits ON then the level correctly fails to validate. However it's not made clear that the the failure is due to more than 1 output is on.

![image](https://github.com/user-attachments/assets/8f251f23-ab83-43ff-8101-645ef42c6985)

This (somewhat artificial) circuit turns on `Output 7`  for all input put apart from `011` and `111`. But the bottom panel suggest that valid outputs were received for all inputs.
There is a red flash, but this is easy to miss IMO, and doesn't make it clear what the user's error is.

Suggestion: Annotate the table with a `*`, `X` or other symbol on the failing test cases rather than the number of the first set output pin.

### Version

0.1164 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
