### ISSUE TITLE
[Request]: shortcut to remove a mid-wire connection point

### ISSUE THREAD

**Issue by bmerry** [Turing-Complete-Game/Suggestions-and-Issues#248]
### Request?

If I create a side-branch off a wire, then later delete it, I'm left with a connection point on the wire, which I often want to remove (apart from being aesthetically unpleasant, it can end up forcing the wire to route through that point when the endpoints are moved, and other wires have to route around that point). I can do it by shift-clicking the connection point and then moving to overlay another connection point, but that's tedious. It would be handy to have a keyboard shortcut that removes selected connection points with degree 2.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
You can now remove this by right clicking once on the connection point
