### ISSUE TITLE
[Bug]: high resolution displays scale down the UI

### ISSUE THREAD

**Issue by danielrab** [Turing-Complete-Game/Suggestions-and-Issues#249]
### What happened?

The UI of the game seems to have hard-coded sizes in pixels, instead of fractions of screen resolution.
Here's an example of how it affects the UI for a 4k display:
![HDPI_-_Application_1](https://user-images.githubusercontent.com/6858789/148787062-c6e23358-b311-4ec1-8f29-06181d05e64a.png)
![HDPI_-_Application_2](https://user-images.githubusercontent.com/6858789/148787070-75b3d129-fce9-4d35-825c-52f550ed2ce0.png)

for reference, here's how the same scenes look on a 1080p display:
![Default_1](https://user-images.githubusercontent.com/6858789/148787191-a0925127-7e4a-4979-b19b-9e3fb0413b3e.png)
![Default_2](https://user-images.githubusercontent.com/6858789/148787202-45382922-af2b-4ce1-b03a-b32790124093.png)

All the UI elements should probably be scaled with the vertical resolution of the display.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
An option to configure scaling might be nice as well.

**Comment by scottanderson** [comment]
+1 slider in the settings menu. As a work-around, the Windows display scaling feature (pictured below) works with TC.

![image](https://user-images.githubusercontent.com/662325/148829087-aa6c7186-b507-4735-a194-d3253385b7ba.png)

**Comment by Stuffe** [comment]
Scaling has been added
