### ISSUE TITLE
[Bug]: Leaderboard is downgrading player scores

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#25]
### What happened?

I used to have 0/0 or, but now the leaderboard shows 0/2. I have not been able to improve any of my later level scores which rely on 0/0 or since this occurred. Other players have reported the same issue, and the number of players who have the 0/0 OR solution on the leaderboard is decreasing over time.

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think this was when the lowest delay score for OR was momentarily 2. This will solve itself when scoring is reenabled.

**Comment by scottanderson** [comment]
For related issue with leaderboard not updating, see https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/33
