### ISSUE TITLE
[Bug]: IO components in quite a few levels are unmovable

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#25]
### Discord Thread

https://discord.com/channels/828292123936948244/1264157045188464710

### What happened?

For readable solutions, they should be movable. Especially levels like `ADDING BYTES` or `3BIT DECODER` are negatively affected.

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I actually intended this. This way I don't have to explain why I lock components in levels that produce custom components
