### ISSUE TITLE
[Bug]: Latency RAM Load Value shows bogus values on wire

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#250]
### Discord Thread

https://discord.com/channels/828292123936948244/1287653591443832902

### What happened?

Single-stepping through ticks seems to make the Load Value wire get stuck after a load completes, instead of resetting back to 0. Seems to only be a visual bug, since computing some result with that value and storing back in the RAM seems to act as if that value was 0 after all.

![image](https://github.com/user-attachments/assets/98c94fbb-a093-4573-a489-cb78e19e25e8)

### Version

0.1164 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Should be fixed in 0.1166
