### ISSUE TITLE
[Bug]: Crash when pasting custom components

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#250]
### What happened?

The game crashes when pasting at the end of the following bug. I also uploaded by save. I assumes this has something to do with the enormous size of the individual components. This is nesting layer 5 or 6.

https://user-images.githubusercontent.com/26136419/149036100-e8fb3da4-41bf-47e8-9261-864192921429.mp4

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed
