### ISSUE TITLE
[Bug]: Output pins on custom components allow wrong sized values

### ISSUE THREAD

**Issue by tali713** [Turing-Complete-Game/Suggestions-and-Issues#252]
### What happened?

I would expect an output pin to behave similarly to input pins on standard components.  e.g. a bit pin is implicit or across the width of the wire, a byte pin is an implicit mask.  Instead they behave as a pass through and do not alter the value even when it is too large.

### Version

Latest

### Operating System

Ubuntu 10.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
