### ISSUE TITLE
[Bug]: Word AND / NAND / NOR gate scores are not set correctly

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#253]
### Discord Thread

https://discord.com/channels/828292123936948244/1285832471379968014

### What happened?

Word AND / NAND / NOR gates are unlocked in the Arithmetic Logic Unit (ALU) 1 level,

but they shouldn't use the score from that level, they should copy the score from the Byte OR level instead;

or better yet, make their score hardcoded (gate score: width, delay score: 1),
as they're essentialy just arrays of non-interconnected gates.

### Version

0.1168 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
