### ISSUE TITLE
[Request]: 32/64 bits opcodes/mnemonics

### ISSUE THREAD

**Issue by Alexei-Kornienko** [Turing-Complete-Game/Suggestions-and-Issues#255]
### Request?

Would be good to add UI support for 32/64 bit opcodes in assembly editor.
I'm trying to implement a RISC-V instruction set and it relies heavily on 32 bit opcodes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
64 bit was added, you can find it through the 64 bit program. 32 and 16 bit will be added eventually, but they will still really be 64 under the hood so it will only be a visual thing
