### ISSUE TITLE
[Bug]: Game crashing when pressing the media buttons

### ISSUE THREAD

**Issue by ExAxee** [Turing-Complete-Game/Suggestions-and-Issues#256]
### What happened?

Whenever I press the media buttons on my mouse the game crashes, to reproduce: open the "Component Factory" level, then press the "start/stop" media button and the game will crash

### Version

Latest

### Operating System

Windows 10 Home; Version: 20H2; build: 19042.1466

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This should be fixed in 0.445
