### ISSUE TITLE
[Bug]: File Loader starts wrapping addresses at 256 sometimes

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#257]
### What happened?

1) Create a text file with content abcdefgh , ie an 8-byte file
1) Create a new schematic with a File Loader. Load the text file in it. Draw a wire from the File Loader's output; it will show 0x61 (a) as  expected because its bit width is 8 (default) and its address is 0.
1) Connect a 64-bit Constant to the File Loader's input. Set the Constant to 0x101. The File Loader now outputs 0x62 (b) as if it's wrapping the address to 0x1. This is the bug.

I have another File Loader where addresses bigger than 256 work fine, but that might be because the file there is also ~100 KiB and those addresses are always within the file range. So possibly the bug only happens when the file is smaller than 256B and the address is out of range.

![image](https://github.com/user-attachments/assets/1ddb62e0-eea0-4cc5-af9c-a73e08e36583)

### Version

0.1174 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
Fixed next patch
