### ISSUE TITLE
[Request]: Configurable custom components

### ISSUE THREAD

**Issue by Pr0metheus42** [Turing-Complete-Game/Suggestions-and-Issues#258]
### Request?

Having the ability to configure custom components in a similar way to the counter will enable making 1 component rather than several variations of the same component. This could be implemented via the byte constant.
A more powerful component i want is a mux but with the control signal being a config such that it only ever reads the one input.
It essentially chooses what wires to connect. This would allow components such as a constant shift or bit extractors for neat wiring.
Since this only affects organising and cant ever reduce scores it would be a 0/0 component

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I agree that this would be nice, but it is not going to happen before custom levels, so I am closing for now
