### ISSUE TITLE
[Request]: Use maximum tick score for divide, maze levels

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#259]
### Request?

Binary long division can always be done in a single tick, but uses a prohibitively large amount of nand to be competitive.

Dividing by repeated subtraction can be done with less nand, at the cost of as many ticks as the quotient. However, because the tick score is taken from the problem `10 ÷ 3`, only three subtractions are required. Designs which divide by repeated subtraction perform worst on the problem `255 ÷ 1`.

The current scoring punishes binary long division by not rewarding its ability to always divide in a single tick.

Similarly, the best solution to the maze level is a hardcoded solution to the timed maze, plus a general solver, meaning that it does not perform well in terms of tick count for the other mazes. By taking the max tick count from all 8 mazes, there would be an incentive to optimize for a slightly larger problem space.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This should probably be the case for Tower of Alloy as well

**Comment by Stuffe** [comment]
I have now implemented support for this, but how many tests do you propose for divide? And what should the tests be (they have to be deterministic for this to make sense)

**Comment by EnderShadow** [comment]
This currently isn't tested, but how about `n / 0`?

**Comment by scottanderson** [comment]
Each test case costs 0.5~1 nand to encode into a LUT, so the number of fixed test cases would need to into the hundreds to discourage LUT cheese. Certainly one of the test cases should be `255/1`, as well as other `large/small` combinations.
