### ISSUE TITLE
[Bug]: ALPHA: Crude Awakening - Panel not visible on startup

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#26]
### Discord Thread

https://discord.com/channels/828292123936948244/1264144652257460305

### What happened?

When starting the very first level "Crude Awakening", the Panel which tells the player what to do is not visible and has to be clicked manually.
That panel should be visible right from the start so that new players don't get confused.

This behavior might only occur for players who had minimized the panel before they updated to the alpha branch.

(Reported by UnsignedRobin on Discord)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
