### ISSUE TITLE
[Request]: Byte NAND (and friends)

### ISSUE THREAD

**Issue by bmerry** [Turing-Complete-Game/Suggestions-and-Issues#260]
### Request?

I'd like to see the full set of byte versions of basic gates. In particular, the lack of byte NAND is annoying when optimising for score, because synthesizing it from the other per-byte ops (e.g. byte AND + byte NOT) is more expensive, and building it out of 8 gates + splitter + maker takes a lot of space (and is tedious). Similarly for byte XNOR, although that's probably less common. Byte NOR is less critical because it would cost the same as byte OR + byte NOT, but still nice to have for completeness.

It's probably not worth having new levels for these. Possibly the intern could do them, e.g. unlocking byte NAND after completing byte AND and byte XNOR after completing byte XOR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by paulstelian97** [comment]
I'd propose something a bit different:

For bit gates, you should be able to attach bytes as well (which automatically means apply that gate 8 times to the individual, corresponding bits), and for byte gates (and bit gates) you should be able to attach 64-bit lines as well (apply the byte gate 8 times, once for each of the bytes). The widths must match or we have some downcasting thing.

Not sure if this one would fly as it means a good chunk of redesigning the levels, but it definitely would help optimize some things. Maybe only unlock this possibility after completing a certain level or something.

**Comment by Stuffe** [comment]
We now have this
