### ISSUE TITLE
[Bug]: CTRL+A (Select-all) doesn't grab level IO pins

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#261]
### Discord Thread

https://discord.com/channels/828292123936948244/1289543951430193223

### What happened?

Select all with CTRL+A doesn't include the level IO pins, these are now movable (hooray!), so should be included in the selection.

(Tested in 3 Bit Decoder)

### Version

0.1177 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
