### ISSUE TITLE
[Bug]: OR gate as connected wires

### ISSUE THREAD

**Issue by metaflow** [Turing-Complete-Game/Suggestions-and-Issues#261]
### What happened?

It's possible in game to simulate OR gate by simply connecting wires.

e.g. this passes as 3 OR

![image](https://user-images.githubusercontent.com/254523/149841991-bd4e63ac-c4c7-4e75-999e-e8a28fb454ab.png)

while this will not work "in reality" as this will create a short circuit.

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is intentional and is not something that will be debated (it has been debated a lot). Exact realism is not a goal of this game.

**Comment by metaflow** [comment]
Oh wow, what a friendly response. Refunded the game.

**Comment by MegaIng** [comment]
Sorry if I came of as rude, that wasn't the intention. It's just that this is a very common point of discussion, brought up dozens of times already. I shouldn't have taken the fact that I am annoyed by this out on you.

Also, you are punishing the wrong person with this. I am not the dev, just active player.
