### ISSUE TITLE
[Bug]: NOT gate with AND texture

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#264]
### Discord Thread

https://discord.com/channels/828292123936948244/1290279944441823263

### What happened?

The 1-bit NOT gate seems have the AND texture/icon.
Seems to invert the input as the NOT should.

### Version

0.1179 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Uploading a fix for this now
