### ISSUE TITLE
[Bug]: Rotating component during copy-paste behaviour broken

### ISSUE THREAD

**Issue by bmerry** [Turing-Complete-Game/Suggestions-and-Issues#265]
### What happened?

Until recently, if you did Ctrl-C, Ctrl-V to copy a component then pressed space before placing the copy, it would rotate the floating copy. Now it rotates the original component. This makes it much harder to make a rotated copy of a component.

Steps to reproduce:
1. Open sandbox.
2. Place a basic gate.
3. Select the gate.
4. Press Ctrl-C.
5. Press Ctrl-V.
6. Press space.

Expected behaviour: the translucent gate rotates.

Actual behaviour: the gate placed in step 2 rotates.

### Version

Latest

### Operating System

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think it works now
