### ISSUE TITLE
[Bug]: M1 mac, crash on startup when run in arm mode

### ISSUE THREAD

**Issue by vvulpes0** [Turing-Complete-Game/Suggestions-and-Issues#266]
### What happened?

The `libbackend.dylib` file included in the macOS version of the game is an x86_64-only shared library. Meanwhile the main executable is a fat binary with both x64_64 and arm64 components.  By default, because the main executable has an arm component, it is launched in arm mode and immediately crashes with a segmentation fault after being unable to locate a proper version of the library.

* workaround: "Get Info" and check "Open using Rosetta"
* real solution: provide an arm version of the backend library
* alternative solution: strip the arm version away from the main executable

### Version

Latest

### Operating System

macOS 12.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The M1 mac is currently not supported. You can use a Beta to downgrade to an earlier version that happens to work. #251 251

**Comment by vvulpes0** [comment]
Definitely no reason to downgrade when a checkbox in the OS makes it work perfectly. This is more a "User Experience" issue — if arm is unsupported, then shipping a build where the arm component has been stripped would prevent users from having to (know about and) click that box

**Comment by MarximusMaximus** [comment]
For  me, the checkbox wasn't showing up, but found this instead which also works. (Although you'll have to repeat it after every update... which you'll know happened when it won't open again...)

```
cd ~/Library/Application Support/Steam/steamapps/common/Turing Complete/Turing Complete.app/Contents/MacOS
[ -f Turing\ Complete\ Old ] && rm Turing\ Complete\ Old
lipo -remove arm64 "Turing Complete" -output "Turing Complete New"
mv "Turing Complete" "Turing Complete Old"
mv "Turing Complete New" "Turing Complete"
```

You can now launch via Steam normally. First startup after doing this may take a little bit of time.

NOTE: For some reason, the first time I launched, I had to double click everything until I actually loaded a level once, and then single clicks started working again, even for freshly launched instances. Unsure if related.

NOTE2: Using the `arch` command to launch is no good if you want Steam support (cloud saves and such) b/c it disables those.

**Comment by MarximusMaximus** [comment]
Currently this appears to be working, albeit in Intel mode. (This is fine. For now?)

**Comment by matnick** [comment]
> Definitely no reason to downgrade when a checkbox in the OS makes it work perfectly. This is more a "User Experience" issue — if arm is unsupported, then shipping a build where the arm component has been stripped would prevent users from having to (know about and) click that box

Dear developers, you're shipping a commercial product. 
It's a key feature that it runs smoothly and people don't need to go to Github and read all the stuff to get the app running.

So, it's crucial to remove arm64 stuff from the executable, so macOS without any user notifications uses Rosetta and the app runs fine.
If you don't get that and think that users that paid for the game should create hundreds of issues that you instantly close and point to this thread, then you definitely need a new product owner who understands what UX and churn rate are.

**Comment by MegaIng** [comment]
@matnick I am not the dev. I don't expect you to read all the issues. That is why close as duplicate exists.

This game is early access. Some problems might take a while to resolve. The solo dev (not plural) has to manage the time he spends on what issues. He is very active and often has multiple patches a day. He currently doesn't himself a M1 Mac where he can test, so he instead decides to solve other issues first.

**Comment by vvulpes0** [comment]
Apple no longer sells Intel-bearing laptops. Students tend to buy (discounted, new) Apple products, and this game seems particularly appealing to an audience of computer science students. Using the `lipo -remove arm64` command to strip the arm code away from the main executable is necessary until the backend library can be built with support, or the checkbox to run the application through Rosetta 2 must be activated by the end-user.

Ideally the unsupported architecture's code would be removed by the developer before pushing updates to Steam, by that single command which requires no further coding effort or testing. Or even by selecting appropriate options in whatever build tools are used. But we have known workarounds, so the hostility seen earlier in this thread is, in my opinion, unwarranted

**Comment by ldhacker** [comment]
Just posted a similar thread over at #365 . The game runs perfectly on Windows ARM, so I don't think that it is a ARM specific issue.

**Comment by vvulpes0** [comment]
> Just posted a similar thread over at #365 . The game runs perfectly on Windows ARM, so I don't think that it is a ARM specific issue.

It's a Mac+Arm issue: `libbackend.dylib` is built _only_ for x86\_64 and contains no Arm code at all. When the main executable is run in Arm mode, it tries to load this library, and fails because there's no matching architecture.

The fix is trivial: remove the Arm code from the main executable until the backend is built properly. Then it will launch in x86\_64 mode by default and will be able to find its match in the library.

**Comment by Stuffe** [comment]
My plate is honestly just too full to officially support this right now, I think I will do it right after sharing is live (and I don't have an m1 to test on right now). However, if someone were to compile a pure x86 version of the GodotSteam 3.4.2 template, I would certainly use it, granted that it works on intel macs. Check here: https://github.com/Gramps/GodotSteam
