### ISSUE TITLE
[Bug]: 64-bit values are displayed incorrectly

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#268]
### What happened?

![image](https://user-images.githubusercontent.com/26136419/150635249-d7d0140c-9f42-44e2-ad34-9127ee0aa4c6.png)
![image](https://user-images.githubusercontent.com/26136419/150635256-67f219c2-ec56-42c8-972a-8081ced5dad1.png)
Based on this report on steam: https://steamcommunity.com/app/1444480/discussions/0/3081016749002068191/?ctp=21#c3186860850592934223

### Version

Development

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
