### ISSUE TITLE
[Bug]: Two instances of the same CC containing a RAM end up sharing the RAM contents

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#269]
### Discord Thread

https://discord.com/channels/828292123936948244/1290905804676796417

### What happened?

1) Load the "Default" schematic in sandbox. It two instances of "Default" CC, which contains a RAM.

1) Step the architecture for a few ticks. It's expected that the top CC will remain at 0 and only the bottom CC whose Store Value is connected to the Counter will change its output. But in fact the top CC will also change its output. The inner RAMs of the two CCs are sharing their contents, so writes to the bottom end up happening to the top one too.

1) Delete the top CC, then restore it via Undo or by adding a new one.

1) Step the architecture for a few ticks. This time the top CC will remain at 0, as it should.
1) Switch to the Component Factory, then back to the architecture, to trigger a reload of the schematic. Step it for a few ticks again. The bug will reappear.

This isn't just a visual bug, because in my real architecture these false writes also get read back and cause the program to behave incorrectly. There also, deleting one of the CCs and restoring it makes it work (writes to the two CCs become independent), until I restart the game or reload the schematic in some way, which makes the problem reappear. 

### Version

0.1181 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch
