### ISSUE TITLE
[Bug]: Able to paste IO into architecture schematic

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#27]
### What happened?

Copy Pasting an IO node from the Component Factory to an Architecture Level (XOR, AND, etc) will paste a Non-Editable node into the level. 

Attempting to copy/paste the new node results in a Crash

Sourced from [Discord Message](https://discord.com/channels/828292123936948244/850737218759032892/907418537616879717) by `altrag`

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I believe this is fixed a few patches ago, kindly reopen if not
