### ISSUE TITLE
[Request]: Close score summary when running tests again

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#270]
### Request?

After a level is completed successfully, a completion dialog pops up. If the player runs the tests again, the dialog remains open. Please close the dialog automatically when any of the tick controls are pressed (stop, play, fast forward, etc), or corresponding hotkeys are pressed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next patch
