### ISSUE TITLE
[Bug]: Byte wire does not update animation on element move

### ISSUE THREAD

**Issue by alexarze** [Turing-Complete-Game/Suggestions-and-Issues#271]
### What happened?

Moving two byte nodes (on any element, including the byte input) close enough that the "value stream" animation stops on the byte wire (where the nodes are in adjacent grid spaces) causes the animation to permanently stop, including when the nodes are moved further apart again.

This can very simply be reproduced by wiring together any two `byte element`s (say, a `byte input` and a `byte switch`), multi-selecting one of the elements (including its associated `byte node`), moving them so that the `byte node`s are adjacent, then moving them away again. Notice, the "value stream" animation has permanently ceased.

Can simply be fixed by deleting the `byte wire` and rewiring.

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is finally fixed in the next patch
