### ISSUE TITLE
[Bug]: Simulation pauses on each tick

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#271]
### Discord Thread

https://discord.com/channels/828292123936948244/1291516089993396346

### What happened?

This specific sequence of components in a CC makes the simulation pause after each tick instead of running continuously.

* Input pin set to a value of 0x4 or higher
* connected to a Static Shift with a negative shift
* connected to a 1-Bit Switch

If this CC is placed into an architecture, the architecture's sim also pauses on each tick. 

### Version

0.1182 Beta

### What OSes are you seeing the problem on?

Windows, Linux

**Comment by Stuffe** [comment]
PM a save if this still happens
