### ISSUE TITLE
[Bug]: Conditions level writes to "OVETURE" directory

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#273]
### Discord Thread

https://discord.com/channels/828292123936948244/1291587682106871921

### What happened?

Conditions level writes to "OVETURE" directory.

Typo there

### Version

0.1182 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
as intended
