### ISSUE TITLE
[Bug]: Can't play on macOS

### ISSUE THREAD

**Issue by Xedespy** [Turing-Complete-Game/Suggestions-and-Issues#273]
### What happened?

Game is not opening on macOS
![image](https://user-images.githubusercontent.com/71879084/151013503-d86ff528-0df0-4816-a404-67d5cb2e83e2.png)
 

### Version

Latest

### Operating System

macOS Monterey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
These might be relevant: #251 #266
