### ISSUE TITLE
[Bug]: Saving Gracefully is still in the game and doesn't work. I'm unable to progress.

### ISSUE THREAD

**Issue by Nybbler98** [Turing-Complete-Game/Suggestions-and-Issues#274]
### What happened?

The level "Saving Gracefully" is required for me to continue, I saw that it was supposed to be removed from the game but it hasn't and I'm unable to progress until I complete it. 
I made a D-Latch and it operates properly, however the test data is wrong, even including the one tick delay. 
In the test data it shows that the output should change state after a data input change only, which is wrong. }

![image](https://user-images.githubusercontent.com/38850670/151173556-11177053-26cc-4a47-8d64-c3fe3c6d73c7.png)
![image](https://user-images.githubusercontent.com/38850670/151173596-dceec250-639f-4d12-9c85-b5734f166af1.png)

This is very frustrating!

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You are misreading the truth table. The "Desired output" row is correct, it doesn't change. The bottom row is what you are outputting. Your solution changes when just the Value changed.

**Comment by Nybbler98** [comment]
> 

Yeah I see it now, the buffer is screwing me up because it doesn't need to be there in real life or other simulators but the game can't deal with the feedback of the latch without it.
