### ISSUE TITLE
[Bug]: Program counter resets for no apparent reason

### ISSUE THREAD

**Issue by icrss** [Turing-Complete-Game/Suggestions-and-Issues#276]
### What happened?

Completed the computer yesterday and tried the add 5 program this morning. After the 4th instruction of 5, the program counter resets to zero and just loops (even if I remove the connection to the overwrite bit on the program counter so that it can't do anything but increment).

Instructions were:

1. Write 5 to register 0,
2. Copy register 0 to register 1,
3. Copy input to register 2,
4. Add register 1 to register 2, storing in register 3,
5. Copy register 3 to output.

Instructions 1-4 repeat, 5 never happens

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The visual feedback is a bit lacking, but this means that your program is working correctly. There is a trial counter in the bottom right (top of the panel) that increases. I think it's 32 trials.

**Comment by icrss** [comment]
So if I leave it running, the task will eventually pass?

**Comment by icrss** [comment]
Thanks, that was it! Apologies for wasting your time. Great work - I'm an experienced developer, it's actually my daughter playing it as I'm using it to teach her the basics. She's starting a computer science degree in the autumn. Looking forward to seeing where it goes.
