### ISSUE TITLE
[Bug]: Writing "<U1" in the assembler crashes

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#277]
### Discord Thread

https://discord.com/channels/828292123936948244/1293186363335905361

### What happened?

In a blank Asm, trying to write "<U16>" leads to the crash.
```
fatal.nim(54)            sysFatal
Error: unhandled exception: value out of range: -1 notin 0 .. 9223372036854775807 [RangeDefect]
```

### Version

0.1191 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed
