### ISSUE TITLE
[Bug]: Halt doesn't trigger from inside a component

### ISSUE THREAD

**Issue by RicardoLuis0** [Turing-Complete-Game/Suggestions-and-Issues#277]
### What happened?

Halt doesn't trigger when it's inside a component, but the exact same setup _does_ trigger when it's outside a component.
![image](https://user-images.githubusercontent.com/15188209/151268600-1aac3a80-13aa-46f4-9f5c-a086cd54c044.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SuperCraftAlex** [comment]
clock, keyboard and waveform generator also doesnt work inside a custom component
