### ISSUE TITLE
[Bug]: Custom component schematic description clears itself upon editing schematic for it

### ISSUE THREAD

**Issue by nhoffie** [Turing-Complete-Game/Suggestions-and-Issues#278]
### What happened?

Steps to reproduce:

1. Create a new schematic in the component factory
2. Type something in the description box for the schematic
3. Drag a new component onto the schematic
4. Check the description, what was typed is now gone

I would expect that the description for the component would remain even if I heavily edited the component. I use the description for recording which input and output pins do what as well as which instruction codes do what, and I'd to log that information as soon as I create the pins. This isn't possible, however, if the description clears after I edit the schematic because I add the IO pins first.

### Version

Latest

### Operating System

Windows 10 and 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This has been fixed from what I can see
