### ISSUE TITLE
[Bug]: OVERTURE - input does not update on tick

### ISSUE THREAD

**Issue by greendwin** [Turing-Complete-Game/Suggestions-and-Issues#279]
### What happened?

In OVERTURE level Input register is always set to zero.
When I click `STEP` I see an error that `63 is expected at output`. But input is zero.
![image](https://user-images.githubusercontent.com/1989891/151597489-bb9e8e18-ca36-4182-a7a1-3b22a3cdb91a.png)

### Version

Latest

### Operating System

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The input only has a value if you read from it by setting an ON signal to the component on the second pin. If you are doing that, you need to be more specific with a full screenshot of the schematic.

**Comment by greendwin** [comment]
Oh, I see. I didn't get that I should write to these bits. Thanks.
