### ISSUE TITLE
[Bug]: Single On solves Storage Cracker

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#28]
### What happened?

![image](https://user-images.githubusercontent.com/26136419/140895649-89f2f035-ff67-49a1-a044-172420289f74.png)

is a working solution for Storage cracker.

Found by RealOfficalTurf: https://discordapp.com/channels/828292123936948244/851327200736444446/907556797454368770

Related Issues:
#58 
#61 

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
More info from #58 
Same bug but achieved programmatically.
The byte value `1` will ALWAYS solve.

**Comment by bombitmanbomb** [comment]
Pinned Issue. 2 duplicate issues have been posted since.
Elevated issue from Low to Moderate

**Comment by Stuffe** [comment]
fixed next version
