### ISSUE TITLE
[Bug]: The cost of Word XOR & Word XNOR components is hardcoded to constant values

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#280]
### Discord Thread

https://discord.com/channels/828292123936948244/1294229207194537984

### What happened?

The Word XOR and Word XNOR components get unlocked by the Byte XOR level, but their gate/delay costs are hardcoded to 32/3, regardless of how well one solved that level.

### Version

0.1193 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
