### ISSUE TITLE
[Bug]: 3 bit decoder output bits 4-7 don't light up green.

### ISSUE THREAD

**Issue by DylanL826** [Turing-Complete-Game/Suggestions-and-Issues#282]
### What happened?

![image](https://user-images.githubusercontent.com/62712498/151705337-51332923-a1fa-4fe6-b537-fb7634ec3503.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
