### ISSUE TITLE
[Bug]: Missing wire colors

### ISSUE THREAD

**Issue by byte-chan** [Turing-Complete-Game/Suggestions-and-Issues#285]
### What happened?

Whenever a level is (re)loaded, very short wires without animation (but not wire heads) appear in the default color of that wire type. This issue affects all types of wires (bit, byte, 64 bit), except wires not connected to any inputs.
![wire_colors_bad](https://user-images.githubusercontent.com/7152794/151904240-0c023adc-7fdc-464e-9d0d-7d31633b812e.png)
Editing the level restores the correct wire color for the affected wires until the level is reloaded, either by exiting the level or undoing/redoing.
![wire_colors_good](https://user-images.githubusercontent.com/7152794/151904511-1d5daca9-8f77-4086-b981-3c297a9312bd.png)

### Version

Latest

### Operating System

Arch Linux x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed
