### ISSUE TITLE
[Request]: In-game tick rate counter

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#286]
### Request?

Please add an option in settings to enable an in-game FPS/UPS/TPS counter. The three metrics are:
1. Framerate (frames per second)
2. Circuit rendering update rate (updates per second)
3. Simulation speed (ticks per second / Hz)

For example, the display might say `165fps/30ups/1000tps`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
TPS was just added, the two others are wont add for now
