### ISSUE TITLE
[Bug]: `expect` doesn't work in The Lab

### ISSUE THREAD

**Issue by greendwin** [Turing-Complete-Game/Suggestions-and-Issues#287]
### What happened?

I try to write tests, but it seems that watched state is broken. It keep telling that it is not connected.

![image](https://user-images.githubusercontent.com/1989891/152054762-1d2fc283-7e30-4b8c-b463-55b55f829655.png)
![image](https://user-images.githubusercontent.com/1989891/152054849-ca77a15a-8ae4-44b1-8750-1de5c105d112.png)

### Version

Latest

### Operating System

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
