### ISSUE TITLE
[Bug]: Game doesn't launch

### ISSUE THREAD

**Issue by AlexTholen314** [Turing-Complete-Game/Suggestions-and-Issues#288]
### What happened?

I just purchased the game today, and when downloading it off steam and launching it, the game immediately crashes. If I go to the terminal file that runs the game, I get the following error. Reinstalling the game doesn't fix it, and verifying didn't fix it either. I don't know what more to say tbh.

[USERNAME]s-MacBook-Pro ~ % /Users/[USERNAME]/Library/Application\ Support/Steam/steamapps/common/Turing\ Complete/Turing\ Complete.app/Contents/MacOS/Turing\ Complete ; exit;
arguments
0: /Users/[USERNAME]/Library/Application Support/Steam/steamapps/common/Turing Complete/Turing Complete.app/Contents/MacOS/Turing Complete
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Apple M1
OpenGL ES Batching: ON
 
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
ERROR: Can't open dynamic library: /Users/[USERNAME]/Library/Application Support/Steam/steamapps/common/Turing Complete/Turing Complete.app/Contents/MacOS/../Frameworks/libbackend.dylib, error: dlopen(/Users/[USERNAME]/Library/Application Support/Steam/steamapps/common/Turing Complete/Turing Complete.app/Contents/MacOS/../Frameworks/libbackend.dylib, 2): no suitable image found.  Did find:
	/Users/[USERNAME]/Library/Application Support/Steam/steamapps/common/Turing Complete/Turing Complete.app/Contents/MacOS/../Frameworks/libbackend.dylib: mach-o, but wrong architecture
	/Users/[USERNAME]/Library/Application Support/Steam/steamapps/common/Turing Complete/Turing Complete.app/Contents/Frameworks/libbackend.dylib: mach-o, but wrong architecture.
   at: open_dynamic_library (platform/osx/os_osx.mm:1917)
ERROR: No valid library handle, can't get symbol from GDNative object
   at: get_symbol (modules/gdnative/gdnative.cpp:510)
ERROR: No nativescript_init in "res://nim/libbackend.dylib" found
   at: init_library (modules/gdnative/nativescript/nativescript.cpp:1510)
ERROR: Script does not inherit a Node: res://backend.gdns
   at: start (main/main.cpp:1832)
ERROR: No valid library handle, can't terminate GDNative object
   at: terminate (modules/gdnative/gdnative.cpp:417)
zsh: segmentation fault  
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...      12 completed.

### Version

Latest

### Operating System

Mac OS, big sur 11.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexTholen314** [comment]
Okay I just found out that this is a known bug, and that the solution for now is to get the beta. I apologize for the inconvenience, but I look forward to now playing this game.

**Comment by Stuffe** [comment]
No worries. I will get around to officially supporting M1 macs eventually
