### ISSUE TITLE
[Bug]: Click to Pan no longer allows selection of wire ends

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#29]
### Discord Thread

https://discord.com/channels/828292123936948244/1264148825216647239

### What happened?

Previously, clicking a wire end allowed on to quickly move it. This is no longer possible.

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Alt click to move now
