### ISSUE TITLE
[Request]: Rename the demux to decoder

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#29]
### Request?

The demux should be renamed to decoder since that more aptly describes what it does. For those not familiar with the difference, a decoder takes an N bit input with an optional enable/disable bit and outputs a 2^N bit output with only one line on. A demux is similar to a decoder, but a demux takes an N bit input, an M bit input, and an optional enable/disable bit and outputs 2^N M bit inputs with only one M bit output being on and matching the M bit input.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Done

**Comment by EnderShadow** [comment]
Doesn't the other demux need to be renamed as well?
