### ISSUE TITLE
[Request]: Show components on level map

### ISSUE THREAD

**Issue by MadTinkerer** [Turing-Complete-Game/Suggestions-and-Issues#291]
### Request?

Right now the level map is a diagram of green, yellow, and red boxes which only describe what each level is in the upper left hand corner if you mouse over them. It would be helpful if completed levels showed which component you made by completing the level instead of, or overlaid on top of, the nondescript green boxes. Not only would this allow you to see at a glance which level is which, but you would also have a better idea of your overall progress.

The red and yellow boxes can remain as-is, but I just feel like the green boxes by themselves aren't informative enough. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
There are little icons in the corner showing components. Also, when you get further the green boxes get filled in with your score, so there is not really anymore space left for more information
