### ISSUE TITLE
[Bug]: CTD in Wire Spaghetti

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#291]
### Discord Thread

https://discord.com/channels/828292123936948244/1294706644793561170

### What happened?

Crashes on opening Wire Spaghetti, first crash happened after moving the Word AND gate.

Nothing useful appears in either console.

### Version

0.1195 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
Possible duplicate of bug #292

**Comment by Stuffe** [comment]
fixed next patch
