### ISSUE TITLE
[Bug]: Nothing happens when I click "next tick" or "run ticks" on "Arithmetic Engine"

### ISSUE THREAD

**Issue by McMxxCiV** [Turing-Complete-Game/Suggestions-and-Issues#292]
### What happened?

When clicking "next tick" or "run ticks" in the level "Arithmetic Engine", all I get is a error-ish sounding sound, but nothing happens. I can only assume that some condition for running ticks has not been met, but I've rebuilt the schematic two times and it keeps happening.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can you share a screenshot? Also, did you try to create a new schematic?

**Comment by McMxxCiV** [comment]
![image](https://user-images.githubusercontent.com/5289307/152654937-d8a7ab35-4fc4-4bc3-97b2-53b4297a01c4.png)

What exactly do you mean by new schematic? I deleted all components and started anew, but maybe there's a different way?

**Comment by MegaIng** [comment]
Top left, the "switch schematic" button

**Comment by McMxxCiV** [comment]
OK, so that just worked. Thanks. And never mind, clear case of pebkac.
