### ISSUE TITLE
[Request]: Add translation

### ISSUE THREAD

**Issue by Ectalite** [Turing-Complete-Game/Suggestions-and-Issues#293]
### Request?

Hi, 

I would like to help to translate the game in french, because I absolutely love it but I can't share it to friends because they don't speak English as well as me. 
So if you want me to translate your game, you can send me text files to translate. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I have now added a translation channel on Discord and also added a way to use translations in the game with description here: https://github.com/Stuffe/Turing-Complete-Translations.

It would be very cool if you can add some french translations to the game :)
