### ISSUE TITLE
[Bug]: ALPHA: [minor] Component red pins still large

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#295]
### Discord Thread

https://discord.com/channels/828292123936948244/1303065375574986893

### What happened?

CC-generating levels such as Conditions still use the larger version of the pin circle.  The smaller green circle in the generated component seems to align the pin properly so it's not really "broken", just a bit disconcerting.

That said, I seem to recall part of the reason the pins were blown up was to prevent users from placing two of them in the same grid square.  I'd suggest perhaps a better handling of that is to just pop up an error if they try.  That not only gets rid of this odd-looking resize, but starts to inform them of the "rules" when they get to the real CC and start using the smaller circle.

(It'd also be nice to have the CC area view shown like is done in Component Factory, though perhaps should only be done after CF is unlocked.  Maybe I'll make a separate FR for that one!)
![image](https://github.com/user-attachments/assets/7634188d-743e-4b0a-a5e0-27e060d01f26) ![image](https://github.com/user-attachments/assets/1166156d-1a3c-4ce6-9a35-c6c876a4ee0a)

### Version

0.1212 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This is as  intended
