### ISSUE TITLE
[Bug]: ALPHA: [minor] Input and output components use different font.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#296]
### Discord Thread

https://discord.com/channels/828292123936948244/1303098364078063617

### What happened?

This only appears in the CC-generating levels from what I've seen (the green replacement components on the generated CC both use the same font).  I'm guessing it's because input components can have non-numeric text and the other font is "nicer" in that case, but it looks a bit odd for the inputs that do happen to be strictly numeric.
![image](https://github.com/user-attachments/assets/75a8eb6a-863c-4fa4-a4d5-1a2f86067921)

### Version

0.1212 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
