### ISSUE TITLE
[Bug]: Immediate values level stops working after game replaced registers with custom components

### ISSUE THREAD

**Issue by ArchiDevil** [Turing-Complete-Game/Suggestions-and-Issues#297]
### What happened?

I completed Calibrating Laser Cannons level and decided to get back and tweak something in my machine. But when I returned to Turing Machine or Immediate Values levels they are not working anymore, tests with immediate values are failed, but the schematic works perfectly.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArchiDevil** [comment]
Update. The test fails only on 63 value, other values pass successfully. Still don't understand what happens here, 63 is successfully saved into a register and could be used.

**Comment by EnderShadow** [comment]
Someone else ran into this issue. The workaround that worked for them was copying their architecture to a new schematic.

**Comment by ArchiDevil** [comment]
> Someone else ran into this issue. The workaround that worked for them was copying their architecture to a new schematic.

I did it simpler: I just removed all new registers called RegisterPlus, put a new instances of them again and reconnected watched state from program. Now it works, but it still weird why it was broken and a real bug may still be in a game.

**Comment by Stuffe** [comment]
This works now
