### ISSUE TITLE
[Bug]: game crashes

### ISSUE THREAD

**Issue by Tayfun76** [Turing-Complete-Game/Suggestions-and-Issues#299]
### What happened?

The game crashes as soon as I click a particular level on the map (the one left of "double trouble"). I completed it (so it is green) but I can't re-visit it. No error messages, the game simply terminates and has to be restarted.      

### Version

Latest

### Operating System

Win10 Professional

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Does this still happen with the newest version? If yes, upload your save to https://turingcomplete.game/report_bug
