### ISSUE TITLE
[Bug]: CTRL+X doesn't copy

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#3]
### Discord Thread

https://discord.com/channels/828292123936948244/1264181075274367007

### What happened?

When pressing the shortcut for `CUT`, by default `CTRL+X`, the game successfully deletes the selected components, but they don't end up in the clipboard.

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Turing Complete 0.1066 Beta on Windows
ERROR: Failed to invoke Nim procedure update_paste_selection: expected 0-0 arguments, but got 1
   at:  (godotmacros.nim:497) - Failed to invoke Nim procedure update_paste_selection: expected 0-0 arguments, but got 1
ERROR: Failed to invoke Nim procedure show_paste: expected 1-1 arguments, but got 0
   at:  (godotmacros.nim:497) - Failed to invoke Nim procedure show_paste: expected 1-1 arguments, but got 0
```

**Comment by Stuffe** [comment]
fixed next patch
