### ISSUE TITLE
[Request]: Rotate selected components

### ISSUE THREAD

**Issue by tp1212** [Turing-Complete-Game/Suggestions-and-Issues#30]
### Request?

Rotating multiple selected components would make life quite a bit easier I think. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I just finished rotating when pasting and I think that is a better feature so I will close this for now. If perhaps this turns out to also be necessary we can reopen it again later
