### ISSUE TITLE
[Bug]: Sometimes "Current Output" row is all :OFF:

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#30]
### Discord Thread

https://discord.com/channels/828292123936948244/1264147903505764434

### What happened?

This appears to happen every time if you only click the "Run" button and never the "single step" button.

![image](https://github.com/user-attachments/assets/52f45c9c-4bf8-413d-b961-9ce997add734)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by skyhgzsh** [comment]
![20240721224443_1](https://github.com/user-attachments/assets/dcd2e2c9-a31d-414d-b231-adc4b3381e4f)
The "Current Output" row may also have "ON" signals while mismatching with "Desired Output".

In 0.1069 Beta On Windows 11

**Comment by Stuffe** [comment]
fixed next patch
