### ISSUE TITLE
[Bug]: Stacked Crates in Level "SPACIAL INVASION"

### ISSUE THREAD

**Issue by marthilda** [Turing-Complete-Game/Suggestions-and-Issues#303]
### What happened?

Hallo,

in Programming/Spacial Invasion the second crate from the left appears to be two crates stacked in one place. If you push from below it becomes 2 crates, while the robot while sit on top of one of the crates.

If you shot the stacked crates, only one will be destroyed and you cant move onto the field, but the input is set to 239 ( Debris ), thus my Programm gets stuck. 

Version 0.509 Beta
![grafik](https://user-images.githubusercontent.com/35460762/153724622-999ba14e-d152-401d-bf5f-9f98b0d7f9f1.png)

![grafik](https://user-images.githubusercontent.com/35460762/153724605-4ec35f73-e895-40d3-804b-a008667c5ade.png)

### Version

Other

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed in dev
