### ISSUE TITLE
[Bug]: Crash on level "Push and Pop (add stack)" if writing to output without reading first

### ISSUE THREAD

**Issue by evindor** [Turing-Complete-Game/Suggestions-and-Issues#305]
### What happened?

Writing any value to output causes the game to crash on this level. Can reproduce with this simple circuit. If you first read from the input then it's ok.

<img width="451" alt="Screenshot 2022-02-15 at 00 07 14" src="https://user-images.githubusercontent.com/822951/153954848-d332edf1-0d0c-49df-82dc-bc1eeba395ea.png">

### Version

Latest

### Operating System

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed in 0.651
