### ISSUE TITLE
[Bug]: Clicking 'Profile' in Main Menu Crashes Game

### ISSUE THREAD

**Issue by alexloomis** [Turing-Complete-Game/Suggestions-and-Issues#306]
### What happened?

Clicking 'Profile' in the main menu causes the game to freeze indefinitely.

### Version

Latest

### Operating System

Linux Mint

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is probably because the game tries to sync all your solution and that takes a long time if a lot of your solutions weren't correctly synced before. This is hard to confirm.

**Comment by Stuffe** [comment]
fixed
