### ISSUE TITLE
[Request]: Custom sized 'big' gates

### ISSUE THREAD

**Issue by tp1212** [Turing-Complete-Game/Suggestions-and-Issues#31]
### Request?

I'd like it to be possible to have 'big' gates be resizable by just enlarging an existing gate arbitrarily, maybe with a little pip button.
Like so: 
![image](https://user-images.githubusercontent.com/5463108/140976233-804b45b2-66b4-4a82-a2f4-239558a044dd.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think this is a bit too feature creepy
