### ISSUE TITLE
[Bug]: ALPHA: Performance of "Run fast" in "Odd number of signals"

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#31]
### Discord Thread

https://discord.com/channels/828292123936948244/1264155688318406757

### What happened?

Maybe not a bug, but strange: Clicking "Run fast" in the level "Odd Number Of Signals" takes more time that on other levels (over a second) and is slower than the "normal" run button, that we had before.

Edit: Ok, that happens on other levels too (like double trouble). I guess the UI can't keep up with the speed

![image](https://github.com/user-attachments/assets/8b96b9f4-f8b7-4031-b731-db1eb39e77ee)

(Reported by UnsignedRobin on Discord)

### Version

0.1064 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
