### ISSUE TITLE
[Bug]: Wire animation disappears after pressing undo (ctrl + z)

### ISSUE THREAD

**Issue by jsutterfield** [Turing-Complete-Game/Suggestions-and-Issues#313]
### What happened?

A bug occurs when I use undo (ctrl + z) to remove a wire that I just connected to a live wire. The wire animation from that live wire disappears. Additionally, if the wire which I deleted via undo was connected to a component, that connection point stays green as if a live wire were connected to it.

See video for reproduction. When the wire disappears, that's me pressing ctrl + z

https://user-images.githubusercontent.com/1657792/154770127-e3fd0a76-249d-4453-8950-744b62036fc4.mp4

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed
