### ISSUE TITLE
[Bug]: Using undo on memory components crashes game to desktop

### ISSUE THREAD

**Issue by jsutterfield** [Turing-Complete-Game/Suggestions-and-Issues#314]
### What happened?

When using undo (ctrl + z) on any of the memory components it causes the game to crash to desktop. So far I've only acquired the "Register", "1 Bit memory", and "Delay Line", so it's possible the problem is specific only to those 3, but my hunch is it affects all memory components in the game.

Below is a video of my reproducing the issue. You can see me moving batches of components and then undoing the move with ctrl + z. You'll see I'm able to move and then undo all the bit components. Same for the  byte components. But when I move and undo the memory components, the game crashes. I've tested them individually, it happens for all of them. It also happens if I include any 1 of those memory components in a batch that I'm trying to move. That's demonstrated, at the end of the video.

https://user-images.githubusercontent.com/1657792/154792844-c3937060-8b6d-4c5a-9472-a2f492a2041c.mp4

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next patch. Thanks for the thorough description.

**Comment by jsutterfield** [comment]
Awesome. Thank you!
