### ISSUE TITLE
[Bug]: Wire comments disappear after undo

### ISSUE THREAD

**Issue by jsutterfield** [Turing-Complete-Game/Suggestions-and-Issues#315]
### What happened?

If you move a wire which has a comment and then undo the move using ctrl + z, the wire comment disappears. I don't believe it's deleted since if I leave the level and re-enter I see the wire comment again. But the comments are gone until I leave and enter. See video for reproduction.

https://user-images.githubusercontent.com/1657792/154862411-ea7efee3-716b-491f-a72a-b1edb21e87fe.mp4

p.s. Thanks for fixing that bug where undoing a memory component would crash the game. That issue has gone away in the latest version.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarximusMaximus** [comment]
Lost all my comments on a build. Ooops. >_<;;;;

**Comment by MarximusMaximus** [comment]
Oh! If I exit my schematic (e.g. go to level select) and go back in, all my comments came back!

**Comment by Stuffe** [comment]
Fixed
