### ISSUE TITLE
[Bug]: wire spaghetti description typo

### ISSUE THREAD

**Issue by izik1** [Turing-Complete-Game/Suggestions-and-Issues#315]
### Discord Thread

https://discord.com/channels/828292123936948244/1312213186593689600/1312213186593689600

### What happened?

> 3. Click "Edit link components" on the program component and connect registers to 0 to 6. Connect input / r0put to 7.
`r0put` -> `output` (seems like a find+replace error)

find-able in `campaign/symphony_1_or/meta.txt` (also occurs in `campaign/symphony_1_io/meta.txt`, line 19 in both files).

OS: Linux (6.11.5-xanmod1), NixOS (nightly)

(I know this is a very minor bug lol, not dying to get a fix implemented right away, more writing it down for when priorities allow)

### Version

(alpha) 0.1234

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
Fixed
