### ISSUE TITLE
[Bug]: Overture Assembly uses Incorrect ALU opcodes

### ISSUE THREAD

**Issue by jasondyoungberg** [Turing-Complete-Game/Suggestions-and-Issues#316]
### Discord Thread

https://discord.com/channels/828292123936948244/1312311870664740925

### What happened?

The ALU levels say: `nand` `or` `and` `nor`
But the assembly says: `or` `nand` `nor` `and`

![Screenshot 2024-11-29 235313](https://github.com/user-attachments/assets/209ea9a0-07b5-46eb-93c8-bd38db746f67)
![Screenshot 2024-11-29 235244](https://github.com/user-attachments/assets/36093f74-c07e-454b-8f66-117d282a8bc6)

### Version

0.1234 beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
It was fixed, but the game might have copied the old version of the spec.isa so you would need to update it manually
