### ISSUE TITLE
[Bug]: Toggling bits in the bottom drawer is out of sync with bits in top left. Has strange, broken behavior

### ISSUE THREAD

**Issue by jsutterfield** [Turing-Complete-Game/Suggestions-and-Issues#316]
### What happened?

Sorry for the onslaught of bug reports, but I've encountered another one which is annoying and a bit strange.

When toggling bits in the bottom drawer view of a component (the one you get when you click on it), the text which communicates the meaning of those bits isn't updated. E.g., toggling a bit to make the input mean calculate < 0, or toggling another bit to have it calculate = 0. The text on the component in the schematic updates, but not the text in the drawer.

Additionally, updating the bits via the UI in the top left doesn't sync with updating the bits in the drawer. However, if you update the bits in the drawer, it _does_ update the bits in the top left. Finally, if you click away from the component (in order to close the drawer) and then click it again (to re-open it), it will show the proper text and bits. That seems to re-sync it.

Here's a video demonstrating the behavior:

https://user-images.githubusercontent.com/1657792/154863183-f2e39eca-03e4-43fc-ac80-8b7f6f038442.mp4

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
