### ISSUE TITLE
[Bug]: Arithmetic Engine

### ISSUE THREAD

**Issue by coredmp95** [Turing-Complete-Game/Suggestions-and-Issues#317]
### What happened?

After i finish the "Logic Engine" i switch to "Arithmetic Engine" with the previous schematic ( from Logic Engine) and at this point a red message is printed on the bottom saying "This save is from an obsolete version of this level. Create and load a new shcematic in the schematic menu." 

I cannot lauch the validation process.

I try to delete all and restart .. still this message

I have try on Dev version, same error

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You need to create a new schematic by using the menu in the top left. You can use `CTRL+A`, `CTRL+C`, `CTRL+V` to copy over
