### ISSUE TITLE
[Request]: Multiple types of waveform generation: sine, triangle, square, noise

### ISSUE THREAD

**Issue by MarximusMaximus** [Turing-Complete-Game/Suggestions-and-Issues#318]
### Request?

The audio systems of some retro computers had multiple types of waveform generators, for example, the NES had two square wave generators, one triangle wave generator, and one noise generator (although some carts added more sound channels for the Famicom b/c it could mix in additional channels of audio, this was dropped for the NES release).

Noise channel input could just be the different types of noise (white noise, brown noise, pink noise, etc) or a pitch and a +/- range to generate the noise within.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
A new more powerful audio component was added. Actually the default sounds are sampled from the NES
