### ISSUE TITLE
[Bug]: Can't place new ASM components in sandbox

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#318]
### Discord Thread

https://discord.com/channels/828292123936948244/1312403601632530494

### What happened?

The ASM component doesn't appear in the component menu and when I try to copy it from a schematic which already has it, I can't place it. 
Also when I try to scroll the ASM component in said schematic, the game crashes.

(`Add 5 Again` has not been completed.)

### Version

0.1234 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
