### ISSUE TITLE
[Bug]: [ALPHA] Dragging ghost components leaves input pins behind

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#321]
### Discord Thread

https://discord.com/channels/828292123936948244/1313986940693123082

### What happened?

I'm just going through replacing my delay lines, registers, etc with the newer sized ones and noticed that they seem to leave their input pins behind when I move them (output pins work fine).  The pins appear to be attached while dragging, but as soon as the (now deghosted) component is dropped, they disappear.  Performing any other circuit update (adding an unrelated wire, for example) seems to fix it up, as does leaving the level and re-entering, so I assume it's just a minor display issue.

Also, after being placed the register pins show red for a couple of seconds before turning yellow.  In this case the "fix" seems to happen on it's own (no circuit update required - just wait a few seconds and its fine).
![image](https://github.com/user-attachments/assets/a2786690-f051-43c9-93c9-51833d0666f5)

### Version

0.1236 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
