### ISSUE TITLE
[Bug]: Mismatch between Factory and Sandbox

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#324]
### Discord Thread

https://discord.com/channels/828292123936948244/1315194518802399383

### What happened?

This circuit behaves differently in the Component Factory and the Sandbox.
If CF it outputs `0xfffffd` (4 bytes), as expected, but while testing in Sandbox it outputs `0x00fffffd` (3 bytes).
![image](https://github.com/user-attachments/assets/0b4c1fad-1f9a-4c7d-afce-6346f256dc93)
![image](https://github.com/user-attachments/assets/7540ff6e-73c9-451e-bfa9-641ecbf9de76)

### Version

0.1237 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This was fixed
