### ISSUE TITLE
[Bug]: Tower of Alloy never reaches height of 5 due to bug in `test.si`

### ISSUE THREAD

**Issue by blubberdiblub** [Turing-Complete-Game/Suggestions-and-Issues#325]
### Discord Thread

https://discord.com/channels/828292123936948244/1316359662538588210

### What happened?

The test cases will only ever have heights of 3 (max disc no. 2) or 4 (max disc no. 3), but never 5 (max disc no. 4).

Evidence for why this is unintentional:

- The description speaks of the maximum disc number being between 2 and 4 (which corresponds to the three possible heights 3, 4 or 5).
- There is an image `4.png` for disc 4 that never shows up in the current version
- `ui.txt` specifies discs 0 through to 4
- `test.si` has several places showing that up to 5 discs where meant to make up the tower

The primary problem is that `test.si` uses `3 + random(2)`. With the upper bound being exclusive, this only yields numbers 0 and 1, resulting in the two heights 3 and 4, missing 5.
It should use `3 + random(3)` instead:

```diff
--- campaign/tower/test.si.orig	2024-12-11 11:12:37.650545244 +0100
+++ campaign/tower/test.si	2024-12-11 11:31:08.625341999 +0100
@@ -189,7 +189,7 @@
 
     let source  = random(3)
     var destination = source
-    let height = 3 + random(2)
+    let height = 3 + random(3)
 
     while source == destination {
 
```

This allows a height of 5, however, it also triggers a follow-up bug where the successful move of a tower of height 5 is never detected making the test run forever. This is due to a slightly faulty completion detection in `test.si`, which can be fixed in many possible ways.

I chose to fix it like this:

```diff
@@ -251,9 +251,7 @@
         let pos = scratch_space[PLATES + i]
         if pos == -1 {
 
-            return win
-
-            target
+            pass
 
         } elif pos != target {
 
@@ -265,4 +263,10 @@
 
     }
 
+    if i >= 5 {
+
+        return win
+
+    }
+
 }
```

### Version

0.1245 Beta

### What OSes are you seeing the problem on?

Windows, Linux

**Comment by Stuffe** [comment]
This is fixed next patch, thanks for the solution!
