### ISSUE TITLE
[Request]: 64-bit RAM that only has 256 addressable locations and does not have a load delay.

### ISSUE THREAD

**Issue by MarximusMaximus** [Turing-Complete-Game/Suggestions-and-Issues#326]
### Request?

For the transitionary gameplay where a player is upgrading from 8-bit to 16-, 32-, or 64-bit, it would be extremely helpful to have a version of the 64-bit RAM that functions like the 8-bit RAM. It took me a while to notice that the large 64-bit RAM had a load delay and the regular did not.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Yes I agree. I think there will be different versions of the 64 bit ram. They will have different delay score vs tick cost trade offs

**Comment by MarximusMaximus** [comment]
Sounds awesome. Looking forward to it. :-)
