### ISSUE TITLE
[Bug]: ALU not in build menu

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#328]
### Discord Thread

https://discord.com/channels/828292123936948244/1316900000583913482

### What happened?

I've completed `Symphony ALU` but when I enter the level `Integrating ALU` no ALU is present in the build menu.

If the CC is invalid for some reason then the level `Symphony ALU` tests should fail with some error message about the problem.

This is different from bug #60 as the CC is created; it's visible and openable in the factory, and placeable in sandbox, just not the level.

### Version

0.1247 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
