### ISSUE TITLE
[Bug]: Errors in the "Symphony Register" level log

### ISSUE THREAD

**Issue by FoxSlyme** [Turing-Complete-Game/Suggestions-and-Issues#329]
### Discord Thread

https://discord.com/channels/828292123936948244/1317237260697211014

### What happened?

In the level log for "Symphony Register" there are several errors:
1) There's no closing parenthesis after the opening one, and no period. The sentence just abruptly ends.
2) "seen" is misspelled as "soon".
![image](https://github.com/user-attachments/assets/d932c940-8f45-4328-bb00-4f8047e45ee9)

### Version

0.1250 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
