### ISSUE TITLE
[Bug]: After single-stepping, "run fast" does not seem to work.

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#33]
### Discord Thread

https://discord.com/channels/828292123936948244/1264213186496692335

### What happened?

I click run fast, which starts running. Then I click single-step, which does a single step. Then I click run fast again, which does another single step.

If I wait a while and then click single-step, it does a single step - it hasn't been running in the background and just not updating the UI.

If I alt-tab out of the game and then wait, it eventually starts running. I haven't seen it start running again without tabbing out of the game (though admittedly I'm not very patient, so it may just be that I needed to wait even longer). 

(Reported by Jabor on Discord, I've guessed the version and OS)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
Oreo confirms Windows.
Seen in sandbox.

**Comment by Stuffe** [comment]
This was due to a hidden short circuit I think

**Comment by technod999** [comment]
This was closed, but the issue is still around
the bug is that it re-runs from zero, up until where you simulated it from, even in an empty circuit

https://github.com/user-attachments/assets/791fed60-8aee-4fd4-be0a-d45f69c8b075
