### ISSUE TITLE
[Bug]: Leaderboard is not updating

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#33]
### What happened?

The leaderboard is not updating.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Yeah, Stuffe is aware of this. IIRC this is because the page is getting reworked.

**Comment by bombitmanbomb** [comment]
Related to #25 
Reason for Bug: Site Rework

@Stuffe Leaving open for now to prevent duplicates.

**Comment by MegaIng** [comment]
@Stuffe This is not really fixed, There are still levels (especially some architecture levels) that don't update.
