### ISSUE TITLE
[Bug]: RAM has unexpected behavior when accessing it with address + byte width > byte size

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#330]
### Discord Thread

https://discord.com/channels/828292123936948244/1317451439706210344

### What happened?

When you try and read from a RAM or FAST RAM component and the address + byte width is larger than the memory capacity, memory accesses go to address num_bytes - width_bytes.

For powers of 2 memory sizes, the expected behavior would be for it to wrap around at the beginning. For non-power of 2 sizes, there's no clear behavior for what should happen, but I think
- padding it with 0 up to a power of 2 and then wrapping around or
- just wrapping around would be fine.

The first option is less computationally expensive since you just use an AND mask, but would require allocating more memory than requested if it's not a power of 2. The second option doesn't require allocating extra memory, but does require using the modulus operator for wraparound which would slow down the simulation.

### Version

0.1251 save_breaker

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch

**Comment by EnderShadow** [comment]
This issue is still present in 0.1271

**Comment by EnderShadow** [comment]
This is still preset in 0.1344 when (FAST) RAM is set to little endian
