### ISSUE TITLE
[Bug]: Crash on drawing wire: Variable not in scope

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#331]
### Discord Thread

https://discord.com/channels/828292123936948244/1318227359198875829

### What happened?

Drawing and connected the wire (show in light blue) crashes with
```
Variable [34mz984[0m not in scope.
[31m(5785)[0m
            .level_output[2] = <U64> ((<U16> (([31mz984[0m != 0 ? <U64> (<U1> v984) : <U64> Z_STATE))))
```
Happens in the level `IO`

![image](https://github.com/user-attachments/assets/11b848cc-63fc-4c18-bd7a-b666245e2e40)

### Version

0.1265 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
