### ISSUE TITLE
[Bug]: Custom components involving registers not working properly

### ISSUE THREAD

**Issue by timotheetallon** [Turing-Complete-Game/Suggestions-and-Issues#331]
### What happened?

v 0.549 beta

Two things:
1. In the 'Turing complete' level, the RegisterPlus components don't display the saved value. However the value seems to be saved correctly as all tests pass.
2. In the 'Wire Spaghetti' level, any custom component involving registers doesn't work (Tested with a RegisterPlus and some other custom component with two outputs). However, a single register component saves and displays the value correctly. Tested through the first test case (add the input twice) and by hardwiring constant values.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
For 1: You need to add a Watched State component inside the `RegisterPlus` component and connect it to the register. Your ``RegisterPlus`` component was probably created before this existed.

For 2: Doesn't work: purely visual or does it actually not have a value?
