### ISSUE TITLE
[Bug]:  Strange error in Score sync

### ISSUE THREAD

**Issue by itay-grudev** [Turing-Complete-Game/Suggestions-and-Issues#336]
### What happened?

When attempting to sync my score I encountered the following error:

![image](https://user-images.githubusercontent.com/2123767/155862464-743dca60-f4d6-432a-9abd-1b9ce482a13d.png).

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Finally fixed this
