### ISSUE TITLE
[Bug]: Auto Pass

### ISSUE THREAD

**Issue by Arineke** [Turing-Complete-Game/Suggestions-and-Issues#337]
### What happened?

When you undo and then and then run(full or tick doesn't matter) it automatically passes that level

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I can't reproduce this. Can you share a video?

**Comment by Arineke** [comment]
Hello

After trying to reproduce the bug it only worked on previously passed
levels, it seem sto only happen in cpu 2

This video was of the final level of cpu 2, conditionals, i hope this will
help you.

Op wo 2 mrt. 2022 15:28 schreef MegaIng ***@***.***>:
