### ISSUE TITLE
[Request]: Add "Set Input for next read" instruction to TheLab

### ISSUE THREAD

**Issue by Frisch12** [Turing-Complete-Game/Suggestions-and-Issues#338]
### Request?

It would be nice to have a instruction like "input 10" that will set the input to the value provided for the next read to test if the input reading is working correctly. Furthermore it would be nice to have this for all watched values.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The `set_input <number>` instruction exists, is however a bit unreliable at the moment.
