### ISSUE TITLE
[Bug]: Adding Bytes tests are flawed

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#34]
### Discord Thread

https://discord.com/channels/828292123936948244/1264222586624147511

### What happened?

The carry input and the first bit of the top input are always the same.

```
def get_input($inputs: [Int], tick: Int){
    var x = tick
    x ^= x << 7
    x ^= x >> 9
    x ^= x << 8
    inputs[0] = x & 0xff
    inputs[1] = (x >> 8) & 0xff
    inputs[2] = x & 1
}
```

This means that quite a number of (accidently) incorrect circuits will work.

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
