### ISSUE TITLE
[Bug]: Naming custom components with the name of a standard component makes the standard component unpickable

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#34]
### What happened?

Steps to reproduce (Using the MUX component as an example):

1. Create a custom component with any name and place a MUX in it.
2. Set it's nesting level to 2.
2. Create a custom component named "Mux", possibly with any capitalization.
3. Restart the game.
4. Go to the component you created in step 1.
5. The vanilla MUX is missing from the bytes menu.

### Version

Development

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I can not reproduce this on windows 10. Might be OS specific.

**Comment by Stuffe** [comment]
fixed in 0.290
