### ISSUE TITLE
[Bug]: Watch states malfunction in custom components

### ISSUE THREAD

**Issue by timotheetallon** [Turing-Complete-Game/Suggestions-and-Issues#340]
### What happened?

v 0.561 beta

When using a custom component involving one or several Watch State components (e.g. the RegisterPlus component, or a custom component with a RAM and Stack component):
1) The display in top of the component is locked on 0 and never updated, even when the value in the register or memory is updated.
2) I can not link the Watch states from my program to the component's slot. When I try, the link is simply not created, but in the program editor, the watched states appears to exists even though it is never updated.

The tested components work correctly, and they all contain the relevant watch state components that are correctly linked to the relevant slots. In the component factory, the Watch State Components' displays are correctly updated when the register's value is updated.

This only happens with custom components. When using directly the Register component, I can link the program's watch state to the register's slot.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
