### ISSUE TITLE
[Bug]: "Conditionals" might have mismatched testcase and test program

### ISSUE THREAD

**Issue by Deveritas** [Turing-Complete-Game/Suggestions-and-Issues#341]
### What happened?

While playing "Conditionals", the final level in CPU Architecture II, there seems to be a mismatch between the testcase and the test program.
Notice that byte 3 is 1, but the test case is looking at REG0.
![Screenshot 2022-03-02 211850](https://user-images.githubusercontent.com/3656594/156501494-d16f5f5e-1d27-4ba0-8628-348a69937315.png)
 

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
