### ISSUE TITLE
[Bug]: Crashes when "Show in menu" is unchecked on RegisterPlus

### ISSUE THREAD

**Issue by Garek33** [Turing-Complete-Game/Suggestions-and-Issues#346]
### What happened?

I have everything but the final levels unlocked.
The game reliably crashes when I:

1. Go to the Lab
2. Go to the Component Factory
3. Go to switch Schematic
4. Change into the Folder "Old" I put a lot of schematics in
5. Select RegisterPlus
6. Try to uncheck "Show in menu"

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Garek33** [comment]
Also, the Numbers are broken in the Menu, but correct (80 / 14) in the component factory and don't seem to break architecture totals.
![grafik](https://user-images.githubusercontent.com/6023983/157511192-732b2a31-a44b-4912-98b7-62df9542c42b.png)

**Comment by Stuffe** [comment]
fixed
