### ISSUE TITLE
Crash on early OVERTURE levels

### ISSUE THREAD

**Issue by sona13asatryan** [Turing-Complete-Game/Suggestions-and-Issues#348]
### What happened?

A bug happened! I can't test the level Calculation and program crashes. Same is with the level Registers (I don't know what I've done wrong but I have the same scheme in both levels). When I move by ticks, few ticks work and only then the game crashes.
Also when I run the Arithmetic engine level and click continue, Components factory opens automatically. 

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pinkii-** [comment]
Is it happening to me too. Levels Registers was fine until I reached level Calculations, then when testing the level Calculations it crashes sometimes on the third step, some times later. Then trying to play Registers, as it has the same components, it crashes too

**Comment by Stuffe** [comment]
This has been fixed in the latest release
