### ISSUE TITLE
[Bug]: OVERTURE red register's always output doesn't work

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#35]
### Discord Thread

https://discord.com/channels/828292123936948244/1264155101971480576

### What happened?

Image shows my attempt to connect to it. It seems to still be solid as if it was a register body.
![image](https://github.com/user-attachments/assets/a86a79bc-789a-4173-b39f-d5977f110bdb)

### Version

0.1067

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think this was fixed
