### ISSUE TITLE
[Request]: Use subfolder with SteamID for savegame

### ISSUE THREAD

**Issue by C0ntroller** [Turing-Complete-Game/Suggestions-and-Issues#350]
### Request?

On my machine multiple steam accounts are used by me and other persons. We share our games via family share. 

But for this game it's problematic as the save is stored in the Windows-users appdata folder. As only the Steam user and not the Windows user changes the appdata folder and the save game is the same. 

Just using a subfolder with the SteamID for the save would eliminate this problem as for every user another subfolder is created. If there's no ID available it could fallback to "default" or anything like that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
this would be done through profiles, which is very low priority still and has another open issue, so I will close this one
