### ISSUE TITLE
[Bug]: Missing Inputs on Counting Signals.

### ISSUE THREAD

**Issue by Scimon** [Turing-Complete-Game/Suggestions-and-Issues#351]
### What happened?

I've been bouncing around a few levels trying them out and copying and pasting some bits from one to the other.
Somewhere along the way I appear to have deleted the Input Register for Counting Signals and there doesn't seem to be any way to replace it. 

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Scimon** [comment]
https://turingcomplete.game/profile/20848 : Game profile.

**Comment by MegaIng** [comment]
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

**Comment by Stuffe** [comment]
Fixed

**Comment by NigelHiggs30** [comment]
I tried the solution didn't fix my predicament.
