### ISSUE TITLE
[Bug]: Logic engine page is empty.

### ISSUE THREAD

**Issue by ellamanukyan** [Turing-Complete-Game/Suggestions-and-Issues#353]
### What happened?

![photo_2022-03-14_13-00-53](https://user-images.githubusercontent.com/70705614/158138903-b150b4d8-ef27-4ade-834f-b655ff2cfbfd.jpg)

### Version

Latest

### Operating System

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Create a new schematic via the menu in the top left.

**Comment by ellamanukyan** [comment]
> Create a new schematic via the menu in the top left.

thank you, it works

**Comment by MegaIng** [comment]
Duplicate of #351
