### ISSUE TITLE
[Bug]: Condition level doesn't give input.

### ISSUE THREAD

**Issue by aristakesyanl** [Turing-Complete-Game/Suggestions-and-Issues#355]
### What happened?

Condition level doesn't give any inputs.
![Screenshot_3](https://user-images.githubusercontent.com/60519263/158169223-0669a432-c209-4910-b60c-d1ca25d2fbc6.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Duplicate of #351

Create a new schematic via the menu in the top left.
