### ISSUE TITLE
[Bug]: Missing inputs at level half adders

### ISSUE THREAD

**Issue by AgentAlopex** [Turing-Complete-Game/Suggestions-and-Issues#356]
Did not fix even after reinstalled.
![Screenshot (68)](https://user-images.githubusercontent.com/101688286/158513979-fd2af7dc-cb17-46fa-8878-b6992c75f51f.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Duplicate of #351 , create a new schematic.
