### ISSUE TITLE
no input [Bug]: 

### ISSUE THREAD

**Issue by Liuphillip** [Turing-Complete-Game/Suggestions-and-Issues#357]
### What happened?

in the level "odd number of signals" there is no input

### Version

Latest

### Operating System

windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351
