### ISSUE TITLE
[Bug]: 'node_has_breakpoint' Crash on entering the program editor in "Spacial Invasion"

### ISSUE THREAD

**Issue by Fabbi** [Turing-Complete-Game/Suggestions-and-Issues#358]
### What happened?

In the level "Spacial Invasion" the game crashes on entering the program editor.

The log says: 
> Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Apple M1
OpenGL ES Batching: ON
>
> Turing Complete 0.588 Beta on OSX
> ERROR: Failed to invoke Nim procedure node_has_breakpoint: a range error has occurred when converting argument 0 of Godot type Int
>   at:  (godotmacros.nim:241) - Failed to invoke Nim procedure node_has_breakpoint: a range error has occurred when converting argument 0 of Godot type Int

Creating a new schematic and copying every file except the `circuit.data` seems to work. 

In the level before that I had the issue that some breakpoints just won't trigger but I had no breakpoints in the editor before proceeding.

### Version

Development

### Operating System

MacOS Monterey 12.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arnaud-carre** [comment]
I have the exact same issue, 100% repro crash as soon as I click on "Edit Memory" button in "Calibrating Laser Cannons" level. Log:

Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Graphics 6100
OpenGL ES Batching: ON
 
WARNING: No small icon found, reusing 150x150 @32768 icon!
   at: OS_Windows::set_native_icon (platform\windows\os_windows.cpp:2968) - No small icon found, reusing 150x150 @32768 icon!
Turing Complete 0.592 Beta on Windows
ERROR: Failed to invoke Nim procedure node_has_breakpoint: a range error has occurred when converting argument 0 of Godot type Int
   at:  (godotmacros.nim:241) - Failed to invoke Nim procedure node_has_breakpoint: a range error has occurred when converting argument 0 of Godot type Int

**Comment by BLucky-gh** [comment]
Same issue here, calibrating cannons level, crash as soon as I try to open assembly editor. I'm on MacOS btw

**Comment by Stuffe** [comment]
this was fixed
