### ISSUE TITLE
[Bug]: Crash/level reset while drag deleting

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#36]
### What happened?

I think this is the bug that was so mysterious and experienced by a lot of players in the last few days. It happens when having something selected, and then using RMB+drag to delete Stuff.

When with the first click you target empty area or a component, the level just reloads. While annoying, this is the better option.

When with the first click targeting a wire, the game completely crashes.

I tried to record it, but I can't get my mouse cursor to be also captured.

- First two reloads are targeting nothing
- 3 and 4 are targeting the components
- The final one is targeting one of the wires.

After each click it only crashes when you then drag the mouse.

https://user-images.githubusercontent.com/26136419/141368453-31b761c4-838b-4674-9569-32111a16182c.mp4

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed!
