### ISSUE TITLE
[Bug]: ALPHA: Wire-Pins can no longer be double clicked

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#36]
### Discord Thread

https://discord.com/channels/828292123936948244/1264239100362494043

### What happened?

Double clicking a pin on a wire no longer selects it

![image](https://github.com/user-attachments/assets/b562e270-5112-461d-8aaf-2ff310431f00)

(Reported by UnsignedRobin on Discord)

### Version

0.1067

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
