### ISSUE TITLE
[Bug]: REGISTERS - missing "Input value"

### ISSUE THREAD

**Issue by kryoclasm** [Turing-Complete-Game/Suggestions-and-Issues#361]
### What happened?

On the Registers level, you need both the "Code input", for addressing locations and the "Input Value" that needs to be copied. 

On the side bar, only a single Input byte is shown, this containing the addressing. There should be a second Input byte that contains the value to be copied. 

On the play field, only the "address input" and "value output" is visible.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351
