### ISSUE TITLE
[Bug]: Level "Byte Constant" does not have an output node

### ISSUE THREAD

**Issue by Potato2357** [Turing-Complete-Game/Suggestions-and-Issues#362]
### What happened?

 The level "Byte Constant" does not have an output node, resulting in the game crashing when running the next ticks.

### Version

Latest

### Operating System

macOS Monterey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351
