### ISSUE TITLE
[Bug]: Crash when 'Run ticks' or 'Next tick' in Counter and Little box

### ISSUE THREAD

**Issue by pancanin** [Turing-Complete-Game/Suggestions-and-Issues#363]
### What happened?

I was solving Counter and the first time I tried to run ticks it just crashed - window closed, no errors or anything.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Do you have 3 red input/output components in the level?

**Comment by pancanin** [comment]
There are 2 red components in Little box and 1 in Counter.

**Comment by MegaIng** [comment]
Then this is a duplicate of #351 

Create a new schematic, make sure to switch to it. The IO should now be there.

**Comment by pancanin** [comment]
Ah yes, that's does it. Thanks!
