### ISSUE TITLE
[Request]: False Circular dependency?

### ISSUE THREAD

**Issue by NexusCubed** [Turing-Complete-Game/Suggestions-and-Issues#364]
### Request?

I discovered a way to get circular dependency without actual circular dependency, not sure if this is intentional or not, but I'm not smart enough to work around it.
<img width="383" alt="circular dependency without circular dependency" src="https://user-images.githubusercontent.com/45430861/159156417-19c40063-0f07-437c-a6d8-79be48bbb83d.PNG">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is a circular dependency. The top switch connects left to right, the bottom right to left. Just because you know that the two switches can't be activate at the same time does not mean that it's not a circular dependency.

**Comment by NexusCubed** [comment]
> 

Shouldn't it be allowed if I know it will never loop?
Or is my circuit just unproffesional?

**Comment by MegaIng** [comment]
It should be allowed if it is incredible obvious on a per component basis that it's not a loop, which is not the case here.

How to fixes this really depends on what you actually want. For example, adding byte buffers to limit the data flow might already be enough.

**Comment by NexusCubed** [comment]
I'm sorry, I am not sure what you mean.

I'm on the level "Registers", so I felt the need to loop the circuit to let the registers save to other registers
<img width="462" alt="solution" src="https://user-images.githubusercontent.com/45430861/159157777-872214eb-8135-4717-a188-1dbc2e826ecf.PNG">
I thought it would be a clever solution, and I'm confident it would work, but it won't let me run it, and I'm not sure how to get around this without labourious circuits.

**Comment by MegaIng** [comment]
Just remove the two switches. You don't need them at all.

**Comment by NexusCubed** [comment]
thank you
