### ISSUE TITLE
[Bug]: unable to start Turing complete on a m1 pro macbook pro

### ISSUE THREAD

**Issue by us0906** [Turing-Complete-Game/Suggestions-and-Issues#368]
### What happened?

As soon, I start the game on my m1 pro macbook pro it crashes.

### Version

Latest

### Operating System

macOS Monterey 12.3 m1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oshyshkin** [comment]
Any updates? I have the same issue.

**Comment by Fabbi** [comment]
you need to either set the game to launch with Rosetta or tell steam to load the "m1 version" (under Betas)

**Comment by oshyshkin** [comment]
> tell steam to load the "m1 version" 

I don't see any other option than just "Install". Should I write to the Steam team?

> set the game to launch with Rosetta
What do I need to do for this? I'm not sure what steps I need to perform.

**Comment by Fabbi** [comment]
> > tell steam to load the "m1 version"
> 
> I don't see any other option than just "Install". Should I write to the Steam team?

right click on the game > properties > beta > m1

> > set the game to launch with Rosetta
> 
> What do I need to do for this? I'm not sure what steps I need to perform.

right click on the game > show files in Finder > right click on "Touring Complete.app" > "Get Info" > turn on Rosetta

**Comment by oshyshkin** [comment]
It does work, thanks!
