### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Usagi19** [Turing-Complete-Game/Suggestions-and-Issues#369]
### What happened?

The program component will sometimes not load bytes properly (i.e. it won't output at all). I've found that deleting and replacing this component fixes the issue temporarily.
Also, when there are 2 program components placed, only one of them will ever load an instruction/byte. I have 2 because I want to load 2 instructions at a time for a 16-bit system and it is only possible to load 1 byte at a time with this component. I haven't tested this problem with the ram component but I suspect it could have similar issues.

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
