### ISSUE TITLE
[Bug]: ALPHA: unable to start on linux with older glibc version

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#37]
### Discord Thread

https://discord.com/channels/828292123936948244/1264243838357213244

### What happened?

it looks similar to https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/11 ⁠but it is different.

After installing gnome-terminal i get two interesting messages in there:
./simulator: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by ./simulator)
./simulator: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34' not found (required by ./simulator)

my libc version is 2.31 (i'm on mint 20.3, which is based on ubuntu 20.04 and probably won't be updating it in the near future because university)

It might work if similator is compiled on a system with glibc <= 2.31 for me.

on ubuntu you can see the glibc version by checking the package version of libc6, for example via apt show libc6

Also it looks like simulator is the only file that needs that glibc version, the output of ldd for libbackend.so, libsteam_api.so, and Turing Complete.x86_64 does not contain these two messages.

(Reported by McModknower on Discord)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
im compiling on ubuntu 20 from now on
