### ISSUE TITLE
[Request]: Use actual names to help learners

### ISSUE THREAD

**Issue by Xopher40** [Turing-Complete-Game/Suggestions-and-Issues#370]
### Request?

As the title states. 
it is made difficult to learn the name of components when we learn about them but the name is never called out. 
For example, "Input Selector". Are we creating a multiplexer here?
Having fun / funny / creative names for challenges is fun, but doesn't help educate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The components you get from the level should always have the correct name.
