### ISSUE TITLE
[Bug]: Watched state watcher doesn't watch

### ISSUE THREAD

**Issue by BLucky-gh** [Turing-Complete-Game/Suggestions-and-Issues#378]
### What happened?

The values in watched state are always 0

In the screenshot below you can see reg0 has 7 in it, but the watcher says 0

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/41377306/160611125-e7e9ed6e-b6c7-48ce-9980-e8c729cd5275.png">

### Version

Latest

### Operating System

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
