### ISSUE TITLE
[Bug]: ALPHA: Cannot colour byte wires

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#38]
### Discord Thread

https://discord.com/channels/828292123936948244/1264255977482485781

### What happened?

Drawing a wire from an 8-bit pin draws a wire that is shown in the default blueish colour, regardless of the colour UI setting.
Painting an existing byte (with CLT-F, or CTRL-E) wire appears to do nothing.
Using the colour picker (CTRL-R) on a wire I attempted to paint picks up the colour, so it looks like the display is ignoring the colour for the moment.

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
