### ISSUE TITLE
[Bug]: Program component is filled with zeros on the first test in levels that don't allow editing program component

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#38]
### What happened?

In levels like Program you can't edit the program memory. Instead the test suit is supposed to do so for you. But it only does so when you try to run the circuit once on zeroed out program component (which fails the test in most cases), and press the Reset button. Afterwards the tests can be passed without any issues.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can reproduce.

**Comment by Stuffe** [comment]
I believe this is fixed now as of 0.297, feel free to reopen if not
