### ISSUE TITLE
[Bug]: Adding Bytes - 175 + 146 test

### ISSUE THREAD

**Issue by xaviermonin** [Turing-Complete-Game/Suggestions-and-Issues#383]
### What happened?

Hi,

I found an error on Adding bytes test.

175d + 146d = 321d = 101000001b = 1 carry and 01000001b = 1 carry and 65d.

But the test assert 1 carry and 66d.

![image](https://user-images.githubusercontent.com/5740369/161399146-c226ce05-0898-41f5-be48-22fe81a6e646.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You are ignoring the carry in
