### ISSUE TITLE
[Bug]: Little Box level does not work on Linux

### ISSUE THREAD

**Issue by streifenfrei** [Turing-Complete-Game/Suggestions-and-Issues#384]
### What happened?

The little box level (see screenshot) seems not to work on Linux. It just fails the first test right away. **On Windows 10 though it runs just fine**. I also tried different solutions. All with the same result.
![little box](https://user-images.githubusercontent.com/18353470/161795872-524b476c-b9b7-40f8-b340-a81ed6f9d563.png)

### Version

Latest

### Operating System

Ubuntu 20.04

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This should now be fixed already.
