### ISSUE TITLE
[Bug]: Achievement "3 Adder Multiply" is unlocked with a design using many adders

### ISSUE THREAD

**Issue by mikecat** [Turing-Complete-Game/Suggestions-and-Issues#385]
### What happened?

The achievement "3 Adder Multiply", which should be unlocked only if the level is solved using no more than 3 adders, is unlocked with my solution that uses 11 Full Adder components and 1 half adder built with logic gates.

<details><summary>Here is my solution</summary><div>

![tc-multiply-20220406](https://user-images.githubusercontent.com/6667599/161976339-6f5bb7fd-db4b-4c75-88b9-9cfd003a149f.png)

</div></details>

Game version: 0.648 Beta

### Version

Other

### Operating System

Windows 10 Home x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
What is meant here is 3 byte adders, as the more naive version uses 7 or 8 byte adders. What you describe here is an even more optimized solution than the 3 byte adder one, so it still deserves this achievement. I will change the description though
