### ISSUE TITLE
[Bug]: Achievement "Symmetric ALU" is not unlockable?

### ISSUE THREAD

**Issue by mikecat** [Turing-Complete-Game/Suggestions-and-Issues#388]
### What happened?

I solved the level "Logic Engine" using only components in "8BIT" category, but the achievement "Symmetric ALU" is not unlocked.

The achievement says:

> Complete the "Logic Engine" level using only components from the "BYTES" category

There looks no "BYTES" category in the level in current version, so is the achievement impossible to unlock now?

<details><summary>My solution (has less (better) score than my previous solution using components from BIT category)</summary><div>

![tc-logic-engine-20220408](https://user-images.githubusercontent.com/6667599/162417456-16e783b6-6e0f-44f6-b6b5-78ba9eded9ba.png)

</div></details>

Game version: 0.652 Beta

### Version

Other

### Operating System

Windows 10 Home x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I believe this has now been fixed. If you are still not able to get the achievement please upload your save here so I can test the specific schematic: https://turingcomplete.game/report_bug
