### ISSUE TITLE
[Bug]: Achievement "Condition 10" is not unlocked even after solving "Conditions" with 10 components

### ISSUE THREAD

**Issue by mikecat** [Turing-Complete-Game/Suggestions-and-Issues#389]
### What happened?

I solved the level "Conditions" with 10 components, but the achievement "Condition 10" is not unlocked.

<details><summary>My solution</summary><div>

![tc-conditions-20220408](https://user-images.githubusercontent.com/6667599/162420239-7bcbea6e-cbc2-44ab-b2d0-423e8d47accd.png)

</div></details>

Game version: 0.652 Beta

### Version

Other

### Operating System

Windows 10 Home x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This has been fixed
