### ISSUE TITLE
[Bug]: "Instructions" Menu not accessible

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#39]
### Discord Thread

https://discord.com/channels/828292123936948244/1264237064770293842

### What happened?

Clicking the instructions menu throws the attached error

![image](https://github.com/user-attachments/assets/649d8bbf-c371-4b67-ae1c-e5e0597e826e)
![image](https://github.com/user-attachments/assets/0017b3bd-0695-415d-a283-3bfbc41835f5)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
