### ISSUE TITLE
[Bug]: Program module in level Add 5 outputs as if it's filled with zeroes, until you edit the memory in some way

### ISSUE THREAD

**Issue by SunCatMC** [Turing-Complete-Game/Suggestions-and-Issues#39]
### What happened?

If you have the program saved from the last time you were doing this level, it is visible on the Program component (as expected). But these values have no bearing on actual output of the component, until you edit memory of the module.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SunCatMC** [comment]
i remember that this was reported a while ago on discord, but I added it in GitHub for completeness sake

**Comment by MegaIng** [comment]
I would assume all three issues you just opened #37 , #38 , #39 are the same bug.

**Comment by SunCatMC** [comment]
i didn't open #37, but yeah, that a reasonable assumption to make

**Comment by MegaIng** [comment]
Sorry, no for some reason I thought you opened three issues. I don't think 37 is a dupe.

**Comment by EnderShadow** [comment]
Yeah, 37 is a completely different issue

**Comment by Stuffe** [comment]
fixed in 0.297
