### ISSUE TITLE
[Bug]: Planet Names level: text scroll on the screen

### ISSUE THREAD

**Issue by ViridiCanis** [Turing-Complete-Game/Suggestions-and-Issues#394]
### What happened?

In the level `Planet Names` the displayed text on the screen/in the assembly editor is offset by too much as the text scrolls
![output](https://user-images.githubusercontent.com/49595344/162626212-b01413d1-ed74-4a95-bb55-26b14b9b5f52.gif)

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
