### ISSUE TITLE
[Bug]: Latest Turing Complete Version Won't Run on Linux or Mac

### ISSUE THREAD

**Issue by DarthMalloc** [Turing-Complete-Game/Suggestions-and-Issues#395]
### What happened?

After the latest update, when I try to run Turing Complete through Steam on my Linux Mint 19.3 machine, the game won't start. The game window opens for a second, and then quickly closes. When I try to run on my Mac, something similar happens, except that there is no window.

### Version

Latest

### Operating System

Linux Mint 19.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Upload your save folder here please: https://turingcomplete.game/report_bug
