### ISSUE TITLE
[Bug]: Inconsistent behavior of input-setting menus

### ISSUE THREAD

**Issue by MavethGH** [Turing-Complete-Game/Suggestions-and-Issues#396]
### What happened?

This is easiest to describe through screenshots. 
![2022-04-11_12-39](https://user-images.githubusercontent.com/65792235/162797998-1c204869-4c1f-4cfe-a595-49497a640dee.png)
![2022-04-11_12-41](https://user-images.githubusercontent.com/65792235/162798422-5130ced7-ffc1-4621-910f-b03824bb45ce.png)
As you can see, when the input bits are set through the bottom menu, the desired input is not sent through the wire. However, when using the top left menu to set the inputs, it works as expected. This issue is present on the levels 'Registers' and 'Logic Engine', and likely others.

### Version

Latest

### Operating System

Linux (Kubuntu 21.04)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed
