### ISSUE TITLE
[Bug]: ALPHA: Sandbox crash Intel 8008

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#4]
### Discord Thread

https://discord.com/channels/828292123936948244/1264156359935524874

### What happened?

Loading my copy of Intel 8008 in the sandbox crashed the game, now it crashes on every start up.
I'll come back to this later, I've reset my save to a known good state.

### Version

0.1064 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by BenjaminSchaaf** [comment]
Had the same thing loading my risc-v CPU: https://github.com/BenjaminSchaaf/turning-complete-riscv

**Comment by Gelthir** [comment]
This schematic no longer crashes on version 0.1081.
