### ISSUE TITLE
[Bug]: Pixel display does not decode blue correctly

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#40]
### Discord Thread

https://discord.com/channels/828292123936948244/1264258915630317640

### What happened?

blue channel color in the RRRGGGBB format isn't displayed correctly. There are only two values of blue available, instead of four
also attached is red, for what it should look like

![image](https://github.com/user-attachments/assets/9b785543-fa06-4b66-b868-b7e1d6a51be1)
![image](https://github.com/user-attachments/assets/34b99eb2-dfb1-4543-9381-7187083a660d)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
