### ISSUE TITLE
[Request]: Please don't get disappointed with old schematics of Logic Engine

### ISSUE THREAD

**Issue by mikecat** [Turing-Complete-Game/Suggestions-and-Issues#400]
### Request?

When I re-ran one of my schematics I created before in the "Logic Engine" level, this message appeared:

> Some of the components used are not supposed to be
> available in this level!
> The solution is not scored.
> And we are all very disappointed.

<details><summary>My schematics and the message</summary><div>

![20220415195032_1](https://user-images.githubusercontent.com/6667599/163562713-6201cccd-89e2-4bbf-b27f-2ce4f0fe6f4b.jpg)

</div></details>

After a while, I found that the NAND component is replaced with the OR component, and successfully completed this level again using OR component.

However, I had a bad impression with the message because I felt like the message is meaning "You cheated, didn't you?" while I was just trying my old schematics I lawfully created in the past.

Instead of being told that you are disappointed with old schematics, I prefer to see an "This save is from an obsolete version of this level." message like one used in the "Saving Bytes" level.

![20220415195842_1](https://user-images.githubusercontent.com/6667599/163563260-14f54ebb-3b08-4316-adf4-c2bceda5c84b.jpg)

Game version: 0.668 Beta  
OS: Windows 10 Home x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
That comment was meant for people who edit their saves to get components in levels before they should, but in this case you see it because the level budget changed. I guess this will could happen from time to time so I will remove the last line
