### ISSUE TITLE
[Bug]: Red components in the "Logic Engine" level is movable while they are said not

### ISSUE THREAD

**Issue by mikecat** [Turing-Complete-Game/Suggestions-and-Issues#401]
### What happened?

The "Logic Engine" level has this description:

> Also you can't move the red components in this level

However, the red components are normally movable.

Solutions looks like still can be accepted after moving red components.

[Video that demonstrates this issue](https://user-images.githubusercontent.com/6667599/163580998-c4ab4d63-2219-4cf8-a9ee-a0b140ddb946.mp4)

Game version: 0.669 Beta

### Version

Other

### Operating System

Windows 10 Home x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is only a problem if you are revisiting the level later on.
