### ISSUE TITLE
[Bug]: Correct answer not working 

### ISSUE THREAD

**Issue by aristakesyanl** [Turing-Complete-Game/Suggestions-and-Issues#403]
### What happened?

My correct answer which passed all tests is now getting a short circuit issue after some possible updates.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Beginning of this months the rule for the game changed, free OR was removed, see https://turingcompelte.game/blog

**Comment by aristakesyanl** [comment]
> Beginning of this months the rule for the game changed, free OR was removed, see https://turingcompelte.game/blog

Link is not working

**Comment by MegaIng** [comment]
Typo in URL https://turingcomplete.game/blog
