### ISSUE TITLE
[Bug]: Correct answer not working

### ISSUE THREAD

**Issue by aristakesyanl** [Turing-Complete-Game/Suggestions-and-Issues#405]
### What happened?

In the CPU Architecture level after updates, I receive error message when the architecture is working fine.
It says next tick counter will be 0, which should be 4, while the command is to rewrite counter if reg3=0, which is true.

![Screenshot_6](https://user-images.githubusercontent.com/60519263/164071708-a8ced5cf-bdc9-4ca5-86ff-5a6cf7efc14a.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
What does your counter look like when getting this error message?

**Comment by aristakesyanl** [comment]
Counter value is zero.
![Screenshot_8](https://user-images.githubusercontent.com/60519263/164080956-876c0a5a-7331-4b23-8762-6aff6947f62a.png)

**Comment by MegaIng** [comment]
Yes exactly, you are overwriting it despite not being supposed to do that. I can't tell exactly what you are doing wrong, but the counter should not be overridden with the value 0 here.
