### ISSUE TITLE
[Bug]: 16-bit maker has wrong description

### ISSUE THREAD

**Issue by ripSquid** [Turing-Complete-Game/Suggestions-and-Issues#409]
### What happened?

![image](https://user-images.githubusercontent.com/44409107/164537697-a827e26b-362c-451a-b12b-f25c81a9832a.png)
The 16-bit maker has a description which isn't actually what it does.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ripSquid** [comment]
I think this might be a correct description. Although it seems weirdly written either way.

**Comment by Stuffe** [comment]
Fixed in the next patch
