### ISSUE TITLE
[Bug]: ALPHA: Word Delay has small input pin

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#41]
### Discord Thread

https://discord.com/channels/828292123936948244/1264282781320740936

### What happened?

The word delay component has a small (bit) input pin, unlike the word register.
This is cosmetic, it works fine.

![image](https://github.com/user-attachments/assets/08f1140f-cebf-418b-9644-e7e3afd1f240)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
