### ISSUE TITLE
[Request]: Display custom component in folder / tree structure in menu.

### ISSUE THREAD

**Issue by drsmile1001** [Turing-Complete-Game/Suggestions-and-Issues#41]
### Request?

While costom component increasing, It hard to find which I want.
![圖片](https://user-images.githubusercontent.com/11384864/141679861-7368e2d4-33e4-45e2-b410-773d0a991458.png)

And name of component is hard to identify, maybe show it's name under icon?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
this is on the roadmap for sure. As a short term fix you might be able to use the new hide feature to remove some of the clutter

**Comment by Cereal4Dinner** [comment]
The directory structure is a big help sorting custom components, but I agree that it is hard to identify without hovering the mouse. But that just goes to the fact the the component names are hard to read, whether they're in the menu or on the board. Maybe you need options for colors, which would also help the color blind people. (And option for which direction for component name to print so I don't have to turn my component design sideways)

**Comment by Stuffe** [comment]
The folder based menu system has now been implemented
