### ISSUE TITLE
[Bug]: 64-bit counter only increments 1 at a time even with custom increment size

### ISSUE THREAD

**Issue by ripSquid** [Turing-Complete-Game/Suggestions-and-Issues#410]
### What happened?

As the title says. When you use a 64-bit counter and you have set the increment size to something other than 1 it still only increments by 1 each tick.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is fixed in the newest version
