### ISSUE TITLE
[Bug]: The file rom outputs bytes in the wrong order.

### ISSUE THREAD

**Issue by ripSquid** [Turing-Complete-Game/Suggestions-and-Issues#411]
### What happened?

The highest byte becomes the lowest byte when it comes out of the File ROM. So when it reads 8 bytes it must flip the order of them somewhere. 

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I am doubtful that this is the case, I do no modifications of the index number before loading bytes. However, the program you are externally editing the file in is probably little endian
