### ISSUE TITLE
[Bug]:  switch schematic sidebar doesn't update correctly

### ISSUE THREAD

**Issue by Cereal4Dinner** [Turing-Complete-Game/Suggestions-and-Issues#412]
### What happened?

A bug happened!
1. When renaming a schematic, the sidebar with its info doesn't update the name until selected again.

2. When a schematics gate/delay score changes due to a contained components score change, the sidebar doesn't update until it's saved again (I move a component, then move back. Seems to cause a save). Seems like the level map scores do get updated now, keeping an eye on it.

### Version

Latest

### Operating System

win11pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
this was fixed
