### ISSUE TITLE
[Bug]: crash after deleting current schematic

### ISSUE THREAD

**Issue by Cereal4Dinner** [Turing-Complete-Game/Suggestions-and-Issues#413]
### What happened?

A bug happened!
Copied a schematic, double clicked to edit, opened switch schematic, deleted currently editing schematic, closed switch schematic, moved a component, crash...
Maybe it should open the Default schematic or create a new Default if it doesn't exist. (seems a schematic must be open)

### Version

Latest

### Operating System

win11pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think this happened specifically when deleting an open schematic and then changing away from it. That bug has been fixed
