### ISSUE TITLE
[Bug]: Helperbot achievement not issued

### ISSUE THREAD

**Issue by Cereal4Dinner** [Turing-Complete-Game/Suggestions-and-Issues#414]
### What happened?

A bug happened!
It's been a while since I've finished the game and yet the helperbot achievement is still locked.

### Version

Latest

### Operating System

win11pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You don't get it for the normal levels, you need to explore a little.

**Comment by Cereal4Dinner** [comment]
Thanks, I'll look more
