### ISSUE TITLE
[Bug]: Level "One Way" should work with a "Switch" and not with a logic gate

### ISSUE THREAD

**Issue by pitti98** [Turing-Complete-Game/Suggestions-and-Issues#418]
### What happened?

I understand that this level is supposed to teach you bus arbitration, i.e. not to drive the bus (= Hi-Z) when someone else is driving it. Normal logic gates always drive their outputs, whether it is high or low, true or false, and the one component that was introduced as an exception is the "Switch" component, and so it should be the component of choice for this level. And yet the game tells me there is a contention when I use a switch.

1. A normal AND/OR/NOT gate works when it shouldn't. It should always drive its output and so there should be a conflict during test #3, when there even is visible flow into its output which is clearly a contention.
2. A switch does not work. At test #2, where it is SUPPOSED to drive the output, the game complains about a contention (and calls it "short circuit") when there should not be one.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next patch
