### ISSUE TITLE
[Bug]: Invalid Component control leads to crash

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#42]
### What happened?

When at the same pressing left and right mouse button to select a component the moment you delete it, the component will be gone, but it's control at the bottom still appears. For most component without anything interactive at the bottom that is irrelevant. However, for components like Constant and Counter interacting with what is displayed leads to this:

![image](https://user-images.githubusercontent.com/26136419/141681724-b9d23e56-a9e5-4dfb-9ced-64ae91e8aff7.png)

And if you change the value of IO from the component factory in this mode(e.g. change value of components that don't exist), it crashes.

Also, the overlay doesn't disappear when exiting to level select:

![image](https://user-images.githubusercontent.com/26136419/141681860-c11dcae1-cdac-4e94-9cd8-755dc6b0bd3f.png)

And sometimes get's overlapped with other stuff that wants to be displayed down there:

![image](https://user-images.githubusercontent.com/26136419/141681883-d943a4b8-b715-45c4-a13b-1a2e7fec6cc6.png)
 

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
