### ISSUE TITLE
[Bug]: Crashes at start (macOS Monterey 12.3.1)

### ISSUE THREAD

**Issue by koermiz** [Turing-Complete-Game/Suggestions-and-Issues#422]
### What happened?

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Turing Complete [2780]
Path:                  /Users/USER/Library/Application Support/Steam/*/Turing Complete.app/Contents/MacOS/Turing Complete
Identifier:            TuringComplete
Version:               1.0 (1.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-04-28 15:16:54.7915 +0200
OS Version:            macOS 12.3.1 (21E258)
Report Version:        12
Anonymous UUID:        ADAB7B25-251F-411D-F14E-A74A3F7B49EB

Time Awake Since Boot: 11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [2780]

VM Region Info: 0x10 is not in any region.  Bytes before following region: 4331306992
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1022a8000-104388000    [ 32.9M] r-x/r-x SM=COW  ...ring Complete

Application Specific Information:
dyld4 config: DYLD_LIBRARY_PATH= DYLD_INSERT_LIBRARIES=/Users/tobiaskirmes/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamloader.dylib:/Users/tobiaskirmes/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/gameoverlayrenderer.dylib

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed:: MainThrd Dispatch queue: com.apple.main-thread
0   Turing Complete               	       0x10397eda0 Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) + 176
1   Turing Complete               	       0x10248bfac GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) + 29620
2   Turing Complete               	       0x10245c0a0 GDScript::_create_instance(Variant const**, int, Object*, bool, Variant::CallError&) + 436

Thread 1:
0   libsystem_pthread.dylib       	       0x1a2779078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1a2779078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1a2779078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1a2779078 start_wqthread + 0

Thread 5:
0   libsystem_kernel.dylib        	       0x1a2744290 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1a277e83c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1a26cd230 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Turing Complete               	       0x103ad5504 _IP_ResolverPrivate::_thread_function(void*) + 132
4   libsystem_pthread.dylib       	       0x1a277908c thread_start + 8

Thread 6:
0   libsystem_kernel.dylib        	       0x1a2744290 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1a277e83c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1a26cd230 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Turing Complete               	       0x1036e49a0 VisualServerScene::_gi_probe_bake_thread() + 152
4   libsystem_pthread.dylib       	       0x1a277908c thread_start + 8

Thread 7:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x1a274090c semaphore_wait_trap + 8
1   caulk                         	       0x1ab1d2a2c caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1ab1b677c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1ab1b639c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x1a277e26c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1a277908c thread_start + 8

Thread 8:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x1a27408d0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1a2740d40 mach_msg + 76
2   CoreAudio                     	       0x1a448aa40 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 104
3   CoreAudio                     	       0x1a4317cd0 HALC_ProxyIOContext::IOWorkLoop() + 3396
4   CoreAudio                     	       0x1a4316990 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 100
5   CoreAudio                     	       0x1a44e2e60 HALB_IOThread::Entry(void*) + 88
6   libsystem_pthread.dylib       	       0x1a277e26c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1a277908c thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000150376aa8   x1: 0x0000600001a607e8   x2: 0x000000016db560a8   x3: 0x0000000000000001
    x4: 0x000000016db56060   x5: 0x000000016db561c8   x6: 0x0000000000000000   x7: 0x00000001a273a7a0
    x8: 0x00006000035fac10   x9: 0x0000000000000010  x10: 0x0000000000000018  x11: 0x0000000000000000
   x12: 0x0000000150376aa8  x13: 0x0000000000000000  x14: 0x00000000f353af53  x15: 0x0000000000b6ba86
   x16: 0x000000000000b6ba  x17: 0x000000000000b6ba  x18: 0x0000000000000000  x19: 0x000000016db56060
   x20: 0x000000016db561c8  x21: 0x0000000000000001  x22: 0x0000000150376aa8  x23: 0x0000600001a607e8
   x24: 0x00000001040bbb36  x25: 0x0000000000000001  x26: 0x0000000000000095  x27: 0x000000016db56060
   x28: 0x0000000104018882   fp: 0x000000016db56380   lr: 0x000000010248bfac
    sp: 0x000000016db55fc0   pc: 0x000000010397eda0 cpsr: 0x80001000
   far: 0x0000000000000010  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1022a8000 -        0x104387fff TuringComplete (1.0) <3c927619-3594-3039-a89e-72d08cdc110f> /Users/USER/Library/Application Support/Steam/*/Turing Complete.app/Contents/MacOS/Turing Complete
       0x1a2777000 -        0x1a2783fff libsystem_pthread.dylib (*) <cee8bc77-6923-34d9-89a3-6f8f7279605e> /usr/lib/system/libsystem_pthread.dylib
       0x1a273f000 -        0x1a2776fff libsystem_kernel.dylib (*) <1d7b3b8e-75a1-34ea-aa52-9f7c23155c55> /usr/lib/system/libsystem_kernel.dylib
       0x1a26c0000 -        0x1a2726fff libc++.1.dylib (*) <06bc1ec0-9992-398e-a85b-2973eb1fdba2> /usr/lib/libc++.1.dylib
       0x1ab1b4000 -        0x1ab1dafff com.apple.audio.caulk (1.0) <23d0d7ce-cb87-35f3-9c15-943bd8f6645a> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x1a4156000 -        0x1a4878fff com.apple.audio.CoreAudio (5.0) <51dd4b50-d2b2-31e7-acae-f662748a2d2b> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=893.5M resident=0K(0%) swapped_out_or_unallocated=893.5M(100%)
Writable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 6464K       12 
ColorSync                          544K       24 
CoreAnimation                       16K        1 
CoreGraphics                        64K        4 
CoreUI image data                  240K        2 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           334.4M       56 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         832.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                       11.5M       51 
VM_ALLOCATE (reserved)              16K        1         reserved VM address space (unallocated)
__AUTH                            1913K      183 
__AUTH_CONST                      11.4M      346 
__DATA                            8828K      340 
__DATA_CONST                      12.1M      355 
__DATA_DIRTY                       744K      119 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       592.3M       12 
__OBJC_CONST                      1606K      152 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3152K        1 
__TEXT                           301.2M      372 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                       81.2M       21 
shared memory                     18.6M       19 
===========                     =======  ======= 
TOTAL                              2.7G     2121 
TOTAL, minus reserved VM space     1.5G     2121 

-----------
Full Report
-----------

{"app_name":"Turing Complete","timestamp":"2022-04-28 15:16:54.00 +0200","app_version":"1.0","slice_uuid":"3c927619-3594-3039-a89e-72d08cdc110f","build_version":"1.0","platform":1,"bundleID":"TuringComplete","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"600EAD20-6EAC-4D38-8485-96BB294EB01C","name":"Turing Complete"}
{
  "uptime" : 11000,
  "procLaunch" : "2022-04-28 15:16:52.7060 +0200",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 279501281410,
  "coalitionID" : 1936,
  "osVersion" : {
    "train" : "macOS 12.3.1",
    "build" : "21E258",
    "releaseType" : "User"
  },
  "captureTime" : "2022-04-28 15:16:54.7915 +0200",
  "incident" : "600EAD20-6EAC-4D38-8485-96BB294EB01C",
  "bug_type" : "309",
  "pid" : 2780,
  "procExitAbsTime" : 279550926268,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Turing Complete",
  "procPath" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/Turing Complete.app\/Contents\/MacOS\/Turing Complete",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1.0","CFBundleIdentifier":"TuringComplete"},
  "storeInfo" : {"deviceIdentifierForVendor":"D45E2212-8E2B-5000-AAB4-7C2176287B8C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "TuringComplete",
  "crashReporterKey" : "ADAB7B25-251F-411D-F14E-A74A3F7B49EB",
  "sip" : "enabled",
  "vmRegionInfo" : "0x10 is not in any region.  Bytes before following region: 4331306992\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1022a8000-104388000    [ 32.9M] r-x\/r-x SM=COW  ...ring Complete",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000010","rawCodes":[1,16],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000010"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":2780},
  "ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n",
  "vmregioninfo" : "0x10 is not in any region.  Bytes before following region: 4331306992\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      1022a8000-104388000    [ 32.9M] r-x\/r-x SM=COW  ...ring Complete",
  "asi" : {"dyld":["dyld4 config: DYLD_LIBRARY_PATH= DYLD_INSERT_LIBRARIES=\/Users\/tobiaskirmes\/Library\/Application Support\/Steam\/Steam.AppBundle\/Steam\/Contents\/MacOS\/steamloader.dylib:\/Users\/tobiaskirmes\/Library\/Application Support\/Steam\/Steam.AppBundle\/Steam\/Contents\/MacOS\/gameoverlayrenderer.dylib"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":106070,"threadState":{"x":[{"value":5640776360},{"value":105553143924712},{"value":6135570600},{"value":1},{"value":6135570528},{"value":6135570888},{"value":0},{"value":7020455840,"symbolLocation":0,"symbol":"__cxxabiv1::__class_type_info::search_above_dst(__cxxabiv1::__dynamic_cast_info*, void const*, void const*, int, bool) const"},{"value":105553172868112},{"value":16},{"value":24},{"value":0},{"value":5640776360},{"value":0},{"value":4082347859},{"value":11975302},{"value":46778},{"value":46778},{"value":0},{"value":6135570528},{"value":6135570888},{"value":1},{"value":5640776360},{"value":105553143924712},{"value":4362844982,"symbolLocation":436866,"symbol":"png_formatted_warning.valid_parameters"},{"value":1},{"value":149},{"value":6135570528},{"value":4362176642}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4333289388},"cpsr":{"value":2147487744},"fp":{"value":6135571328},"sp":{"value":6135570368},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4355255712,"matchesCrashFrame":1},"far":{"value":16}},"name":"MainThrd","queue":"com.apple.main-thread","frames":[{"imageOffset":23948704,"symbol":"Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&)","symbolLocation":176,"imageIndex":0},{"imageOffset":1982380,"symbol":"GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*)","symbolLocation":29620,"imageIndex":0},{"imageOffset":1786016,"symbol":"GDScript::_create_instance(Variant const**, int, Object*, bool, Variant::CallError&)","symbolLocation":436,"imageIndex":0}]},{"id":106079,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":106080,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":106084,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":106087,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":106107,"frames":[{"imageOffset":21136,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30780,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":1},{"imageOffset":53808,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":28,"imageIndex":3},{"imageOffset":25351428,"symbol":"_IP_ResolverPrivate::_thread_function(void*)","symbolLocation":132,"imageIndex":0},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":106111,"frames":[{"imageOffset":21136,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30780,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":1},{"imageOffset":53808,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":28,"imageIndex":3},{"imageOffset":21219744,"symbol":"VisualServerScene::_gi_probe_bake_thread()","symbolLocation":152,"imageIndex":0},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":106113,"name":"AMCP Logging Spool","frames":[{"imageOffset":6412,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":2},{"imageOffset":125484,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":4},{"imageOffset":10108,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":4},{"imageOffset":9116,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":4},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":106139,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":6352,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":2},{"imageOffset":7488,"symbol":"mach_msg","symbolLocation":76,"imageIndex":2},{"imageOffset":3361344,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":104,"imageIndex":5},{"imageOffset":1842384,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3396,"imageIndex":5},{"imageOffset":1837456,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":100,"imageIndex":5},{"imageOffset":3722848,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":88,"imageIndex":5},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331307008,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "TuringComplete",
    "size" : 34471936,
    "uuid" : "3c927619-3594-3039-a89e-72d08cdc110f",
    "path" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/Turing Complete.app\/Contents\/MacOS\/Turing Complete",
    "name" : "Turing Complete",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7020703744,
    "size" : 53248,
    "uuid" : "cee8bc77-6923-34d9-89a3-6f8f7279605e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7020474368,
    "size" : 229376,
    "uuid" : "1d7b3b8e-75a1-34ea-aa52-9f7c23155c55",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7019954176,
    "size" : 421888,
    "uuid" : "06bc1ec0-9992-398e-a85b-2973eb1fdba2",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7165657088,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 159744,
    "uuid" : "23d0d7ce-cb87-35f3-9c15-943bd8f6645a",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7047831552,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7483392,
    "uuid" : "51dd4b50-d2b2-31e7-acae-f662748a2d2b",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7017414656,
  "size" : 3136438272,
  "uuid" : "1df3dfc1-141a-35d0-a4e5-f1e113894c6e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=893.5M resident=0K(0%) swapped_out_or_unallocated=893.5M(100%)\nWritable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 6464K       12 \nColorSync                          544K       24 \nCoreAnimation                       16K        1 \nCoreGraphics                        64K        4 \nCoreUI image data                  240K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           334.4M       56 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         832.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.1M        9 \nStack                             12.2M        9 \nVM_ALLOCATE                       11.5M       51 \nVM_ALLOCATE (reserved)              16K        1         reserved VM address space (unallocated)\n__AUTH                            1913K      183 \n__AUTH_CONST                      11.4M      346 \n__DATA                            8828K      340 \n__DATA_CONST                      12.1M      355 \n__DATA_DIRTY                       744K      119 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       592.3M       12 \n__OBJC_CONST                      1606K      152 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           301.2M      372 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                       81.2M       21 \nshared memory                     18.6M       19 \n===========                     =======  ======= \nTOTAL                              2.7G     2121 \nTOTAL, minus reserved VM space     1.5G     2121 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "MainThrd",
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000139
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "625de77818a7dd465be99423"
      },
      "deploymentId" : 240000109
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 7459.101.3, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Display: PMOS321-IQC, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Display: Sidecar Display, 2576 x 1892, MirrorOff
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Feb  8 2022 01:51:44 version 20.90.39.0.8.7.114 FWID 01-510a2aee
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet Adapter (en4), Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB2.1 Hub
USB Device: Komplete Audio 6
USB Device: Razer Kiyo
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

### Version

Latest

### Operating System

macOS Monterey 12.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
The newest version of the game now supports ARM macs
