### ISSUE TITLE
[Bug]: Memory probes only work at a limited depth

### ISSUE THREAD

**Issue by alien-valkyrie** [Turing-Complete-Game/Suggestions-and-Issues#423]
### Problem description
When using custom components (from the component factory) inside custom components, memory probes stop working beyond two-ish levels, always showing a value of 0.

### Context where this is a major problem
I was factoring out groups of processor registers into sub-components in order to reduce bloat in my main architecture, and in order to more easily add more registers later. This bug causes register contents to no longer show up in the program editor's watched state, and subsequently causes the automated tests to fail.

### Steps to reproduce
- Create a custom component called "Inner" that wraps an 8-bit memory component, consisting of:
  - the central 8-bit memory component
  - a 1-bit input called "Load", connected to the memory's "Load" input
  - a 1-bit input called "Save", connected to the memory's "Save" input
  - an 8-bit input called "Save value", connected to the memory's "Save value" input
  - an 8-bit tristate output called "Output", connected to the memory's "Output" output and enabled by the "Load" input
  - a memory probe, connected to the memory's contents
- (Optional) With the "Inner" component opened in the Component Factory, test that
  - it saves and loads values correctly
  - the memory probe shows its current value
- Create a custom component called "Middle" that wraps an "Inner" component the same way the "Inner" component wraps an 8-bit memory component
- (Optional) With the "Middle" component opened in the Component Factory, test that
  - it saves and loads values correctly
  - the value saved in the "Inner" component is displayed correctly on that component
  - the "Middle" component's memory probe also displays the correct value
- Create a custom component called "Outer" that uses a "Middle" component like an 8-bit memory
- With the "Outer" component opened in the Component Factory, test that
  - the "Middle" component saves and loads values correctly
  - the "Middle" component _**always displays a 0**_, rather than its current value
  - (Optional) any memory probes connected to the "Middle" component always show 0

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Which version are you on?
And would you mind uploading your example here: https://turingcomplete.game/report_bug
This guarantees that I can reproduce and I will fix it asap

**Comment by Stuffe** [comment]
Thank you for the very detailed bug report you uploaded. This issue has now been fixed in version 741

**Comment by michaellindman** [comment]
I have encounted this issue again but I'm on the latest Steam release of 0.925 Beta. perhaps a regression somewhere has broke this again?
