### ISSUE TITLE
[Bug]: Migration issue with nesting levels

### ISSUE THREAD

**Issue by vxgmichel** [Turing-Complete-Game/Suggestions-and-Issues#424]
### What happened?

After I started to use version 0.728, I noticed that one of my previous design no longer worked as expected.

Then I noticed that opening some of the sub components at least once fixed the issue. However, closing and re-opening the game causes the issue to appear again. I ran a quick investigation and here are my findings.

I isolated one of the buggy sub components and created a copy of it using the schematics menu. As you can see in the screenshot below, the copy correctly outputs `1` where the original component wrongly outputs `0`. 

![before](https://user-images.githubusercontent.com/7490006/166903232-701ec361-cd67-4c79-be6d-4bbe16e86884.png)

After opening the buggy sub component and heading back to the overall design, both components output `1` correctly:

![after](https://user-images.githubusercontent.com/7490006/166903715-7959c8ca-2fcb-44b2-b473-5088dcc31906.png)

I used [turing-complete-interface](https://github.com/MegaIng/turing-complete-interface) to compare the two components and it turns out the `circuit.data` files differ by very little:

```
E         Omitting 10 identical items, use -vv to show
E         Differing items:
E         {'nesting_level': 1} != {'nesting_level': 0}
E         {'save_version': 294734888110546160} != {'save_version': 5367111108562193828}
```
My suspicion is that something got wrong during the migration to remove the nesting level in the components.

It's nice to know that the problem can easily be fixed by copying the subcomponents but it's also very hard to know which component is at fault, especially in complex designs. The fact that the problems no longer occurs once the component has been open makes it hard to realize what's going on.

Please let me know if you need some extra information.

 

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Thank you for the thorough bug report. You migrated from an older version of the game? 
Unfortunately there has been backwards compatibility breaking changes over the months. I do think the worst is behind us though

**Comment by vxgmichel** [comment]
> You migrated from an older version of the game?

Well, I don't think the issue was present around the 20th of april (I think I would have noticed, probably? It's hard to know since I might also have opened my components before testing). I think that was version 683 or close enough.

Also, I can confirm this issue still happens in version 733. I'm keeping my buggy components around for the moment so I can confirm it's fixed, if it gets fixed. If you don't plan on fixing it I'll simply copy all my components as it seems to be a valid workaround. In any case please let me know :)

**Comment by vxgmichel** [comment]
I just noticed something really weird: renaming my buggy component fixes the issue, and even weirder, renaming the component back to its original name (`int_latch`) recreates it. I'm really puzzled.. I wanted to get to the bottom of it on my own (or at least have something really simple to reproduce the issue) but now I don't where to go with that :sweat_smile: 

I also tried to fix the issue by renaming the component I identified as buggy, but somehow other components began to exhibit the same kind of behavior. I'm not sure how I can fix it locally, please let me know if you have any idea, thanks :)

**Comment by vxgmichel** [comment]
I attached some schematics that hopefully should be enough to reproduce the issue.

The zip file below includes:
- 1 safe SR latch component (i.e a wrapped SR latch that resolve the `S AND R` case)
- 1 test component that simply outputs `/Q` from the safe SR latch (i.e should always be `1`)
- 1 design that simply includes the test component (and hence should output `1`)

[schematics.zip](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/8686489/schematics.zip)

As you can see from the screenshot below, the test component isn't displayed properly when the design is open at game startup:
![Screenshot from 2022-05-13 13-10-01](https://user-images.githubusercontent.com/7490006/168271528-c573cbbe-550d-45e9-b070-0522c8ec77a6.png)

After opening the test design once and heading back to the main design, this issue is fixed:
![Screenshot from 2022-05-13 13-12-42](https://user-images.githubusercontent.com/7490006/168271943-dd940a88-24cf-436b-8683-a47d1c1cb29c.png)

There seems to be some hidden parameters that I'm missing because I can't reproduce this issue all the times. More precisely, it does always happen at startup if it has been observed once, but:
- it might not happen anymore after renaming the test component
- it might not happen anymore after updating the test component
- it might not happen if it uses another version of the safe SR latch (even though they seem indistinguishable)
- and so on
I said "might" because I ran many tests but I couldn't make sense from the results I got, so I might have missed something.

Hopefully this will help :)

**Comment by vxgmichel** [comment]
The schematics zip file I mentioned in my last message: [schematics.zip](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/8686599/schematics.zip)
