### ISSUE TITLE
[Bug]: Counter not updating with ticks

### ISSUE THREAD

**Issue by gabrielpandrade** [Turing-Complete-Game/Suggestions-and-Issues#426]
### What happened?

After the update on may 5 my counter on computers is not updating anymore 
https://www.loom.com/share/3d51959326294bc0a3a45c0baa933af6

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
It's increment is set to zero, because of the save format change announced in the main menu. Just change the increment in the bottom panel to 1.
