### ISSUE TITLE
[Bug]: All constants reset

### ISSUE THREAD

**Issue by Cereal4Dinner** [Turing-Complete-Game/Suggestions-and-Issues#427]
### What happened?

A bug happened!

Seems like all my constants were reset to zero today. Doubt anything can be done about it.

### Version

Latest

### Operating System

win11pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Yes, as mentioned in the main menu, this is sadly a consequence of the last update.
