### ISSUE TITLE
[Bug]: ALPHA: Cannot select Red Register

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#43]
### Discord Thread

https://discord.com/channels/828292123936948244/1264290653341483092

### What happened?

Normally you can select a component to inspect its pins in the bottom pane, since the Reg Registers are not editable that doesn't seem possible to view the pin labels in the Register level.

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
