### ISSUE TITLE
[Bug]: Moving imovable red components

### ISSUE THREAD

**Issue by eReN17** [Turing-Complete-Game/Suggestions-and-Issues#43]
### What happened?

I can move 'imovable' red components if i've got it selected and moving wire joint while holding ALT.

- Selecte imovable object
- Press and hold ALT
- Try to move random wire joint 
- See 'imovable' object move with joint

### Version

Latest

### Operating System

Windows10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I can reproduce this.
