### ISSUE TITLE
[Bug]: Counter is not working

### ISSUE THREAD

**Issue by aristakesyanl** [Turing-Complete-Game/Suggestions-and-Issues#438]
### What happened?

After the latest updates, my program counter is not working. It doesn't increase. I made no changes.
![Screenshot_3](https://user-images.githubusercontent.com/60519263/168740825-4a4103ad-6257-4830-9846-f1ef6aa496f2.png)
.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
As mentioned in the update infos in the main menu, the increment attribute of the Counter component broke. Click on the component and edit the value to 1.
