### ISSUE TITLE
[Bug]: Pin on register becomes unconnectable

### ISSUE THREAD

**Issue by TheIronHobo** [Turing-Complete-Game/Suggestions-and-Issues#439]
### What happened?

A bug happened! On the level Calculations, the 'always output' pin of register 2 is no longer wireable. Any attempt to drag a wire to or from that pin and only that pin does not work. Bug persists through restarts. I suspect I'd need to modify my save file to fix it. This same problem happened with other miscellaneous components at various times but I could always delete and replace the component to fix it. Since the registers on this level can not be deleted this workaround does not work. Bug aside, this game rocks. Thanks for all yall do.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gloowa** [comment]
I also envountered this issue, the workaround is to create a piece of wire, and then ctrl+c, ctrl+v it onto the pin, it will connect then. This allows you to progress further.

**Comment by MegaIng** [comment]
This has been fixed
