### ISSUE TITLE
[Request]: Rotate selection

### ISSUE THREAD

**Issue by eReN17** [Turing-Complete-Game/Suggestions-and-Issues#44]
Rotate all selected components at once would be a nice addition 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
This is currently in the development version, not sure if it's in the main branch yet though.

**Comment by bombitmanbomb** [comment]
Duplicate of #30 
Available in Development Build.
