### ISSUE TITLE
[Bug]: ALPHA: Crash on right clicking a selected wire

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#44]
### Discord Thread

https://discord.com/channels/828292123936948244/1264292024887279722

### What happened?

Selecting multiple wires and then right clicking on them crashes the game.
I can only repro this in the Register Level on the wires connected to the right most register.

![image](https://github.com/user-attachments/assets/d21a44c5-0b0b-48f8-a881-8751ddf57317)

[overture_1_registers.zip](https://github.com/user-attachments/files/16322039/overture_1_registers.zip)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Gelthir** [comment]
Smaller test case inside a sandbox architecture: Select (with shift-click drag) all the wires, then right click on the background - I'd expect this to cancel the selection as that's how it behaves in the previous version. Instead it crashes with:

tables.nim(234)          raiseKeyError
Error: unhandled exception: key not found: 4 [KeyError]

[wire-copy-paste.zip](https://github.com/user-attachments/files/16324783/wire-copy-paste.zip)

**Comment by Stuffe** [comment]
fixed next patch
