### ISSUE TITLE
[Bug]: Input and output on 'Calculations' can be deleted

### ISSUE THREAD

**Issue by TheIronHobo** [Turing-Complete-Game/Suggestions-and-Issues#440]
### What happened?

Title says it all. If this is intentional please disregard but I could see this causing trouble. Cheers.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You should be able to place them again, so this is not really a problem I think.

**Comment by MegaIng** [comment]
Turns out, this can be a problem in for example the early OVERTURE levels: https://discord.com/channels/828292123936948244/893929557072162827/976459556471316540

**Comment by Stuffe** [comment]
this was fixed
