### ISSUE TITLE
[Request]: External assembler

### ISSUE THREAD

**Issue by tronkko** [Turing-Complete-Game/Suggestions-and-Issues#441]
### Request?

I love the game and I would like to build an assembler for my language!  Preferrably the assembler would be an executable program that, when given an assembly language file, would produce translated code you could then run under Turing complete.

For example, if the input file contains assembly code:
```
mov #0xF000, ax
mov (ax+5), bx
nop
jmp done
```
then the external program might translate the file to:
```
0x03 0xF0 0x00 # mov #0xF000, ax
0x56 0x85 # mov (ax+5), bx
0xCC # nop
0x05 0x00 0x20 # jmp done
```

Compilation errors might be reported back to Turing Complete simply with line numbers:
```
pcr.assembly:2: Invalid instruction
```

The assembler is doable already and it would only need to be integrated with Turing Complete such that you could edit code and have the file compiled before running it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
At some there will be an assembly macro language feature in the game, so you will be able to use any syntax you want. Right now though you could perhaps externally generate in game compatible assembly and leave a comment with an error message if it didn't work. Not a perfect solution, but may be an OK hack for now
