### ISSUE TITLE
[Request]: opening schematic inconsistency 

### ISSUE THREAD

**Issue by Cereal4Dinner** [Turing-Complete-Game/Suggestions-and-Issues#443]
### Request?

Can you make opening a schematic consistent in its position? Right now, the same position and zoom is used between schematics. If the newly opened schematic is on another part of the board, you have to do a little search, or zooming, or whatever to find the schematic. Can you center the schematic and camera on the board, or center the camera on the schematic?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
the schematics now save the camera positions of the last edit
