### ISSUE TITLE
[Bug]: Wire Spaghetti Input issue

### ISSUE THREAD

**Issue by gloowa** [Turing-Complete-Game/Suggestions-and-Issues#444]
### What happened?

In v 0.766 Beta, when testing the Wire Spaghetti level, a red box is shown that reads "Argument 7 means read from input, but input is not enabled" despite input being enabled (and correct result is stored into correct register):

![turing_bug_1](https://user-images.githubusercontent.com/686705/169369936-8e072faf-3e2d-40a8-bfee-aa7c42fd2296.PNG)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is related to #440

**Comment by oxi-dev0** [comment]
I have this issue aswell, the instruction is being processed correctly but it gives this error and wont increment tick.

**Comment by MegaIng** [comment]
This can be worked around by creating a new schematic, and making sure to not delete the preplaced IO components in there. You can copy over everything else.

**Comment by gloowa** [comment]
"This can be worked around by creating a new schematic, and making sure to not delete the preplaced IO components in there"

That didnt work for me for some reason, i will try again after work but new schematic -> copy blue components from old one -> connect to red from new schematic didnt fix the issue. (i am running new game, after factory reset in options, i tend to do that after each bigger update)

**Comment by MegaIng** [comment]
Then upload your save to https://turingcomplete.game/report_bug and Stuffe can take a look.

**Comment by oxi-dev0** [comment]
I have submitted my save file aswell, as your suggestion didnt work for me

**Comment by Stuffe** [comment]
This is now fixed in 0.771.
