### ISSUE TITLE
[Bug]: Hex Racer is not marked as Complete after completing

### ISSUE THREAD

**Issue by mikecat** [Turing-Complete-Game/Suggestions-and-Issues#445]
### What happened?

I completed the new "Hex Racer" level (saw the "Level Complete" pop-up), but the level is still shown in yellow in the Level map.

Game version: 0.767 Beta

### Version

Other

### Operating System

Windows 10 Home 21H2 x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Potentially related to #447

**Comment by MegaIng** [comment]
This should be fixed. Can you check if you can now beat the level?
