### ISSUE TITLE
[Bug]: In Level "Calculations" - Tick 4: Register 3 expects wrong value

### ISSUE THREAD

**Issue by crc-fehler** [Turing-Complete-Game/Suggestions-and-Issues#446]
### What happened?

At the very first run after the level "Calculations" is loaded, at tick 4 (the OR-Tick):
register 0 expect to hold **123**
register 1 expect to hold **152**
register 3 expects a value of **255** but should expect **251** ( **123 OR 152** is **251** )

Each following run (without reloading the level), tick 4 got different values:
register 0 expect to hold **123**
register 1 expect to hold  **63**
register 3 expect a value of **63** but should expect **127** (**123 OR 63** is  **127**)

![Screenshot 2022-05-19 213406](https://user-images.githubusercontent.com/42750899/169388091-4fd21c69-789b-4df6-97a2-f8899d1e0902.png)

### Version

Latest

### Operating System

Win10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You are supposed to use register 1 and 2 as ALU inputs, not 0 and 1.

**Comment by crc-fehler** [comment]
Ah! My fault! Sorry!
