### ISSUE TITLE
[Bug]: 8-bit switch

### ISSUE THREAD

**Issue by bdub-1** [Turing-Complete-Game/Suggestions-and-Issues#448]
### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/100250017/170065127-d214845c-0909-4c6c-a89b-0b476b039eb9.png)

The 8-bit switch allows power output despite it not being enabled.  It causes a short circuit

### Version

Latest

### Operating System

windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdub-1** [comment]
Thanks, I get every tick correct in this level except this tick. My not gate on the right gets activated only for this input.

![image](https://user-images.githubusercontent.com/100250017/170069368-a870c31d-9a6c-4b0e-b1ff-29cacf2efc96.png)

**Comment by jholladay10** [comment]
I think the problem is that you're running a byte signal into the bit NOT and it's not doing what you want.  You should just use your bit input on the 2nd switch and, as mentioned above, just wire the byte wires together on the output.

**Comment by Stuffe** [comment]
This was fixed
