### ISSUE TITLE
[Bug]: Stuck camera movement

### ISSUE THREAD

**Issue by eReN17** [Turing-Complete-Game/Suggestions-and-Issues#45]
### What happened?

I'm not really sure what causes this bug, but from time to time using WASD / Zoom makes camera moves endlessly in one direction. It even persist after i use 'Level search' feature and select level (see attached gif).

![2021-11-14 23-10-54](https://user-images.githubusercontent.com/5936651/141700779-444afcb8-736b-48fc-b0fc-f2bc41df8296.gif)

It keeps coming back because i hover over levels in 'Level seach' 

### Version

Latest

### Operating System

Windows10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
pretty sure this is a stuck key which I can't do anything about. Just click "a" on your keyboard next time you see this

**Comment by eReN17** [comment]
Nope that's not it. If it would be a stuck key i would see it in 'level search' feature
