### ISSUE TITLE
[Bug]: Component limit in the level "bit switch" doesn't work.

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#45]
### Discord Thread

https://discord.com/channels/828292123936948244/1264294931996999761

### What happened?

The components don't vanish from cursor when you place 2, so as long as you won't right click, you can place as many as you want.
![image](https://github.com/user-attachments/assets/62c49034-9c0e-461d-9f1a-edf7e42251e2)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed
