### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LOICVAL42** [Turing-Complete-Game/Suggestions-and-Issues#450]
### What happened?

Hello,

I am playing on arch linux.
Sometimes the game would randomly crash (rotating a component over a file and stuff like that)
However, i'm now stuck att the "add 5" level. Every time i reach the end of the level the game just crashes.

### Version

Latest

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LOICVAL42** [comment]
Thanks, i uploaded my save to the given link.

**Comment by Stuffe** [comment]
fixed in 0.786

**Comment by LOICVAL42** [comment]
Thanks!
