### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LOICVAL42** [Turing-Complete-Game/Suggestions-and-Issues#451]
### What happened?

Hello,

I know i've already posted this yesterday but this as been marked as completed even though it still doesn't work.
Here's my original post:

I am playing on arch linux.
Sometimes the game would randomly crash (rotating a component over a file and stuff like that)
However, i'm now stuck att the "add 5" level. Every time i reach the end of the level the game just crashes.
I noticed it crashes when it tries to add 5 to the number 1 as the 33th test out of 32.

### Version

Latest

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Did you update the game? If yes, upload your save here: https://turingcomplete.game/report_bug

**Comment by LOICVAL42** [comment]
I did, i was in 0.789 last time i tried. I'm gonna upload it rn.

**Comment by Stuffe** [comment]
Thanks for uploading, now actually fixed in the next patch
