### ISSUE TITLE
[Bug]: Game Crashes on launch

### ISSUE THREAD

**Issue by IsaacGoins** [Turing-Complete-Game/Suggestions-and-Issues#453]
### What happened?

After the update on May 25th, my game crashes on launch. Nothing loads except for a gray screen.

### Version

Latest

### Operating System

Windows 11 - Version 21H2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcelmaatkamp** [comment]
I have the same problem: windows 10, gray screen and game does not start.

my debug.log:

`Turing Complete 0.800 Beta on Windows
tm_halt
ERROR: Failed to invoke Nim procedure load_level: expected 1-1 arguments, but got 2
   at:  (godotmacros.nim:295) - Failed to invoke Nim procedure load_level: expected 1-1 arguments, but got 2
tm_halt`

**Comment by Stuffe** [comment]
This was fixed I believe
