### ISSUE TITLE
SR Latch Level not showing up 

### ISSUE THREAD

**Issue by corybuchholz** [Turing-Complete-Game/Suggestions-and-Issues#454]
### What happened?

I did a "reset" of the game on the options menu and started over again.  This time thru the SR latch isn't available.  You can search for it in the level search in the level map screen but it isn't playable.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
You need to enable it in the settings

**Comment by corybuchholz** [comment]
Oh I feel silly.  

Thanks!
