### ISSUE TITLE
[Bug]: Current Output seems stuck at all high.

### ISSUE THREAD

**Issue by corybuchholz** [Turing-Complete-Game/Suggestions-and-Issues#455]
### What happened?

A bug happened!

I'm working on the BYTE OR level and when I run thru the ticks it shows Desired Output and Current Output.  The current Output shows on the screen as ALL HIGH and never changes.  The level completes successfully and I can move on to the next level but the current output never changes on the screen.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
does this still happen? If so can you upload your save here:
https://turingcomplete.game/report_bug
