### ISSUE TITLE
[Bug]: Right click in Component Factory crashes the game

### ISSUE THREAD

**Issue by uiofgh** [Turing-Complete-Game/Suggestions-and-Issues#458]
### What happened?

When right click to remove anything in Component Factory, the game crashes.

### Version

Latest

### Operating System

win10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Does this still happen for you? If so could you upload your save here and I will fix it:
https://turingcomplete.game/report_bug
