### ISSUE TITLE
[Request]: Recenter camera

### ISSUE THREAD

**Issue by eReN17** [Turing-Complete-Game/Suggestions-and-Issues#46]
### Request?

Recenter camera for roadmap and levels. 

This is kinda related to my last bug report (stuck camera movement).  When i happened to stop the movement somehow  i found myself lost and couldn't find my way back to the 'circuitboard'. It's not a big deal (can still jump out to menu and back) but would be a nice feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
At some point there will be a boundary you cant scroll beyond, but I don't want to add a button for this specifically
