### ISSUE TITLE
[Bug]: Crash / Save file corruption when loading "Program" level.

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#46]
### Discord Thread

https://discord.com/channels/828292123936948244/1264301529029021736

### What happened?

When loading the "Program" level for the first time with an existing architecture from the previous level, the game crashes and wont restart.

Error: unhandled exception: cache_opps.nim(67, 12) `h notin component_area_obstructions` AREA POS: (x: -41, y: -25) 7 25 [AssertionDefect]

A rom-file is created inside `overture_4_program\Default` everytime the game is restarted.

Maybe the game tries to place a program component without enough space.

Workaround: Delete the `overture_4_program` directory, restart the game and manually copy the architecture from the previous level.

### Version

0.1067

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
this was caused by the Front Panel spawning on top of something else. This shouldn't happen again in the future (although the save in question is still corrupted)
