### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by planles1905** [Turing-Complete-Game/Suggestions-and-Issues#460]
### What happened?

A bug happened! Hello I've a bug in odd ticks.. even if I've unlock the delay it does not appear in odd ticks
![Capture](https://user-images.githubusercontent.com/106737753/171599533-230c36b9-803a-4c73-ab48-694a9dbd07be.PNG)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Fixed in 0.820
