### ISSUE TITLE
[Bug]: Level "The Bus" requires four switches but only two are allowed

### ISSUE THREAD

**Issue by flokle** [Turing-Complete-Game/Suggestions-and-Issues#462]
### What happened?

I'm quite sure i need two switches for in- and two switches for output selection but only two are allowed in total.

![image](https://user-images.githubusercontent.com/43744390/171695372-ed94badb-cdbe-4df9-a236-87c00ef2a1ed.png)

### Version

Latest

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Is fixed in 0.822
