### ISSUE TITLE
[Bug]: Manual Entry level result always says "Entry: Architectural Complexity"

### ISSUE THREAD

**Issue by mikeday37** [Turing-Complete-Game/Suggestions-and-Issues#463]
### What happened?

Whenever I complete a level that unlocks a Manual Entry, when I mouse-over the book icon in the Level Complete window, it always shows "Entry: Architectural complexity".  I would instead expect it to give the name of the entry it actually unlocked.

For reference, on my profile I completed several levels a long time ago, but before playing on the latest update, I did a "factory reset."

![image](https://user-images.githubusercontent.com/75497325/171987379-6b0dcba8-6679-4e22-84be-30b2b11a69e9.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed
