### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Al3xander123** [Turing-Complete-Game/Suggestions-and-Issues#466]
### What happened?

A bug happened!
Is no really a bug, is just a miss match pinout of display 7seg
Actual -- Must Be
A 7  -- A 1
B 1  -- B 2
C 2  -- C 3
D 3  -- D 4
E 4  -- E 5
F 5  -- F 6
G 6  -- G 7

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is fixed in the newest development patch
