### ISSUE TITLE
[Bug]: Creating first custom component inside a folder causes crash

### ISSUE THREAD

**Issue by MJE10** [Turing-Complete-Game/Suggestions-and-Issues#47]
### Discord Thread

https://discord.com/channels/828292123936948244/1264302262294151168

### What happened?

(after deleting everything from the save folder)

- Go to Sandbox
- Go to Component Factory
- Click Switch Schematic
- Create a folder
- Double click it
- Create a schematic inside the folder
- Observe crash when you click enter after typing the name

Note, the crash does not happen if one first creates a component in the root folder next to Default

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1067 Beta on Windows
```

**Comment by Stuffe** [comment]
fixed next patch
