### ISSUE TITLE
[Bug]: Wrong EXPECT values in PUSH AND POP level

### ISSUE THREAD

**Issue by ZennTNX** [Turing-Complete-Game/Suggestions-and-Issues#472]
### What happened?

In test 3/4 Tick 9 the command is "PUSH[149] on stack" but it throws an error "You were supposed to POP the last value (149) off the stack"

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The level has confusing/wrong error messages, I would suggest you upload your save to https://turingcomplete.game/report_bug .

But if you do everything correct, you wont get error messages, so you have a bug in your implementation as well. It's probably something like not disabling/enabling the input or output, hard to say without seeing your solution.

**Comment by Stuffe** [comment]
The error message should now be fixed in the development version of the game
