### ISSUE TITLE
[Bug]: Game crash when renaming programs to empty.

### ISSUE THREAD

**Issue by core-exe** [Turing-Complete-Game/Suggestions-and-Issues#474]
### What happened?

At level maze, but i suspect other level that have an text editor will crash in the same way.

Step to trigger this bug:
+ Open level "maze" and its text editor
+ Create a new file, delete the file name
+ Hit the key "esc", and the game will crash.

The game is still openable after triggering the crash.

### Version

Latest

### Operating System

Windows 10 21H2 19044.1706

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next patch
