### ISSUE TITLE
[Bug]: The Maze input is always 0

### ISSUE THREAD

**Issue by stefior** [Turing-Complete-Game/Suggestions-and-Issues#475]
### What happened?

In The Maze level the computer's input always stays at 0 even if the robot is looking at a wall. I think to be able to figure out this level I need to be able to know if the robot is looking at a wall or not.

Also, the indicators on any of the DEC output pins don't ever change from red to green even when the wires connected to them do properly. That doesn't really seem to affect this issue though, it's just a visual thing that you might want to know about.

![full window](https://user-images.githubusercontent.com/43305255/174432790-edb03108-8156-43ab-ab73-4cd55b3a1cc4.png)
![DEC visual error](https://user-images.githubusercontent.com/43305255/174432791-1847032d-80d2-4d8b-9ada-1cb57d1d644a.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The input in an architecture only shows the value if you enable it. In the screenshot you are showing you are not trying to read from input, so it is displaying zero.

**Comment by stefior** [comment]
Oh, thank you. When I choose my own input in the top left it shows it on the level's "in" component even without enabling it, so that confused me that it wouldn't show it on the component itself like it normally does, and I jumped to conclusions. It turned out I just had the wrong assembly code saved.
