### ISSUE TITLE
[Bug]: Options Menu not closeable 

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#477]
### What happened?

![Animation](https://user-images.githubusercontent.com/11261721/174662772-1d3b891c-b612-4524-9284-167eb26e4e4c.gif)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This was fixed a while ago
