### ISSUE TITLE
[Bug]: Custom component containing 1-bit memory calculates output delay incorrectly

### ISSUE THREAD

**Issue by Arnavion** [Turing-Complete-Game/Suggestions-and-Issues#48]
### What happened?

Originally reported for: 0.302 Beta
Still repros in: 0.326 Beta

![image](https://user-images.githubusercontent.com/1096010/141861242-3e193da1-6af1-4e07-90e9-f7ebfc4c4314.png)

The 1-bit memory has 6 delay. The delay in the top-right is calculated correctly. But the delay in the bottom on the "Output" pin is calculated as 12.

This isn't just an artifact of this screen; when I embed this component in another custom component, the output pin really does have a delay of 12.

This was reduced from a larger test case:

![byte D-latch](https://cdn.discordapp.com/attachments/850737218759032892/909924237677043712/unknown.png)

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
As far as I can see this should be fixed now in the development version.
