### ISSUE TITLE
[Bug]: Input descriptions wrong in "Saving bytes"

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#48]
### Discord Thread

https://discord.com/channels/828292123936948244/1264305379051962438

### What happened?

They both say "load" instead of one being "store" and one "load".
![image](https://github.com/user-attachments/assets/e3713901-0a94-4cc2-b8c0-2d681b1dcca9)
![image](https://github.com/user-attachments/assets/f627c09a-e2cf-4854-809e-4fb9ec794cc2)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed next patch
