### ISSUE TITLE
[Bug]: Inconsistency between top left IO panel and actual IO when 'converting' from byte to bit

### ISSUE THREAD

**Issue by Pyrogue** [Turing-Complete-Game/Suggestions-and-Issues#486]
### What happened?

works correctly when first bit enabled
![Screenshot 2022-06-28 040549](https://user-images.githubusercontent.com/18368653/176127923-0636181a-b529-4da2-aadf-1ddbc8801b7f.jpg)
output is actually off, but shows in the HUD as on when first bit is off
![image](https://user-images.githubusercontent.com/18368653/176127844-f8a570f9-3722-4374-b02b-e5fec892b551.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This does not function like C where anything larger than 0 coerces to true. Here the lowest bit is used. This is consistent with how you can plug a 64 bit wire into an 8 bit pin and only use those 8 lowest bits (important feature).
