### ISSUE TITLE
[Bug]: Game Crashes when Undoing in the Component Factory

### ISSUE THREAD

**Issue by CapitanChones** [Turing-Complete-Game/Suggestions-and-Issues#488]
### What happened?

A bug happened! Whenever I misplace a component I undo it using the shortcut Ctrl + Z, when doing this in the component factory it closes to the desktop. It has happened once in the "Little Box" but seems to have been fixed upon relaunching. This is an issue that otherwise I have only experienced in the component factory. I am also aware that on Linux machines and some programs Ctrl + Z is the interrupt shortcut, not sure if this is at play. 

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think this was fixed a few days ago
