### ISSUE TITLE
[Bug]: Bypass validation

### ISSUE THREAD

**Issue by SorginDigitala** [Turing-Complete-Game/Suggestions-and-Issues#489]
### What happened?

Player allowed to edit the scheme in validation time. This return null/correct results,
Version: 0.898

https://www.youtube.com/watch?v=O4v9iD4V2vo
https://steamcommunity.com/sharedfiles/filedetails/?id=2829733688

Sorry my english and i not read your stupid code of conduct.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed in dev
