### ISSUE TITLE
[Bug]: Typing '9' nineteen times into the input field of input in causes crash

### ISSUE THREAD

**Issue by MJE10** [Turing-Complete-Game/Suggestions-and-Issues#49]
### Discord Thread

https://discord.com/channels/828292123936948244/1264306352088416308

### What happened?

- Create a custom component
- Place an input pin
- Set it to 16 or 32 bits
- Click in the text box for the input pin, on the left
- Type the number 9 nineteen times (9999999999999999999)
- Observe crash

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1067 Beta on Windows
```

**Comment by Stuffe** [comment]
I believe this was fixed
