### ISSUE TITLE
[Bug]: Execution stops without reason

### ISSUE THREAD

**Issue by m-biermann** [Turing-Complete-Game/Suggestions-and-Issues#490]
### What happened?

The execution of some programs stops without any reason but always at the same program address(es).

There are no break points at the addresses and putting one and removing it doesn't fix the behavior.
There is also no message and afaik there are no halt's triggered.

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Please upload your schematic with instructions here: http://turingcomplete.game/report_bug
