### ISSUE TITLE
[Bug]: Mouse moving by itself

### ISSUE THREAD

**Issue by justinjohnson14** [Turing-Complete-Game/Suggestions-and-Issues#492]
### What happened?

Mouse starts moving diagnaly up and right as soon as the game starts. and only when im focused on the game window

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is probably caused by some kind of controller being plugged in/connected to the PC.

**Comment by justinjohnson14** [comment]
bruh. My controller was plugged in and laying on the joystick thank you lol.
