### ISSUE TITLE
[Bug]: Line breakpoint indicator disappears after changing program

### ISSUE THREAD

**Issue by stephentoth** [Turing-Complete-Game/Suggestions-and-Issues#498]
### What happened?

Steps to reproduce:

1. Go into code assembler
2. Add breakpoint
3. Change the code
4. Breakpoint indicator disappears (while line still acts as a breakpoint)

### Version

Development

### Operating System

Windows 10 Pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This should now be fixed in the dev version of the game
