### ISSUE TITLE
[Bug]: Trying to place overlapping components will crash the game

### ISSUE THREAD

**Issue by Starficz** [Turing-Complete-Game/Suggestions-and-Issues#5]
### What happened?

Exactly as mentioned in title, the expected behavior is to do nothing and play an error sound.

----

To Reproduce: 
- Group Select Components 
- Copy Paste the components in an Invalid Position where a component is overlapping

> Added by @bombitmanbomb 

----

### Version

Development

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
@Starficz Could you please supply your Save Folder. The folder contains logs that may be useful.

Your Save Folder on Windows 11 is located at `%AppData%\godot\app_userdata\Turing Complete`.
Please ZIP the whole `Turing Complete` folder and upload in a reply. (RAR format is not supported)
![image](https://user-images.githubusercontent.com/11261721/140801725-3ebd86d5-f665-4a19-a8c5-11fbe2cb8260.png)

**Comment by MegaIng** [comment]
@bombitmanbomb No, for a crash of this kind the logs are useless.

@Starficz What components are you placing? I can't reproduce.

**Comment by bombitmanbomb** [comment]
Also unable to Reproduce.

**Comment by Starficz** [comment]
Ah i figured it out, its not palcing from the meue bar its copy pasting that crashes.

**Comment by MegaIng** [comment]
Yeah, can reproduce that.

**Comment by bombitmanbomb** [comment]
Modified the ticket to reflect this finding. Thank you @Starficz

**Comment by Stuffe** [comment]
fixed next patch
