### ISSUE TITLE
[Bug]: Sometimes crash when ctrl+z pressed

### ISSUE THREAD

**Issue by MACAYCZ** [Turing-Complete-Game/Suggestions-and-Issues#503]
### What happened?

Sometimes crash when ctrl+z pressed

### Version

Latest

### Operating System

Windows 10 Pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I think this was related to slow HDD. It should now be fixed, if not feel free to reopen this
