### ISSUE TITLE
[Bug]: 8-bit register not saving?

### ISSUE THREAD

**Issue by jholladay10** [Turing-Complete-Game/Suggestions-and-Issues#504]
### What happened?

Shouldn't the register be set to 170 here?

![image](https://user-images.githubusercontent.com/50140581/178380951-a6f1670e-3d5d-44df-a6cc-26176ca514a6.png)

I have this issue in both the "Little Box" and Sandbox.  Unaffected by attaching the output.  Load emits the 0 value.

### Version

Latest

### Operating System

Windows(Steam)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jholladay10** [comment]
As a workaround, I made an 8-bit register in the component factory. It tested fine. However, when I used it as a custom component, it didn't work the same way it did when I tested it. Maybe this is somehow oddly related?

![image](https://user-images.githubusercontent.com/50140581/178395638-7e627354-c4c4-4180-a9df-24e0d5fd914a.png)

![image](https://user-images.githubusercontent.com/50140581/178395714-7d6a862a-328c-4b5d-8e24-8c4b49dd885c.png)

**Comment by MegaIng** [comment]
Are you ticking the simulation?

**Comment by jholladay10** [comment]
Interesting. I hadn't considered that because i lose control of the inputs.  So when i ticked the second simulation above, my homemade register worked but the stock one didn't.  I think that's because there's a time delay in the stock one and the simulation errors out due to a bad result.  I didn't realize that the time delay was a critical element of a register.

![image](https://user-images.githubusercontent.com/50140581/178613210-9f98e3c9-4076-4536-8407-e14515f4e4fa.png)

So I tried it in the sandbox and two ticks worked.

I guess i don't really understand the 'tick' requirement as it relates to register operation (in terms of the time delay on the stock register, like why that's a thing).

Also, it would be nice to be able to tick without starting down the path of the pre-done test cases.  If there was a way to tick without changing the inputs, that would be nice.  And then somehow make it clear that ticking is essential to the proper operation of a complex circuit.

Although I do find the difference in operation of my component in its test mode vs my component included in a circuit is unexpected.

Thanks for the help!
