### ISSUE TITLE
[Bug]: Condition Equals Zero is not functioning.

### ISSUE THREAD

**Issue by MishaMcMash** [Turing-Complete-Game/Suggestions-and-Issues#509]
### What happened?

I've been trying to complete The Maze. To do so would like to be able to jump to a label if the condition equals zero. Pretty standard stuff.

Problem is, the line won't jump if I use Equals Zero. I can make it jump if I use Condition Not Zero, Greater Than Zero and Less Than Zero, but not Equals Zero.

Current version of the game is 0.925 Beta.

Thank you.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
That logic is defined by your own schematic and assembly. The simulator itself has no concept of what "jump" or equality means, so this is a bug in your solution.

**Comment by MishaMcMash** [comment]
I apologize for posting an issue that seems to be my own error.

If I test for condition < 0, it jumps correctly.
If I test for condition > 0, it jumps correctly.
If I test for condition != 0, it jumps correctly.
If I test for condition = 0, it does not jump correctly.

All I have changed is the bits on the condition.

I am using the condition matrix that passed the test earlier in the game and have not changed it.

What am I doing wrong?
