### ISSUE TITLE
[Bug]: Crash with Assembler and Custom Components

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#51]
### Discord Thread

https://discord.com/channels/828292123936948244/1264520951719264317

### What happened?

Game crashes in the following scenario (reproduceable from a new architecture):
- Create a non-empty custom component
- Place the custom component
- Place an assembler **after** placing the component
- Click edit to open the assembler gui
- [Optional] Close the assembler gui
- Select the custom component and click the wrench to edit it
- Crash: `Error: unhandled exception: index 2 not in 0 .. 1 [IndexDefect]`

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
