### ISSUE TITLE
[Bug]: (UI) assembly editor play/stop/step buttons render in foreground of "Add assembly code" dialogue

### ISSUE THREAD

**Issue by ataboo** [Turing-Complete-Game/Suggestions-and-Issues#511]
### Conditions
Level: Calibrating Laser Cannons
Version: v0.925 Beta
Platform: Windows/Steam x64, full-screen

### Steps to Reproduce
1. Open 'Assembly Editor' and 'Add assembly code' dialogues
2. Drag 'Add assembly code' dialogue over the step, play and stop buttons in the 'Assembly Editor'

Step, play, and stop buttons are in the foreground with the rest of the 'Assembly Editor' dialogue behind
 
### Expected Behaviour
Buttons visibility should be blocked by the Add assembly code dialogue.  The instructions dialogue is in the foreground of these buttons as expected.

![image](https://user-images.githubusercontent.com/5650738/179422712-177a11fd-71cf-4645-9998-9cb0403b86fd.png)

### Version

Latest

### Operating System

Windows x64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is now fixed in the dev version of the game
