### ISSUE TITLE
[Bug]: "Wire Spaghetti" level does not accept the "RegisterPlus" component

### ISSUE THREAD

**Issue by tgiddings** [Turing-Complete-Game/Suggestions-and-Issues#513]
### What happened?

The level requires you to set some of the program block's linked components. The dialogue is "Linked component {n} should point to a register or a custom component with a register inside". If you link to the "RegisterPlus" component, the level does not move onto the next dialogue -- even though the previous step ("Add 6 registers to the map") does accept this component. Using the plain "8 bit register" component meets the hard requirement.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Uploading a fix to this now. You will have to link the components again though
