### ISSUE TITLE
[Bug]: Level "Wire Spaghetti" has misleading dialog

### ISSUE THREAD

**Issue by NotNotQuinn** [Turing-Complete-Game/Suggestions-and-Issues#514]
## Issue

As of `0.930 Beta` I cannot complete the level titled "Wire Spaghetti" (where you start to build the LEG architecture). It seems this is because the game cannot recognize that I have added a linked component to the program component. The furthest I am able to get is to connecting the components to the program component, and specifically the error message from that point forward is always `Linked component 0 should point to a register or custom component with a register inside` (so long as the previous requirements are still met)

### Screenshot:

![image showing connected component, and an error saying to add the component](https://i.imgur.com/6am919N.png)

Even after resetting the game and getting back to this point I have the same problem, and this problem persists even when you complete the rest of the level requirements. I will also upload my game save to the Turing Complete website, referencing this github issue.

### What I expected to happen

When I connect the register to component 0 of the Program component, the game will give me some different error (like about component 1, 2, 3 etc.). and then after all of the components are connected, it will run the program loaded to check if my solution is correct, and let me pass or not based on that.

For example, when there is only 5 registers instead of 6 the error message is "Add 1 more register to the map"

### Notes

Before I reset my game, I opened the `progress.dat` file with an SQLite browser and set the level to complete, but the next level has the same requirement that does not pass. I didn't continue this way because I wasn't able to check my circuits against the game's premade tests and didn't feel like testing each and every functionality.

### Version

Latest

### Operating System

Win 10 Version 21H1 (OS Build 19043.1826)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotNotQuinn** [comment]
Related: #513

It seems I didn't try using a normal register component!

**Comment by Stuffe** [comment]
Thank you for sending your save files. I am uploading a fix for this now. You will have to link the components again though
