### ISSUE TITLE
[Bug]: The Maze: always seeing wall

### ISSUE THREAD

**Issue by Culain** [Turing-Complete-Game/Suggestions-and-Issues#519]
### What happened?

In the Level "The Maze" i noticed that the Display shows that the Robot is always seeing "1 Wall". I can read the correct number from the Input, but the display shows always the wrong input. As if the Display is not updated correctly.

![grafik](https://user-images.githubusercontent.com/5566069/180647691-a909e26c-8f48-47da-b8da-586db551fe0e.png)
here you can see, the robot is looking at the door, but is "seeing" a Wall.

Also, i noticed something similar in the Spacial Invaders Level.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is fixed in the dev version
