### ISSUE TITLE
[Bug]: ALPHA: NAND Gate produce wrong values

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#52]
### Discord Thread

https://discord.com/channels/828292123936948244/1264570069145616394

### What happened?

The 8 Bit Nand Gate produces wrong values, leading to failing the ALU2 level (if a NAND is used), because the expected value of 145 NAND 185 is 110 (in signed values it's -111 NAND -71), yet it outputs 70. Can be reproduced in the sandbox 

![image](https://github.com/user-attachments/assets/9c251712-e0b0-4c53-b155-45cfd045305a)
(Reported by UnsignedRobin on Discord)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
