### ISSUE TITLE
[Bug]: Simulation does not pause when returning to level select screen

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#52]
### What happened?

https://user-images.githubusercontent.com/662325/141889270-8af3a0ff-5cc8-4799-9b16-9ba0d8b3745b.mp4

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SunCatMC** [comment]
in 0.544 ticks no longer count up, but play and pause buttons still stay in state of "test is ongoing"

**Comment by Stuffe** [comment]
This is now fixed
