### ISSUE TITLE
[Bug]: Crash on completing levels for the first time

### ISSUE THREAD

**Issue by eliasrg** [Turing-Complete-Game/Suggestions-and-Issues#526]
### What happened?

I have just made my first solutions for Robot Racing, Delicious Order, Planet Names and Dancing Machine. They pass all the test cases, but just as the last test case finishes, the game crashes to desktop. This seems not to happen on levels that are that are green in the level map, only on the yellow ones.

The version is 0.991 Beta. Let me know if more information is required!

### Version

Latest

### Operating System

Manjaro Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The levels do not get marked as completed? Then I would suggest you upload your save folder to https://turingcomplete.game/report_bug (refrence this issue in the message)

**Comment by eliasrg** [comment]
> The levels do not get marked as completed?

No, they do not get marked as completed. They are still yellow and the levels behind them.

> Then I would suggest you upload your save folder to https://turingcomplete.game/report_bug (refrence this issue in the message)

Done! Thanks for the suggestion.

**Comment by eliasrg** [comment]
It seems like something in my computer architecture is causing the crash. I solved AI Showdown with my architecture, and got a crash as above. Then I solved it again, but with a simple circuit with an adder. That time, there was no crash and the level was marked completed. Also, if I now go back and solve it using my architecture, there is no crash. The crash only happened when the level was solved for the first time using my architecture.

**Comment by Stuffe** [comment]
I finally got back from vacation and tried this. I reran "unsigned less" and after about a minute it synced and it caused all the other levels sync as well. I am not sure what the original problem was but it seems to have been fixed (otherwise feel free to post again)
