### ISSUE TITLE
[Bug]: Multi-byte directional pins recently stopped working

### ISSUE THREAD

**Issue by eliasrg** [Turing-Complete-Game/Suggestions-and-Issues#528]
### What happened?

Sometime during the last week, presumably because of an update, the 16-bit, 32-bit and 64-bit bidirectional pins seem to have broken. In my tests, I can't get any signal through them, either into or out of a component. The 8-bit bidirectional pin, as well as input and output pins of any size, still seem to work as expected.

The version is 0.1016 Beta.

I would guess that my save file is not relevant, but I can provide it if needed.

### Version

Latest

### Operating System

Manjaro Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eliasrg** [comment]
I also just noticed that the single-bit and 8-bit bidirectional pins allow a full 64-bit value to be sent through.

**Comment by Stuffe** [comment]
This should be fixed now
