### ISSUE TITLE
[Request]: 64-bit watched state support

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#53]
### Request?

64-bit registers, counters, and custom components cannot be connected to the program component's watched states.

![image](https://user-images.githubusercontent.com/662325/141890359-70a9995f-9e71-4ed5-9948-ff5afe5596b1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
Along with this, being able to define watchable states from internal components would be nice as well. For instance, I might want to combine multiple registers into a single larger state, expose multiple registers as different states, or both.

**Comment by SunCatMC** [comment]
As of 0.544, the only thing missing seems to be watchable 64bit component; default components appear to be supported

**Comment by Stuffe** [comment]
This was fixed
