### ISSUE TITLE
[Bug]: Level input cannot connect to a custom component

### ISSUE THREAD

**Issue by zurbo** [Turing-Complete-Game/Suggestions-and-Issues#538]
### What happened?

If I connect a custom component like this very simple one to the level input
![image](https://user-images.githubusercontent.com/10361296/194790217-d2f47a4a-f67e-4eb8-ab43-6c4374d78a37.png)
it says it's in a state of circular dependency
![image](https://user-images.githubusercontent.com/10361296/194790357-c0b4b237-cf29-4819-99b1-e7e21954bf6e.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
https://turingcomplete.game/FAQ

This is fixed by adding a bidirectional pin anywhere in the custom component.

**Comment by zurbo** [comment]
Oh, ok I didn't see the FAQ before posting, my bad
