### ISSUE TITLE
[Request]: Watched state / expect support for wire connections

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#54]
### Request?

Program component watched state can be connected to circuit nodes, but `expect` cannot be used to monitor the circuit's value.

![image](https://user-images.githubusercontent.com/662325/141890963-d9d53805-9009-4aa3-b16c-be3c9f11c66d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Wires are no longer watched directly
