### ISSUE TITLE
[Bug]: Cannot change asm-file in assembler

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#54]
### Discord Thread

https://discord.com/channels/828292123936948244/1264595268507271189

### What happened?

`SCRIPT ERROR: Invalid call. Nonexistent function 'load_save' in base 'Button (file.gd)'.
          at: _pressed (res://misc/schematic_load.gdc:16)`
when trying to load a asm-file in the assembler.

I'd expect another tab in the asm-window to open, containing the contents of the asm-file.

### Version

0.1069 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
Fixed next patch
