### ISSUE TITLE
[Bug]: Cannot link custom component with memory probe to assembler

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#55]
### Discord Thread

https://discord.com/channels/828292123936948244/1264600614483132569

### What happened?

Works as expected with normal registers, value is shown, first of the three symbols is white and hovering over it shows a dotted green line to the register. 

When trying with a custom component, the dotted line turns green and snaps to the component, but the assembler still shows the value '-', the first of the three symbols left to the value is still greyed out and no line to the custom component is shown.

### Version

0.1069 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
