### ISSUE TITLE
[Request]: Forward delay input pins thru basic components

### ISSUE THREAD

**Issue by henke37** [Turing-Complete-Game/Suggestions-and-Issues#558]
### Request?

Cyclical decencies are a pain. But one mitigation is the delayed input pin found on some of the built in components.

Building custom components will helpfully forward the delayed status when you connect an input pin directly to a delayed pin. This  however does not work if there's a component between the delayed input pin and the component input pin.

A typical example would be the Counter component. It uses a mux to select between the component input pin and the adder. It's impossible to replicate the Counter component in a custom component since the delay input status would be blocked by the mux.

It's probably possible to track if output pins are hooked up to a delayed pin, but I get the feeling that it's more hassle than it is worth. A compromise there would be if the user could manually flag the output pin as requiring being hooked up to a delayed pin, but that's still a bit wonky.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is already implemented. Make sure that the inputs don't affect any output *in the same tick*. Also, the github is basically unused. It's better to post on discord https://discord.gg/QF7zns8S
