### ISSUE TITLE
[Bug]: ALPHA: weird register output behavior

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#56]
### Discord Thread

https://discord.com/channels/828292123936948244/1264352783218507816

### What happened?

this do not happen if the write wire is always on. it's hard to describe, so here's a clip of it happening:

Link to video: https://cdn.discordapp.com/attachments/1264352783218507816/1264352783528755210/Replay_2024-07-21_00-31-58.mp4?ex=669d8fca&is=669c3e4a&hm=eef2491f30043662b14a27a7735cea1c44f4c114896dbfb5daf9cf6e78143865&

(Reported by overcomplexification on Discord. I'm guessing the version and OS)

### Version

0.1067 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
