### ISSUE TITLE
[Bug]: ALPHA: User can inject code in the halt component

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#57]
### Discord Thread

https://discord.com/channels/828292123936948244/1264603791676805173

### What happened?

this will result in the game crashing if the syntax is wrong
here's some examples:
```
"
```
crash the game ( image 1 )

```
")}
```
crash the game ( image 2 )

```
" + (random(2) == 1 ? "1" : "0") + "
```
halt and show either `1` or `0`

(Reported by overcomplexification on Discord)

### Version

0.1069 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
