### ISSUE TITLE
[Bug]: APLHA: ALU level empty

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#59]
### Discord Thread

https://discord.com/channels/828292123936948244/1264636723271434302

### What happened?

When I first enter the level ALU it's empty (apart from the 6 registers, and IO).
I expected it to copy my schematic from the Registers level.

Save from before entering the ALU level:
[Turing Complete.zip](https://github.com/user-attachments/files/16325677/Turing.Complete.zip)

### Version

0.1069 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I don't think this happens anymore
