### ISSUE TITLE
[Bug]: Buffer does not correctly coerce value of higher valued wires.

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#59]
### What happened?

![image](https://user-images.githubusercontent.com/26136419/142034029-a1208610-d498-456d-a9d5-06c4559905bc.png)

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next update
