### ISSUE TITLE
[Bug]: Last loaded level not linking correctly to levels in folders

### ISSUE THREAD

**Issue by Starficz** [Turing-Complete-Game/Suggestions-and-Issues#6]
### What happened?

When entering levels and going back to level via the button in the CF, it fails to laod the correct level when the parent arch level is in a folder.

### Version

Development

### Operating System

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Can reproduce this.

**Comment by bombitmanbomb** [comment]
Reproduced Locally as well.

**Comment by Stuffe** [comment]
This is fixed
