### ISSUE TITLE
[Bug]: Removing the 'File' component without a file loaded causes a crash

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#6]
### Discord Thread

https://discord.com/channels/828292123936948244/1264179958549581959

### What happened?

When a file is loaded it closes fine. Placing and removing the component without loading a file crashes the game.

I assume its trying to call close() on an empty file handle :)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Nothing relevant.
```

**Comment by Stuffe** [comment]
fixed next patch
