### ISSUE TITLE
[Bug]: ALPHA: ALU component missing

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#60]
### Discord Thread

https://discord.com/channels/828292123936948244/1264654778051596298

### What happened?

On entry to the `ALU` level there was no `ALU` component, as described in the level log.
The `alu_1` and `alu_2` levels have been completed and showed as green in the level map.
Rerunning the level tests for `alu_2` did create the expected component and allowed further progress.

### Version

0.1069 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I don't think this happens anymore
