### ISSUE TITLE
[Bug]: ALPHA: Corrupted validation of register contents

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#61]
### Discord Thread

https://discord.com/channels/828292123936948244/1264677855867174932

### What happened?

The orange popup showing problems with the current test, shows artifacts and the validation doesn't pass.
![image](https://github.com/user-attachments/assets/29bd7539-b6cf-4bf4-9ca8-f4e36b775729)

### Version

0.1070 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed
