### ISSUE TITLE
[Bug]: Storage Tracker Challenge possible bug allowed me to complete level

### ISSUE THREAD

**Issue by joeack123** [Turing-Complete-Game/Suggestions-and-Issues#61]
### What happened?

1
output_0
jump

This was the code in my IDE.

1 is immediate.
output_0 for outputting registry 0.
jump is condition always
![turning-complete-bug](https://user-images.githubusercontent.com/22087351/142075288-04ce5652-9759-48b1-91c0-ee95bc9242c3.png)

### Version

Latest

### Operating System

Windows 11 Pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
Duplicate of #28
