### ISSUE TITLE
[Bug]: Components do not save if last action cleared is a loop

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#62]
### What happened?

Report from [This Conversation](https://discord.com/channels/828292123936948244/850737218759032892/910295523787935795) with user `Jesse`

Upon fixing a logic loop and exiting the component factory, the changes are not saved properly.

![Gif](https://cdn.discordapp.com/attachments/850737218759032892/910295520872910948/wwtZPVojPi.gif)
**Image is not looping for the first few times. Wire Removal is not saved**

### Version

Latest

### Operating System

Unknown

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed next update
