### ISSUE TITLE
[Bug]: ALPHA: CTD on launch, MacOS 15 Sequoia M1

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#62]
### Discord Thread

https://discord.com/channels/828292123936948244/1264692783998828706

### What happened?

Getting the following error when trying to launch the alpha on an Apple Silicon device running MacOS 15 beta:
```
Variable .global_seed not in scope.
(586) 
    .global_seed = <Seed> 1
```
(Reported by Knedlik on Discord, version number unclear)

### Version

0.1070 Beta (maybe)

### What OSes are you seeing the problem on?

MacOS

**Comment by Stuffe** [comment]
fixed
