### ISSUE TITLE
[Bug]: ALPHA: Output pins of the same "Splitter" component issue

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#63]
### Discord Thread

https://discord.com/channels/828292123936948244/1264692775677460663

### What happened?

Connecting both output pins of the same splitter doesn't create a circular dependency

(Reported by Think on Discord)

### Version

0.1069 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
