### ISSUE TITLE
[Bug]: ALPHA: All levels have custom components available

### ISSUE THREAD

**Issue by MiaFoxcat** [Turing-Complete-Game/Suggestions-and-Issues#64]
### Discord Thread

https://discord.com/channels/828292123936948244/1264706199274918031

### What happened?

Self-explanatory -> create a component in sandbox, then you can use it in the campaign no matter the level.

### Version

0.1070 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
this is intended
