### ISSUE TITLE
[Bug]: Copy Paste missing pins/NULL

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#64]
### What happened?

This is the bug Jesse was [reporting](https://discord.com/channels/828292123936948244/850737218759032892/909971033623261234). With doing stuff similar to this video, I can reliably reproduce this issue (especially the NULL part) What exactly is causing it I am not sure about. It seems to related to copying a deleted wire.

https://user-images.githubusercontent.com/26136419/142148182-ad65c2f5-0581-4d6b-aa0a-03b97e5db44b.mp4

Note that I did finish completing placing the wire that seems deleted, but it immediately disappeared.

### Version

Development

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
Here an example without custom components. It appears that the selection needs at least some complexity from wires and pins.

The procedure is this:

- make sure that when pasting the selection sometimes pins disappear.
- Select the stuff, CTRL+C
- Draw a wire (without deselecting the stuff? might not be required)
- CTRL+V
- If the wire didn't disappear, delete it and go back two steps
- If the wire disappeared, you now have a NULL wire. placing the current pasted stuff doesn't crash the game.
- If you now select the stuff again, and speciffically where one of the end points of the NULL wire is, you then have NULL in the stuff you can paste. While it hovers it's fine and just is the text NULL. If you place it, the game crashes
- If you reload the save file, the wire reappears.
- If you reloaded it without closing the game, deleting the NULL wire crashes the game (might not be true)

https://user-images.githubusercontent.com/26136419/142150010-4a6e9b40-0495-4cc6-9b16-8fbcdb5948b0.mp4

**Comment by Stuffe** [comment]
@MegaIng I think this is fixed in the dev branch, would you check?

**Comment by MegaIng** [comment]
@Stuffe This seems to be fixed!
