### ISSUE TITLE
[Bug]: Components disappearing

### ISSUE THREAD

**Issue by JamesWHollis** [Turing-Complete-Game/Suggestions-and-Issues#65]
### What happened?

I am currently on The Maze. I just loaded up the game to find my instruction decoder missing from my schematic, along with the six RegisterPlus's that were placed for me.

[Turing Complete.zip](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/7555436/Turing.Complete.zip)

### Version

Latest

### Operating System

Windows 10 Home

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
When was the last time you played? There was a rework of custom components a week or so ago that might have removed them.

**Comment by Stuffe** [comment]
I am pretty sure this was a temporary issue caused by the save upgrade
