### ISSUE TITLE
[Bug]: ALPHA: Bug in Double the number level

### ISSUE THREAD

**Issue by McModknower** [Turing-Complete-Game/Suggestions-and-Issues#66]
### Discord Thread

https://discord.com/channels/828292123936948244/1264754452351553649

### What happened?

Double the number uses signed numbers for the expected result, which a simple leftshift can not do.

It worked some time between yesterday (sunday 2024-07-21) and today (monday 2024-07-22 15:36 CEST) for me

### Version

0.1073 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by ghost** [comment]
user on discord reported the bug also affects him on windows platform

**Comment by Stuffe** [comment]
Fixed
