### ISSUE TITLE
[Bug]: ALPHA: CTRL-T does not activate wire comment tool

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#67]
### Discord Thread

https://discord.com/channels/828292123936948244/1264970160809185310

### What happened?

Using the default CTRL-T key combo doesn't activate the wire comment tool.
Using the mouse on the UI control works, so this keyboard shortcut issue is not a blocker.

### Version

0.1074 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
