### ISSUE TITLE
[Bug]: ALPHA: Assembler missing restrictions

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#68]
### Discord Thread

https://discord.com/channels/828292123936948244/1264930782061793322

### What happened?

Assembler allows creating value names with symbols in them while defining fields as seen on the first picture. Whenever game is reloaded this error pops up and game crashes (second picture)
![image](https://github.com/user-attachments/assets/da00d323-2285-4a4c-b5c4-509a3fa90739)
![image](https://github.com/user-attachments/assets/b4caa4c1-013a-4162-a15d-3d75622051f7)
(Reported by Think on Discord)

### Version

0.1074 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
