### ISSUE TITLE
[Request]: Selection mode options

### ISSUE THREAD

**Issue by tp1212** [Turing-Complete-Game/Suggestions-and-Issues#68]
### Request?

I think it might be nice to have the option to choose how the selection mode operate,
Specifically these 3 modes: 
1. Fully enclosed, only select objects that fall entirely within the selection bounding box, (which is my personal preference)
2. Centre, only select objects whose centre falls within the selection bounding box. (Which is the current behaviour I think?)
3. Any, Select anything that has even slight overlap with the selection bounding box. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Selection has been redone
