### ISSUE TITLE
[Bug]: ALPHA: Assembler line preview incorrect

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#69]
### Discord Thread

https://discord.com/channels/828292123936948244/1264932462241513472

### What happened?

The highlighted line preview in the assembler component just follows the input number, ignoring word length or blank lines or labels etc etc
(I assume this is placeholder logic until the assembler is more finished and the actual byte offset can be calculated?)
![image](https://github.com/user-attachments/assets/23080248-5ee8-4f6b-93b6-e18d6acb0d16)

### Version

0.1074 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
