### ISSUE TITLE
[Request]: Don't kick to menu by default after completing levels

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#7]
### Request?

Especially in the Late game where optimization is something to strive for, Being kicked to the level select and having to reload the level for testing every optimization can get tedious. And in some cases leads to lower performance after a large number of level reloads.

Any level that rewards the player with a new feature or component displays the Onwards Menu, which can be X'd out of to continue working on the level. 
Suggesting a success window be shown on All levels that do not already display this menu.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
