### ISSUE TITLE
Allow nested components to show value summaries.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#71]
### Request?

Right now, if you place a 1-bit memory or a register in a component, it will populate the component tile with the value of the built-in (on/off icon for the 1bm and numeric value for the register).

My suggestion is to make this transitive to multi-level components.  If a component on level 1 contains one of those items and you place that L1 component on an L2 component, have the L2 component show the L1 component's value.

Of course if the L1 component has multiple values (or you place multiple L1 components in the same L2 tile), a choice would need to be made as to which value to display - the same as is currently done when you place two registers in the same tile in a normal L1 component.

(As a bonus, if a tile/L1 component contains between 2-8 memory cells, you could convert that to a numeric display on the L2 or level schematic.. no idea how much extra work it would be to figure that out though, in terms of either programming time or execution time!)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I would like this request to be extended to a bit more, and maybe that is already planned: Allows us to complete customize the information displayed on a custom component (with a small scripting language maybe ;-)): E.g. different texts (LOAD/SAVE for example for the action being done), the (floating point) numeric value, ...

**Comment by Arnavion** [comment]
I suggest making a new component that has the Register's "my value is shown on top of the embedding component" behavior and can be fed the value from a byte wire.

As a use case, my LEG counter has only six 1-bit memories and I want to visualize it as a decimal number. So if such a component existed, I'd wire up those six bits into a byte maker and then the byte maker to this component.

This component should also be treated as a watchable thing in the Program component's watched states.

**Comment by Stuffe** [comment]
Yes the plan is to have a special "component" that displays whatever watched state it is hooked up to. This display component will then also have a watched state so you can bubble up the state of something nested several layers below and even hook it up to your program

**Comment by SunCatMC** [comment]
was fixed with addition of watchable state components
