### ISSUE TITLE
[Bug]: ALPHA: Renaming a folder in the component factory causes a crash

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#71]
### Discord Thread

https://discord.com/channels/828292123936948244/1264938400188989521

### What happened?

Renaming a folder in the component factory causes a crash
Produces the crash log:
```
Turing Complete 0.1070 Beta on Windows
fatal.nim(54)            sysFatal
Error: unhandled exception: custom_prototype.nim(226, 10) `custom_id != 0`  [AssertionDefect]
```

(Reported by Oreo on Discord)

### Version

0.1070 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
