### ISSUE TITLE
[Bug]: ALPHA: Expected "Conditions" solution not accepted

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#72]
### Discord Thread

https://discord.com/channels/828292123936948244/1264976732189102174

### What happened?

I'd expect this solution to pass the Conditions level, but it fails at tick 12 for "-44 < 0 should be ON".
This circuit *is* outputting ON.
![image](https://github.com/user-attachments/assets/eab7b04c-e6af-4308-b120-fe54946028cd)

### Version

0.1074 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
