### ISSUE TITLE
[Bug]: ALPHA: Crash on entering `-` in assembler field expecting an integer

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#73]
### Discord Thread

https://discord.com/channels/828292123936948244/1264978045681406033

### What happened?

Typing a minus sign into the instruction field when it is expecting an integer causes a crash, and requires save editing to undo.
negative numbers function as expected, but require typing the number portion first, and the minus sign doesn't inherit the syntax highlighting

### Version

0.10733 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Turing Complete 0.1073 Beta on Windows
strutils.nim(1072)       parseInt
Error: unhandled exception: invalid integer: - [ValueError]
```

**Comment by Stuffe** [comment]
I think this was fixed
