### ISSUE TITLE
[Request]: Overture instruction decoder level should be renamed

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#73]
### Request?

The instruction decoder level for overture which is named "Decoder" in game should be renamed to "Instruction Decoder" or something similar because it's current name might confuse people with the 1 bit and 3 bit decoders since they were renamed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Done next update
