### ISSUE TITLE
[Bug]: Steam sync issues

### ISSUE THREAD

**Issue by elfrea** [Turing-Complete-Game/Suggestions-and-Issues#74]
### What happened?

Since the last version, my saved games are all messed up. (I play on two computers, so it uses the cloud to save the game).
Usually it's not that much of a problem, but my last time, I'll probably have to start all over again from scratch (I was at the last level) Save bugs seems to occur in components. I'll start the game, my wiring is all fucked up (well not all, but lets say the last time there was 10 connections connected to nothing at all. When stuff wasn't too bad and the conenctions were intact, each time I started the game, I had to go in my components manually 1 by 1 or else my computer was behaving strangely, it's like it didn't load everything correctly the first time. Also, when I write programs on 1 computer, the programs are unavailable in the cloud save. Also, If I create folders for components, things get all messed up on the other computer, the folders arent there.
It is so frustrating to lose data in the game. I don;t care when the game crashes, but I have like 1 hour of work everyday to redo what I did the last night!

### Version

Latest

### Operating System

Win 10 - Win 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
By latest version you mean 0.303 Beta, right? Do you happen to remember what version you were on before? The last save file format change is AFAIK more than a week ago.

**Comment by elfrea** [comment]
I don't remember, but Ive been having problem with saved games for about a week now. It's always in a component where it has components I think. I'm not sure, but I think when I make modifications on one component and change its layout, when I get on the other computer, the wiring gets fucked up... For exemple, I created a component for my ALU, in that component, I have 1 component for ALU_LOGIC, one for ALU_OPER and 1 for ALU_FUNC. If I change the layout of ALU_LOGIC on one computer, quit the game and wait till it saves on the cloud, when I get on my other computer, all the wiring of ALU_LOGIC get messed up. It was not such a problem at firsst, but now it's getting so complex that I have to revise all my ALU wiring logic to be able to repair it. And as I said when I save a program on one computer, if I go on the other, the program is gone. There's definitely a nasty bug with the saved games for sure, at least the cloud save...

**Comment by elfrea** [comment]
when I say :" all the wiring of ALU_LOGIC get messed up", I mean the the ALU component, all the wiring that was attached to the component I changed (ALU_LOGIC) gets messed up. all the connections are near, but not where they are supposed to be. some connects to other wires around, some connects nowehre, some connects on the component, but at the wrong pin, and some connects correctly. So imagine the headache haha

**Comment by elfrea** [comment]
but hey, it might be the best game ive playe so far in the last 30 years, so three thumbs up, I just hope you'll find the bugs! (I wish you could save many diferent games (or profile), at least I could use a different profile on each computer without problems
!

**Comment by MegaIng** [comment]
@elfrea Did you upload your save folder(s) to https://turingcomplete.game/report_bug ? If not, upload and mention this issue.

Please upload the save folders from both computers. To me it sounds like there is a version difference between the PCs. Are you sure you are on the same version on both PCs?

(btw, I am not the dev)

**Comment by elfrea** [comment]
oh, yes same version, i use steam so it auto updates everytime

**Comment by Arnavion** [comment]
>each time I started the game, I had to go in my components manually 1 by 1 or else my computer was behaving strangely, it's like it didn't load everything correctly the first time.

Yes, nested components have that bug. You have to open them in the component factory for them to work, otherwise they aren't simulated at all so they don't output anything.
