### ISSUE TITLE
[Bug]: Alpha: Copy-Pasting between arch levels doesn't include CCs

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#74]
### Discord Thread

https://discord.com/channels/828292123936948244/1265006258436571267

### What happened?

* Select all the the circuit (with CTRL-A), in e.g. Program level, this seems to select everything including custom components.
* Copy (with CTRL-C).
* Switch to e.g. Turing Complete level.
* Paste (with CTRL-V), this pastes in all the wires and built in components, but doesn't include any custom ones.

### Version

0.1074 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
