### ISSUE TITLE
Rename "decoder" level

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#75]
### Request?

With the 1-bit and 3-bit demux being renamed as decoders, it might be helpful to rename the "Decoder" level to something like "Instruction Decoder" just to differentiate it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
*Exact* duplicate of #73

**Comment by altrag** [comment]
Woops I should look before I type :D.  Closing.
