### ISSUE TITLE
[Bug]: Alpha: Component Factory menu icon missing in Overture levels

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#75]
### Discord Thread

https://discord.com/channels/828292123936948244/1265007490962296839

### What happened?

I'd expect the Component Factory menu item to be present in the Overture building levels.
It is not there.

This might be related to #74 

### Version

0.1074 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
