### ISSUE TITLE
[Bug]: Incorrect Register (and Delay Line?) behaviour

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#76]
### Discord Thread

https://discord.com/channels/828292123936948244/1265007718721257626

### What happened?

Register output doesn't update. Also in both cases the 'Result' wires only contain on and 255 on tick 1 (0 on other ticks).

I'd expect the 'Result' wires to always contain the values on and 255 except for the first tick, as the delay line inputs don't change (which they should, as the registers have read and write enabled).
Unsure if this should cause a circular dependency. Delay line behaviour is probably caused by the strange register behaviour.

(Image in discord)
### Version

1.074 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think this was fixed
