### ISSUE TITLE
1-bit decoder reliably crashes the game.

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#76]
### What happened?

When the new 1-bit decoder is on the schematic at all (doesn't even have to be connected to anything), the game crashes 100% of the time upon flipping any bit of any input on the schematic.

Happens in both levels and the component factory.

0.305 Beta

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altrag** [comment]
Zip of save folder sent to bug report form.

**Comment by MegaIng** [comment]
Can reproduce this.

**Comment by Stuffe** [comment]
I don't think this is the case anymore
