### ISSUE TITLE
[Bug]: Instruction decoder level has COPY and CALC reversed

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#77]
### What happened?

The instruction decoder level for OVERTURE has the COPY and CALC outputs reversed

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I swapped the order, so I don't think this is the case if you create a new schematic before solving the level
