### ISSUE TITLE
[Bug]: Alpha: Crash by defining number in binary format

### ISSUE THREAD

**Issue by Pr0sT69** [Turing-Complete-Game/Suggestions-and-Issues#77]
### Discord Thread

https://discord.com/channels/828292123936948244/1265060009365213264

### What happened?

By defining an integer number in the assembler with `<U8> 0b` the game saves the .asm file and crashes. The game keeps crashing if loading the same save again. Changing the line in the .asm file to a valid number like `<U8> 0b00000000` or removing the line fixes the crash. The crash can easily be circumvented if one first writes the valid number out and after that prefixes the Int size 

### Version

0.1074 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
fixed
