### ISSUE TITLE
[Bug]: ALPHA: "The Bus" does not allow Z state output

### ISSUE THREAD

**Issue by McModknower** [Turing-Complete-Game/Suggestions-and-Issues#78]
### Discord Thread

https://discord.com/channels/828292123936948244/1265345274335985724

### What happened?

in 0.1076 the bus does not allow Z state output for the disabled output. This prevents you from solving that level.

### Version

0.1076 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
Now it does
