### ISSUE TITLE
[Bug]: ALPHA: Multibyte constants in assembler are big endian

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#79]
### Discord Thread

https://discord.com/channels/828292123936948244/1265392713600336116

### What happened?

In the assembler <U32>0x4321 is stored as [0, 0, 43, 21, ...] . If the width is set to 32 bits the output on the wire is 21430000.
This is contrary to expectation (little endian, output 00004321) , in particular the manual stating (correctly) that little endian is more common.

![image](https://github.com/user-attachments/assets/33f643f4-a8ce-42e7-9903-c3b82f96da10)

Windows, version 0.1076 Beta.
(All numbers in hex).

### Version

0.1076 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This was fixed
