### ISSUE TITLE
[Request]: Option to Skip Level Intro's

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#8]
### Request?

Requesting an Option to skip the Level Log when loading a completed level.

The level info is Always viewable via the `Level Log` option.

More relevant to Endgame Users who are focusing on Optimizing their solutions and want to get Right into it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scottanderson** [comment]
These messages contain critical information for solving the levels, however after completing the level it would be nice to  unlock a "do not display this message again" checkbox.

**Comment by Stuffe** [comment]
Completed levels now don't show the level log when entering
