### ISSUE TITLE
[Bug]: ALPHA: 32-bit LSR Shift Right component wrong output

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#80]
### Discord Thread

https://discord.com/channels/828292123936948244/1265397748581273731

### What happened?

`3 LSR 3` should be zero. It shows on the wire as `60000000` (hex).
Strangely the value the delay line (and its output wire) reports is zero.
IIRC there are other reported issues regarding incorrect values on wires: Possibly related to #76 

![image](https://github.com/user-attachments/assets/ad0c5a72-d9e6-4af2-8a67-8889536dc3f9)

### Version

0.1076 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
