### ISSUE TITLE
Rotating a selection seems to have gotten broken

### ISSUE THREAD

**Issue by altrag** [Turing-Complete-Game/Suggestions-and-Issues#81]
### What happened?

As the title says.  I was trying to copy a rotated version of a piece of schematic into another one and ended up with the mess in the screenshot.  (Edit:  Looking closer it appears to only be the wires that got doubled up.. the components don't seem to be in the original un-rotated ghost).

Pasting correctly put down the rotated version though, so that's good at least.

![image](https://user-images.githubusercontent.com/59858259/142739979-5905584d-a8b0-43ec-9f97-8f5867fa0909.png)

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Fixed next version
