### ISSUE TITLE
[Bug]: Crash when placing 128-bit input pin

### ISSUE THREAD

**Issue by MJE10** [Turing-Complete-Game/Suggestions-and-Issues#81]
### Discord Thread

https://discord.com/channels/828292123936948244/1265501568757924021

### What happened?

From conversations in the discord, it seems like this currently isn't supported. However, it does still cause a crash and break the schematic if you set the bit width tool to 128 and then try to place an input pin (in the component factory).

### Version

0.1076 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1076 Beta on Windows
```

**Comment by Stuffe** [comment]
you can't do this anymore
