### ISSUE TITLE
[Bug]: instructions editor corruption 

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#82]
### What happened?

when i would add a new one it would seem to merge with an older one sometimes so i closed and reopened the window it it seems it did not save all the things i just added to it correctly.. before i closed and reopened it the original "merged" where still in the list along with the new ones as far as i notice at the time
![image](https://user-images.githubusercontent.com/61679450/142742461-fab28f6c-1d09-438e-9e5c-28431f8ba2fb.png)

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I don't really understand what you mean. Can you give more precise steps to reproduce?

If you just mean the overlapping label names on the top, that is known (although there isn't an issue ATM).

**Comment by fifthFunction** [comment]
so i quit and reopened the game
took a screen shot of all the instructions i had there
then added 3 new ones
![afgvcdfgtnfgn](https://user-images.githubusercontent.com/61679450/143149188-6ce705ea-0b9b-44c7-85e1-cea23ae0cb4d.png)
then closed and reopened the "instructions" and this is what it looks like
![afsdegfrth](https://user-images.githubusercontent.com/61679450/143150549-6fee24bb-5103-46f4-b167-ca229584fdb2.png)
one of the instructions is missing and replaced with nothing and it was the first of the 3 i added

sometimes when adding more than 1 instruction at a time the last one i added would change or simply disappear(maybe move?) but that did not happen when getting the screenshots this time (it did when testing just before the screenshots)

things like this are happening every time i try to add new instructions but changing/removing existing ones dont seem to cause a problem tho

sorry i was very tired when i opened the original report XD i hope this cleared things up
