### ISSUE TITLE
[Bug]: programs changing in levels

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#83]
### What happened?

programs seem to change around entering the sandbox
![image](https://user-images.githubusercontent.com/61679450/142742674-b7b9c0ba-b19f-46e8-9d40-53c76ed3c4ed.png)

### Version

Latest

### Operating System

win 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed
