### ISSUE TITLE
[Bug]: ALPHA: Weird switch "On Z-State" behaviour

### ISSUE THREAD

**Issue by MutexRaceCondition** [Turing-Complete-Game/Suggestions-and-Issues#83]
### Discord Thread

https://discord.com/channels/828292123936948244/1265741791060164811

### What happened?

The z-output of a disabled switch visually keeps the last value it had when it was last enabled, creating the two states shown with blue. When inputted into most gates (like the not-gate), this z-state appears to behaves just as that last value. However, when inputting a value dependent on the "on z-state" into a delay line, the input appears as if the "on z-state" is treated as an "on-value", while the delay line and its output appear as if the "on z-state" was treated as an "off-value" (shown in red). Does not happen with the "off z-state", it always acts as a "off-value".
![image](https://github.com/user-attachments/assets/3eb5fafa-9ede-4384-b7d5-4ba66b1fbfc4)

### Version

0.1080

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think this is fixed. The only issue left is the pin color shouldn't be green when disabled, right?

**Comment by MutexRaceCondition** [comment]
Still behaves the same in 1.083. I don't know whether the visual behaviour (output acts as green) or the actual behaviour (output acts as red) is the indented way, but they are currently not the same.

**Comment by Stuffe** [comment]
fixed next patch
