### ISSUE TITLE
[Bug]: breakpoints are not unique to each program

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#84]
### What happened?

the title says it all... if you set a breakpoint on line 7 in one program, there's automatically a breakpoint on line 7 in all of them
![image](https://user-images.githubusercontent.com/61679450/142743617-ef1b80b2-eeb6-41b4-b10e-422130274b47.png)

### Version

Latest

### Operating System

win 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I can't reproduce this. Anyone else?

**Comment by MegaIng** [comment]
I thought I could original reproduce this to a higher degree, maybe the assembler rework had an effect.

Anyway, what I can still reproduce is that the breakpoints are not unique to one Program Component, but to an assembly file. E.g. multiple different Program Components that have the same Assembly file open share breakpoints.
