### ISSUE TITLE
[Bug]: 7 segment display offset

### ISSUE THREAD

**Issue by nekokiwa** [Turing-Complete-Game/Suggestions-and-Issues#84]
### Discord Thread

https://discord.com/channels/828292123936948244/1265805992273121304

### What happened?

The 7 segment display component has the numbers offset from the component.

![image](https://github.com/user-attachments/assets/9aba77d5-1c76-441a-9887-1dce658720a7)

### Version

0.1080 Beta

### What OSes are you seeing the problem on?

Windows

### Relevant `debug.log` output, search next to the exectuable

```shell
Godot Engine v3.4.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL ES Batching: ON
 
Turing Complete 0.1080 Beta on Windows
```

**Comment by Stuffe** [comment]
fixed next patch
