### ISSUE TITLE
[Bug]: Custom components with static value or probe missing name

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#85]
### Discord Thread

https://discord.com/channels/828292123936948244/1265912704145555486

### What happened?

Custom components that have a static value or a probe on their shape don't have a name on them
This makes some sense for small components but for larger customs the missing name is noticeable

![image](https://github.com/user-attachments/assets/dea814d3-3c61-4792-a115-0371799bf9bf)

### Version

0.1080 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This is intended
