### ISSUE TITLE
[Bug]: Static values in custom components break mouseover

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#86]
### Discord Thread

https://discord.com/channels/828292123936948244/1265916894121037844

### What happened?

Hard behaviour to describe, see the video
Static values aren't "mouse-over-able" in the component tree, and make especially small components slightly annoying to select

https://github.com/user-attachments/assets/74af0d44-5806-4d32-8c9c-7952ac304611

### Version

0.1080 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
