### ISSUE TITLE
[Bug]: Changing the label text on a 1 bit output caused it to stop working

### ISSUE THREAD

**Issue by SAdermann** [Turing-Complete-Game/Suggestions-and-Issues#87]
### What happened?

I was trying to see if I could implement an ALU for a 6502 processor. I had it all working and at the end I decided to add a 1-bit output to indicate when the ALU had decoded an instruction and produced a result. The output was working as intended, but when I renamed it to "Valid" it would no longer light up. The connected trace (from an OR) would be green but the output stayed red. It was green when I clicked it to change the name, so I know it was working before.

I deleted the output and the trace, placed a new output, renamed it and then added a trace and it started working.

v0.303 beta

### Version

Latest

### Operating System

Win10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Please upload your save folder here: https://turingcomplete.game/report_bug
Also please add the description or a link to this issue when you do as I go through a lot of messages each day

And that sounds like a really cool project!

**Comment by SAdermann** [comment]
I refiled the bug there and uploaded my save folder, but I’m no longer able to recreate the problem even if I revert to one of the earlier versions of the component in question.

 

Just FYI on the 6502 project, an interesting problem is how to deal with variable sized instructions, combined with how to deal with instructions that take multiple cycles to execute. You can’t use a counter because it wants to tick up by a set amount each tick. It seems it has to be a register with an input that gives the size of the instruction (or the instruction itself so the register can calculate the size), plus an extra countdown so that you can take extra steps (like retrieving a value from memory so you can jump to it) before the actual Program Counter advances. Kind of tricky since you guys don’t expose the clock (not counting the system clock) as a separate signal.

 

Stan

**Comment by MegaIng** [comment]
I can reproduce this. Create a very simple custom component:

![image](https://user-images.githubusercontent.com/26136419/143098694-fb63bdd2-fa8b-4b65-a8fd-41ee14cd2e2f.png)

Rename the output (this needs to be the last edit), then step simulation: The output doesn't light up

![image](https://user-images.githubusercontent.com/26136419/143098811-88978116-a6a5-4b80-b979-3db3bd3c5523.png)


Note that this is purely visual and has not effect on how the component behaves.

**Comment by SunCatMC** [comment]
looks like as of 0.544 this is fixed (tested both with delay buffer and without it)
