### ISSUE TITLE
[Bug]: ALPHA: Crash while selecting "instruction" in ROM component

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#87]
### Discord Thread

https://discord.com/channels/828292123936948244/1265775182602178591

### What happened?

Crash while selecting "instruction" in ROM component
reproducible

add field breaks too

![image](https://github.com/user-attachments/assets/51cb1442-f127-403a-94a4-42d7d7460fcf)

(There is no ROM component - is it the Front Panel?, If so Gelthor can't repro in version 0.1081)

(Reported by Tanner07 on Discord)

### Version

0.1080 Beta ?

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
the button is now hidden
