### ISSUE TITLE
[Bug]: Crash on entering Overture 2

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#88]
### Discord Thread

https://discord.com/channels/828292123936948244/1265839324394684477

### What happened?

Crashes on launch when Overture 2 is the last accessed level, requires save editing to fix.

Console output:
```
Turing Complete 0.1080 Beta on Windows
fatal.nim(54)            sysFatal
Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]
```

### Version

 0.1080 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
This was fixed
