### ISSUE TITLE
[Bug]: ALPHA: Combination Drag wire + RMB + ESC crashes the game

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#89]
### Discord Thread

https://discord.com/channels/828292123936948244/1264699215532265615

### What happened?

Combination Drag wire + RMB + ESC crashes the game
Self-explanatory - has to be during a wire drag, any other situation is fine.

Possibly related to #44, but that got fixed.

(Reported by Knedlik on Discord)

### Version

0.1079 Beta and 0.1081 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
I think this is fixed in the next patch
