### ISSUE TITLE
[Bug]: Crash on editing Program when using a 64 bit watched state

### ISSUE THREAD

**Issue by trollbreeder** [Turing-Complete-Game/Suggestions-and-Issues#89]
### What happened?

Build: 0.211 Beta

When you connect the watched state of a component's 64 bit output to the Program component, and then edit your program, the game crashes.
Recreation:
Step 1. Visit the sandbox.
Step 2. Place a Program and a 64 bit Register.
Step 3. Connect the Register to something, for example a 64 bit Splitter.
Step 4. Edit watched state and connect the Program 0 to the circuit watched state of the Register.
Step 5. Edit the Program.
Expected: 64 bit watched state showing and working as intended, showing its value.
Result: Game crash, quit to desktop without error message

### Version

Other

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Arnavion** [comment]
All the issues you reported are from an ancient build. 0.303 beta is the current one.

**Comment by MegaIng** [comment]
This seems to have been fixed already. If you still find this in the most recent versions, feel free to reopen, but the steps you gave don't crash for me.
