### ISSUE TITLE
[Bug]: Crash when placing the DIV component.

### ISSUE THREAD

**Issue by technod999** [Turing-Complete-Game/Suggestions-and-Issues#9]
### Discord Thread

https://discord.com/channels/828292123936948244/1264177636016394331

### What happened?

As title. Placing the div component causes a divide by zero error.
Can be placed fine down onto existing wires, but if those at any point are zero, same crash occurs.
![image](https://github.com/user-attachments/assets/c8b8fa34-257e-4a14-8e65-f4ddff1099c6)

### Version

0.1066 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
There is no way to turn off SIGFPE hardware faults. The best you can do is write a signal handler which jumps back, but this would be too much work rn.
I am considering adding a cmov in front of the div, where I overwrite the dividend with the stack pointer if it is 0. cmov only works with registers and the stack pointer is the only register I know for sure isn't 0. Any have any other ideas?
