### ISSUE TITLE
[Bug]: Fonts do not render correctly

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#9]
### What happened?

Fonts don't scale properly, causing severe aliasing. Even at maximum zoom (image below), RAM data remains difficult to read.

![image](https://user-images.githubusercontent.com/662325/140809037-2929f13d-24d7-4380-96f5-591a474660ff.png)

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
fixed 0.290
