### ISSUE TITLE
[Bug]: 64 bit memory components do not have their own special watched state

### ISSUE THREAD

**Issue by trollbreeder** [Turing-Complete-Game/Suggestions-and-Issues#90]
### What happened?

Build: 0.211 Beta
64 bit components that remember such as 64 bit Memory, 64 bit Registers, or 64 bit Counters do not have a special watched state output.
A normal byte register does have this.
![image](https://user-images.githubusercontent.com/25937686/142768302-0550831b-a58f-4d41-96d2-c71020f6a396.png)

Step 1. Place a Program, a 64 bit Register, and a normal Register.
Step 2. Edit watched state and look at the 64 bit Register. 
Expected: The 64 bit Register has a slightly bigger than usual cyan circle in the top left that would give extra detail over its state if connected, just like the normal Register.
Result: The 64 bit Register doesn't have this big cyan circle.

### Version

Other

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Old version

**Comment by MegaIng** [comment]
@Stuffe Yes, but still an issue on the newest development version.

**Comment by SunCatMC** [comment]
fixed as of 0.544
