### ISSUE TITLE
[Bug]: ALPHA: NOT gate visual not updated on Z input

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#90]
### Discord Thread

https://discord.com/channels/828292123936948244/1265964175373500467

### What happened?

On the bottom NOT gate has in input of Z. This gate appears to be outputting OFF, but the delay line is showing the output wire of the NOT as ON. I'd expect the later to be correct.
Compare the visual with the 2 upper circuits, which show the NOT with expected outputs.

![image](https://github.com/user-attachments/assets/1f865d67-b397-498e-85bc-4d9ff83e32eb)

### Version

0.1081 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
