### ISSUE TITLE
[Bug]: ALPHA: Parse error with single letter assembly mnemonic

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#91]
### Discord Thread

https://discord.com/channels/828292123936948244/1265989093893079123

### What happened?

I get a parse/syntax error ```
Was expecting the instruction to end here.
``` when I define a single letter `j` instruction as well as a longer `jmp`.
I only see it with an instructions that takes a label, similar instructions with an immediate don't seem to trigger this.
Switching the order of the definitions appears to mask this.

![image](https://github.com/user-attachments/assets/54d1caea-8635-4a43-a396-4f568e51c3a7)

Workaround: Use a longer asm mnemonic.

### Version

0.1081 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
