### ISSUE TITLE
[Bug]: Wrong description on the 64 bit Maker

### ISSUE THREAD

**Issue by trollbreeder** [Turing-Complete-Game/Suggestions-and-Issues#91]
### What happened?

Build: 0.211 Beta

The 64 Bit Maker has the same description has the Byte Maker, which is wrong. The 64 bit Splitter doesn't have this issue.
![image](https://user-images.githubusercontent.com/25937686/142768490-98276e98-0219-4f2d-841c-db78ab4f28db.png)

Step 1. Hover over the 64 bit Maker's icon in the component category 64BIT.
Expected: "Turns 8 bytes into 64 bits"
Result: "Turns 8 bits into a byte"

### Version

Other

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
This is a really old version of the game

**Comment by MegaIng** [comment]
@Stuffe Yes, but this issue still exists.

**Comment by Stuffe** [comment]
fixed next version
