### ISSUE TITLE
[Bug]: Bogus entry in the manual

### ISSUE THREAD

**Issue by trollbreeder** [Turing-Complete-Game/Suggestions-and-Issues#92]
### What happened?

Build: 0.211 Beta

There's a fake duplicate entry in the manual for the Assembly editor. I don't know when it got there, but it haunts my manual. It probably appeared somewhere around the OVERTURE levels? I'm not sure.

The real entry:
![image](https://user-images.githubusercontent.com/25937686/142768570-4d00b8f3-665e-4f78-83cc-6770121550f7.png)
The impostor entry:
![image](https://user-images.githubusercontent.com/25937686/142768580-2e59c8e4-ca16-4031-a214-42e66cddc37c.png)

### Version

Other

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
this was fixed long ago
