### ISSUE TITLE
[Bug]: ALPHA: Pressing ESC while pasting selection does not behave correctly

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#92]
### Discord Thread

https://discord.com/channels/828292123936948244/1265994213720457226

### What happened?

Pressing ESC while pasting a selection will make all grayed out components stay in place and wires follow the cursor
It should behave the same as pressing RMB

(Reportyed by getItemFromBlock on Discord)

### Version

0.1081 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed
