### ISSUE TITLE
[Bug]: Certain text strings do not change based on bindings

### ISSUE THREAD

**Issue by trollbreeder** [Turing-Complete-Game/Suggestions-and-Issues#93]
### What happened?

Build: 0.211 Beta

Some text strings in the game display the default binds instead of the user's.

- the manual page for "The robot" (Use **arrow keys** to play around, etc...)
![image](https://user-images.githubusercontent.com/25937686/142768856-a2a729e6-653d-49d3-9e9c-789f19e45da1.png)
- the level Water World's display (Hit **ENTER** to show water)
![image](https://user-images.githubusercontent.com/25937686/142768830-fa9a1042-f9a7-4548-bf3c-d3cd6c8f44cd.png)
- the level AI Showdown's display (Use **arrow keys** to select cards) (**ENTER**: Take 2 cards)
![image](https://user-images.githubusercontent.com/25937686/142768844-54339caa-26f2-4f0a-a890-43c0e97beda7.png)
![image](https://user-images.githubusercontent.com/25937686/142768849-0206c39a-76bb-4913-a5f8-bef7b0402d3e.png)

### Version

Other

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Those can no longer be changed (in preparation of custom levels)
