### ISSUE TITLE
[Bug]: ALPHA: Assembly specification editor deletes my entire instruction if it contains an error

### ISSUE THREAD

**Issue by piotrsiupa** [Turing-Complete-Game/Suggestions-and-Issues#96]
### Discord Thread

https://discord.com/channels/828292123936948244/1266147176489422959

### What happened?

If the current instruction has a syntax error, it's reverted as soon as you click on anything else.
![Peek 2024-07-25 23-35](https://github.com/user-attachments/assets/545660cb-2b68-4dc9-9efc-5652a678604e)

### Version

0.1083 Beta

### What OSes are you seeing the problem on?

Linux

**Comment by Stuffe** [comment]
next patch errors show up as you type so you will know immediately if the change works
