### ISSUE TITLE
[Bug]: ALPHA: Wrong wire colors

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#98]
### Discord Thread

https://discord.com/channels/828292123936948244/1266179517278326836

### What happened?

Disabled colored wires have a default color overlay

![image](https://github.com/user-attachments/assets/45cebfd3-3cd3-41c9-8516-7a62f16c35c0)

(reported by think on Discord)

### Version

0.1083 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
