### ISSUE TITLE
[Request]: Character set support

### ISSUE THREAD

**Issue by asd142513** [Turing-Complete-Game/Suggestions-and-Issues#99]
### Request?

I use korean and english. When I type korean, it does not print anything but just break the assembly code.
It would be nice if a question mark appeared when encountering an unsupported character.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I want to find a good font that also supports Korean, Chinese and Japanese and I found this font called Sarasa Gothic
https://github.com/be5invis/Sarasa-Gothic

There are different versions of the font though, one for each region and then there is one "Classical orthography" variant, with no further explanation given. I tried the "Classical orthography" variant and it worked for "hello" in all 3 languages

안녕하십니까
こんにちは
你好

But I don't know why the regional variant are there in the first place? Maybe just for more exotic characters? If you or someone else have more experience with this, please advice

**Comment by asd142513** [comment]
Some chinese characters have different shape(like 骨 in SC and TC or 海 in J)
![sarasa](https://user-images.githubusercontent.com/62266626/143022219-30e39357-71e6-4ac3-8c1c-5ed1fe967bf0.png)

I think CL is the "original" chinese character. How about using Sarasa Mono CL or Sarasa Mono Slab CL?

It doesn't necessarily print non-alphanumeric characters correctly. It's okay to print '�'. Just please don't ignore them😄.

**Comment by Stuffe** [comment]
Switched editor font to Sarasa Mono Slab CL in 0.329
