### ISSUE TITLE
[Bug]: ALPHA: Cannot run tests in ADDING BYTES

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#99]
### Discord Thread

https://discord.com/channels/828292123936948244/1266106409314025583

### What happened?

The Next and Run fast buttons don't work on the ADDING BYTES level, and make a dud sound effect when clicked. This makes it currently impossible to clear this level.

Right clicking the run fast button to alter the target speed also does not work and results in the same sound effect. 

(Reported by Swan on Discord)

Can be worked around by creating a new schematic.

### Version

0.1083 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment]
fixed next patch
